Repository openshift-kni/cnf-features-deploy, pull requests merged in 2020-12, with the labels that each got.

#377 RAN profile work
  README.md
  feature-configs/cn-ran-overlays/README.md
  feature-configs/cn-ran-overlays/images/ran.png
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/performance/kustomization.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/performance/performance-profile.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/kustomization.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/kustomization.yaml
  feature-configs/cn-ran-overlays/ran-profile/kustomization.yaml
  feature-configs/cn-ran-overlays/ran-profile/site.1.fqdn/kustomization.yaml
  feature-configs/cn-ran-overlays/ran-profile/site.1.fqdn/networks/kustomization.yaml
  feature-configs/cn-ran-overlays/ran-profile/site.1.fqdn/networks/sriov-network-mh.yaml
  feature-configs/cn-ran-overlays/ran-profile/site.1.fqdn/networks/sriov-network-node-policy-dpdk-mh.yaml
Labels: approved, lgtm

#380 Bug 1898531: Update the vendored ptp tests.
  go.mod
  go.sum
  vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#390 Update performance tests.
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  vendor/modules.txt
Labels: approved, lgtm

#388 Bug 1902118: force the gorilla/websocket version to 1.4.2
  go.mod
  go.sum
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#387 Assign more hugepages for latest version of dpdk
  feature-configs/typical-baremetal/performance/performance_profile.patch.yaml
Labels: approved, lgtm

#378 Added IPv4 VRF tests. Updated ginkgo version to 1.14
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  functests/test_suite_test.go
  functests/utils/namespaces/namespaces.go
  functests/utils/pods/pods.go
  functests/vrf/vrf.go
  go.mod
  go.sum
  vendor/github.com/onsi/ginkgo/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/README.md
  vendor/github.com/onsi/ginkgo/config/config.go
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/github.com/onsi/ginkgo/ginkgo/generate_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/main.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/dependencies.go
  vendor/github.com/onsi/ginkgo/ginkgo_dsl.go
  vendor/github.com/onsi/ginkgo/go.mod
  vendor/github.com/onsi/ginkgo/go.sum
  vendor/github.com/onsi/ginkgo/internal/global/init.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_darwin.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_dragonfly.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_freebsd.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_linux.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_linux_mips64le.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_netbsd.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_openbsd.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_solaris.go
  vendor/github.com/onsi/ginkgo/internal/remote/output_interceptor_unix.go
  vendor/github.com/onsi/ginkgo/internal/suite/suite.go
  vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#392 Revert the runtime class name change under PAO tests
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/nodes/nodes.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  vendor/modules.txt
Labels: approved, lgtm

#383 Disable chronyd when using ptp
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/disable-chronyd.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/kustomization.yaml
  feature-configs/demo/ptp/disable-chronyd.yaml
  feature-configs/demo/ptp/kustomization.yaml
Labels: approved, lgtm

#396 DPDK: Change the hugepages number from 4 to 5
  functests/dpdk/dpdk.go
Labels: approved, lgtm

#402 revert ptp namespace to default run-level
  feature-configs/deploy/ptp/01_namespace.yaml
Labels: approved, lgtm

#400 Added vrf plus sriov integration test. Updated vrf test
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  functests/vrf/vrf.go
  functests/vrf/vrf_sriov.go
Labels: approved, lgtm, ok-to-test
