Repository openshift-kni/cnf-features-deploy, pull requests merged in 2020-02, with the labels that each got.

#48 Adding ipv6 functional test
  feature-configs/base/sriov/06-ipv6-network_attachment_defintion.yaml
  feature-configs/base/sriov/kustomization.yaml
  functests/ipv6/ipv6.go
  functests/test_suite_test.go
Labels: approved, lgtm, size/L

#52 Replaced kustomize with oc apply -k
  Makefile
  feature-configs/demo/performance/kustomization.yaml
  feature-configs/demo/ptp/kustomization.yaml
  feature-configs/demo/sctp/kustomization.yaml
  feature-configs/demo/sriov/kustomization.yaml
  feature-configs/e2e-gcp/performance/kustomization.yaml
  feature-configs/e2e-gcp/sctp/kustomization.yaml
  hack/feature-deploy.sh
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/M

#18 Fix for labeling worker nodes
  hack/setup-test-cluster.sh
Labels: approved, lgtm, ok-to-test, size/XS

#26 Run the origin tests as part of the external tests
  external-tests/clone_repo.sh
  external-tests/origintests/test.sh
  hack/run-functests.sh
Labels: approved, lgtm, size/M

#64 Use correct operator image in base config
  feature-configs/base/performance/operator_catalogsource.yaml
  feature-configs/demo/performance/kustomization.yaml
  feature-configs/demo/performance/operator_catalogsource.patch.yaml
  feature-configs/e2e-gcp/performance/kustomization.yaml
  feature-configs/e2e-gcp/performance/operator_catalogsource.patch.yaml
Labels: approved, lgtm, size/S

#63 Skip negative test if no non-sctp nodes are available.
  functests/sctp/sctp.go
Labels: approved, lgtm, size/S

#65 Always create TOOLS_DIR.
  Makefile
Labels: approved, lgtm, size/XS

#62 Remove pause / unpause workaround as CI is supposed to be fixed.
  hack/feature-deploy.sh
  hack/setup-test-cluster.sh
Labels: approved, lgtm, size/M

#55 Create a Demo dpdk build and deployment
  feature-configs/demo/dpdk/build-config.yaml
  feature-configs/demo/dpdk/deployment-config.yaml
  feature-configs/demo/dpdk/dpdk-network.yaml
  feature-configs/demo/dpdk/is_ready.sh
  feature-configs/demo/dpdk/kustomization.yaml
  feature-configs/demo/dpdk/scc.yaml
  feature-configs/demo/dpdk/sriov-networknodepolicy-dpdk.yaml
  feature-configs/demo/sriov/kustomization.yaml
Labels: approved, lgtm, size/L

#57 Add a new test for inter pod connectivity on the default namespace.
  functests/sctp/sctp.go
Labels: approved, lgtm, size/L

#69 Check if the default service account is created for the test namespace.
  functests/sctp/sctp.go
Labels: approved, lgtm, size/XS

#70 Remove the skip as the bz should be fixed.
  functests/sctp/sctp.go
Labels: approved, lgtm, size/XS

#73 Fix demo ptp kustomization
  feature-configs/demo/ptp/kustomization.yaml
Labels: approved, lgtm, size/XS

#74 Make the wait for the checksctp pod longer.
  functests/sctp/sctp.go
Labels: approved, lgtm, size/XS

#66 Add single stack ipv6 test
  feature-configs/base/sriov/kustomization.yaml
  feature-configs/demo/sriov/ipv6-network_attachment_defintion.yaml
  feature-configs/demo/sriov/kustomization.yaml
  functests/ipv6/ipv6.go
  go.mod
  go.sum
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_suite_test.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_test.go
Labels: approved, lgtm, size/L

#60 DPDK functests: adding a simple sanity test
  functests/dpdk/dpdk.go
  functests/test_suite_test.go
  functests/utils/pods/pods.go
Labels: approved, lgtm, ok-to-test, size/L

#79 Fix the ipv6 network attachment
  feature-configs/demo/sriov/ipv6-network_attachment_defintion.yaml
  feature-configs/demo/sriov/kustomization.yaml
Labels: approved, lgtm, size/M

#76 Fix testing section stating that we need FEATURES
  README.md
Labels: approved, lgtm, size/XS

#78 Provide NUMA node for hugepages allocation
  feature-configs/base/performance/performance_profile.yaml
  feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
Labels: approved, lgtm, size/S

#82 Remove the creation of ~/bin and .bashrc as pods run /bin/sh
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#83 Explicitly set HOME env variable
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#85 Rollback ci workaround to make it possible to debug the issue
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#80 Add an example on how to build a UBI8 sctp application relying on OCP builds
  tools/buildingsctp/README.md
  tools/buildingsctp/buildconfig.yaml
  tools/buildingsctp/src/Dockerfile.sctp
  tools/buildingsctp/src/sctp.c
Labels: approved, lgtm, size/L

#86 Adjust performance profile for CI
  feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
Labels: approved, lgtm, size/XS

#81 Proper number of nodes message
  hack/setup-test-cluster.sh
Labels: approved, lgtm, size/XS

#71 Update performance profile to reflect api changes
  feature-configs/base/performance/performance_profile.yaml
  feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
Labels: approved, lgtm, size/XS

#89 Adjust performance profile: set balanceIsolated by default
  feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#90 Make the branch of externally consumed tests configurable.
  external-tests/clone_repo.sh
  external-tests/origintests/test.sh
  external-tests/performance/test.sh
  external-tests/setup.sh
Labels: approved, lgtm, size/S

#92 Add slintes to approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#93 Add a comment to the dpdk deployment
  feature-configs/demo/dpdk/kustomization.yaml
Labels: approved, lgtm, size/XS

#88 fix: use resources for dpdk demo environment
  feature-configs/demo/dpdk/kustomization.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#94 Fix dpdk workload when using version 18.11
  tools/s2i-dpdk/test/test-app/test-template.sh
Labels: approved, lgtm, size/XS

#96 Use different junit filename than external tests.
  hack/run-functests.sh
Labels: approved, lgtm, size/XS

#91 PTP/Prometheus functtest
  functests/ptp/prometheus.go
Labels: approved, lgtm, size/L

#99 Consume the openshift sriov tests as external tests.
  external-tests/setup.sh
  external-tests/sriov/test.sh
Labels: approved, lgtm, size/S

#98 Pin ose tests, perf operator tests and version to 4.4.
  external-tests/setup.sh
  feature-configs/base/performance/operator_catalogsource.yaml
Labels: approved, lgtm, size/XS

#100 Pin the ptp operator and sriov operator versions to 4.5.
  feature-configs/base/ptp/03_subscription.yaml
  feature-configs/base/sriov/03-sriov-subscription.yaml
Labels: approved, lgtm, size/XS

#102 Fix base performance profile cpu isolation
  feature-configs/base/performance/performance_profile.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#103 include custom assets for integration
  feature-configs/integration-kni1/dpdk/kustomization.yaml
  feature-configs/integration-kni1/performance/kustomization.yaml
  feature-configs/integration-kni1/performance/performance_profile_patch.yaml
  feature-configs/integration-kni1/ptp/kustomization.yaml
  feature-configs/integration-kni1/sctp/kustomization.yaml
  feature-configs/integration-kni1/sriov/kustomization.yaml
  feature-configs/integration-kni1/sriov/sriov-networknodepolicy-dpdk.yaml
  feature-configs/integration-kni1/sriov/sriov-unsupported-nics-ds.yaml
  feature-configs/integration-kni1/sriov/sriov-unsupported-nics-entrypoint-cm.yaml
  feature-configs/integration-u08/dpdk/kustomization.yaml
  feature-configs/integration-u08/performance/kustomization.yaml
  feature-configs/integration-u08/performance/performance_profile_patch.yaml
  feature-configs/integration-u08/ptp/kustomization.yaml
  feature-configs/integration-u08/sctp/kustomization.yaml
  feature-configs/integration-u08/sriov/kustomization.yaml
  feature-configs/integration-vms/performance/kustomization.yaml
  feature-configs/integration-vms/performance/performance_profile_patch.yaml
  feature-configs/integration-vms/sctp/kustomization.yaml
  feature-configs/integration-wl4-d17u01b05/performance/kustomization.yaml
  feature-configs/integration-wl4-d17u01b05/performance/performance_profile_patch.yaml
Labels: approved, lgtm, ok-to-test, size/L

#104 Fixes resource name
  feature-configs/integration-kni1/sriov/kustomization.yaml
Labels: approved, lgtm, size/XS
