Repository openshift-kni/cnf-features-deploy, pull requests merged in 2020-11, with the labels that each got.

#317 Provide oslat binary and run script under the cnf-tests image
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testbinaries/oslat-runner/main.go
  functests/test_suite_test.go
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/Dockerfile
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/run-tests.sh
  vendor/modules.txt
Labels: approved, lgtm

#348 Fixed link to detailed list of cnf-tests
  cnf-tests/README.md
Labels: approved, lgtm, ok-to-test

#353 [release-4.6] Use index image instead of registry one to deploy PAO
  feature-configs/deploy/performance/operator_catalogsource.yaml
Labels: approved, lgtm

#355 Bug 1890087: Update PAO tests dependencies.
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/hugepages.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#356 Update latency test and provide documentation
  cnf-tests/README.md
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/api/v2/performanceprofile_conversion.go
  vendor/github.com/openshift-kni/performance-addon-operators/api/v2/performanceprofile_types.go
  vendor/github.com/openshift-kni/performance-addon-operators/api/v2/zz_generated.deepcopy.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/Dockerfile
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/run-tests.sh
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/images/images.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/nodes/nodes.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/utils.go
  vendor/modules.txt
Labels: approved, lgtm

#354 Bug 1894861: Switch to the PAO namespace used in the docs and make the namespaces configurable
  feature-configs/deploy/performance/operator-namespace.yaml
  feature-configs/deploy/performance/operator_operatorgroup.yaml
  feature-configs/deploy/performance/operator_subscription.yaml
  functests/dpdk/dpdk.go
  functests/sctp/sctp_sriov.go
  functests/utils/consts.go
  functests/utils/namespaces/namespaces.go
  functests/utils/reporter.go
  go.mod
  go.sum
  validationsuite/cluster/validation.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/consts.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/namespaces/namespaces.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/pods/pods.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/profile/profile.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/utils.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#359 Generate table of content for the cnf-tests README
  cnf-tests/README.md
Labels: approved, lgtm

#361 Bug 1889835: Update the ptp tests dependency.
  go.mod
  go.sum
  vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#360 Bug 1895871: DPDK test: don't backup and create sriov configuration in regular mode.
  functests/dpdk/dpdk.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#362 Replace 4.6 references with 4.7
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  cnf-tests/images.json
  external-tests/origintests/test.sh
  functests/utils/images/images.go
  hack/run-functests.sh
Labels: approved, lgtm

#363 Fix dpdk discovery mode.
  functests/utils/discovery/discovery.go
Labels: approved, lgtm

#364 Fix dpdk discovery mode.
  functests/utils/discovery/discovery.go
Labels: approved, lgtm

#366 Bug 1890089: Update to latest sriov operator tests.
  go.mod
  go.sum
  vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#367 Bug 1896798: Make it possible to override the namespace used by the operators, plus switch the pao default one.
  feature-configs/deploy/performance/operator-namespace.yaml
  feature-configs/deploy/performance/operator_operatorgroup.yaml
  feature-configs/deploy/performance/operator_subscription.yaml
  functests/dpdk/dpdk.go
  functests/sctp/sctp_sriov.go
  functests/utils/consts.go
  functests/utils/namespaces/namespaces.go
  functests/utils/reporter.go
  go.mod
  go.sum
  validationsuite/cluster/validation.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/consts.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/namespaces/namespaces.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/pods/pods.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#369 Add an option to run latency test together with other tests
  hack/run-functests.sh
Labels: approved, lgtm

#371 Add iptables and kmod installation to cnf-tests image for xt_u32 testing
  cnf-tests/Dockerfile.openshift
Labels: approved, lgtm

#370 Fix Mellanox DPDK issue
  feature-configs/demo/dpdk/deployment-config.yaml
  functests/dpdk/dpdk.go
Labels: approved, lgtm

#357 Add xt_u32 feature tests to the test suite.
  Makefile
  cnf-tests/README.md
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/docgen/validation.json
  feature-configs/deploy/xt_u32/is_ready.sh
  functests/test_suite_test.go
  functests/utils/namespaces/namespaces.go
  functests/utils/reporter.go
  functests/xt_u32/xt_u32.go
  validationsuite/cluster/validation.go
Labels: approved, lgtm
