Repository openshift-kni/cnf-features-deploy, pull requests merged in 2020-01, with the labels that each got.

#5 Sctp kustomize
  feature-configs/base/sctp/kustomization.yaml
  feature-configs/base/sctp/sctp_module_mc.yaml
  feature-configs/base/sctp/sctp_role.yaml
  feature-configs/demo/sctp/kustomization.yaml
  feature-configs/demo/sctp/sctp_machineconfigpool_patch.yaml
Labels: approved, lgtm, size/M

#4 Added kustomization for performance
  Makefile
  README.md
  feature-configs/base/performance/kustomization.yaml
  feature-configs/base/performance/operator-namespace.yaml
  feature-configs/base/performance/operator_catalogsource.yaml
  feature-configs/base/performance/operator_operatorgroup.yaml
  feature-configs/base/performance/operator_subscription.yaml
  feature-configs/base/performance/performance_profile.yaml
  feature-configs/demo/performance/kustomization.yaml
  feature-configs/demo/performance/operator_catalogsource.patch.yaml
  feature-configs/demo/performance/performance_profile.patch.yaml
  feature-configs/e2e-gcp/performance/kustomization.yaml
  feature-configs/e2e-gcp/performance/operator_catalogsource.patch.yaml
  feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
  hack/feature-deploy.sh
  hack/label-worker-rt.sh
Labels: approved, lgtm, size/L

#7 Kustomize per machine config pool basis.
  feature-configs/base/sctp/kustomization.yaml
  feature-configs/base/sctp/sctp_role.yaml
  feature-configs/demo/sctp/kustomization.yaml
  feature-configs/demo/sctp/sctp_machineconfigpool_patch.yaml
  feature-configs/demo/sctp/sctp_module_mc_patch.yaml
Labels: approved, lgtm, size/M

#9 Add ptp tests from baremetal deploy repo
  functests/ptp/ptp.go
  functests/test_suite_test.go
  functests/utils/client/clients.go
  go.sum
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/github.com/golang/protobuf/ptypes/any/any.pb.go
  vendor/github.com/golang/protobuf/ptypes/any/any.proto
  vendor/github.com/golang/protobuf/ptypes/doc.go
  vendor/github.com/golang/protobuf/ptypes/duration.go
  vendor/github.com/golang/protobuf/ptypes/duration/duration.pb.go
  vendor/github.com/golang/protobuf/ptypes/duration/duration.proto
  vendor/github.com/golang/protobuf/ptypes/timestamp.go
  vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.pb.go
  vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.proto
  vendor/github.com/googleapis/gnostic/LICENSE
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.proto
  vendor/github.com/googleapis/gnostic/OpenAPIv2/README.md
  vendor/github.com/googleapis/gnostic/OpenAPIv2/openapi-2.0.json
  vendor/github.com/googleapis/gnostic/compiler/README.md
  vendor/github.com/googleapis/gnostic/compiler/context.go
  vendor/github.com/googleapis/gnostic/compiler/error.go
  vendor/github.com/googleapis/gnostic/compiler/extension-handler.go
  vendor/github.com/googleapis/gnostic/compiler/helpers.go
  vendor/github.com/googleapis/gnostic/compiler/main.go
  vendor/github.com/googleapis/gnostic/compiler/reader.go
  vendor/github.com/googleapis/gnostic/extensions/README.md
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
  vendor/github.com/googleapis/gnostic/extensions/extension.proto
  vendor/github.com/googleapis/gnostic/extensions/extensions.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/discovery/doc.go
  vendor/k8s.io/client-go/discovery/helper.go
  vendor/k8s.io/client-go/kubernetes/typed/apps/v1/apps_client.go
  vendor/k8s.io/client-go/kubernetes/typed/apps/v1/controllerrevision.go
  vendor/k8s.io/client-go/kubernetes/typed/apps/v1/daemonset.go
  vendor/k8s.io/client-go/kubernetes/typed/apps/v1/deployment.go
  vendor/k8s.io/client-go/kubernetes/typed/apps/v1/doc.go
  vendor/k8s.io/client-go/kubernetes/typed/apps/v1/generated_expansion.go
  vendor/k8s.io/client-go/kubernetes/typed/apps/v1/replicaset.go
  vendor/k8s.io/client-go/kubernetes/typed/apps/v1/statefulset.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#6 Create ptp deployment manifests
  feature-configs/base/ptp/01_namespace.yaml
  feature-configs/base/ptp/02_operator_group.yaml
  feature-configs/base/ptp/03_subscription.yaml
  feature-configs/base/ptp/kustomization.yaml
  feature-configs/demo/ptp/kustomization.yaml
  feature-configs/demo/ptp/subscription.yaml
Labels: approved, lgtm, size/M

#8 Add sctp tests to the test suite and add waiting logic for CI
  Makefile
  feature-configs/base/sctp/is_ready.sh
  feature-configs/e2e-gcp/sctp/kustomization.yaml
  feature-configs/e2e-gcp/sctp/sctp_module_mc_patch.yaml
  functests/sctp/sctp.go
  functests/test_suite_test.go
  functests/utils/execute/ginkgo.go
  functests/utils/namespaces/namespaces.go
  go.mod
  go.sum
  hack/feature-wait.sh
  hack/label-worker-rt.sh
  hack/setup-test-cluster.sh
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/go.mod
  vendor/github.com/onsi/gomega/go.sum
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/vincent-petithory/dataurl/dataurl.go
  vendor/k8s.io/utils/pointer/OWNERS
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#15 Set the $GOPATH/bin variable to path when running tests
  hack/run-functests.sh
Labels: approved, lgtm, size/S

#21 Fix 'make govet' execution in ci
  Makefile
Labels: approved, lgtm, size/XS

#19 Add a demo for ptp grandmaster and slave
  feature-configs/base/ptp/04-ptpconfig.yaml
  feature-configs/base/ptp/kustomization.yaml
  feature-configs/demo/ptp/kustomization.yaml
  feature-configs/demo/ptp/ptpconfig-grandmaster.yaml
  feature-configs/demo/ptp/ptpconfig-slave.yaml
Labels: approved, lgtm, size/M

#23 update pinned repo
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#22 Pause / unpause the machine pools to have one reboot only.
  hack/feature-wait.sh
  hack/setup-test-cluster.sh
Labels: approved, lgtm, size/S

#11 Add sriov feature deployment
  feature-configs/base/sriov/01-sriov-namespace.yaml
  feature-configs/base/sriov/02-sriov-operatorgroup.yaml
  feature-configs/base/sriov/03-sriov-subscription.yaml
  feature-configs/base/sriov/04-sriov-networknodepolicy.yaml
  feature-configs/base/sriov/05-sriov-network.yaml
  feature-configs/base/sriov/kustomization.yaml
  feature-configs/demo/sriov/kustomization.yaml
  feature-configs/demo/sriov/sriov-networknodepolicy.yaml
  feature-configs/demo/sriov/sriov-subscription.yaml
Labels: approved, lgtm, size/M

#14 Check for having at least one node so tests won't panic.
  functests/sctp/sctp.go
  functests/test_suite_test.go
Labels: approved, lgtm, size/XS

#17 Move the sctptester source code from baremetal deploy repo to here.
  functests/sctp/sctp.go
  go.mod
  go.sum
  tools/sctptester/Dockerfile
  tools/sctptester/main.go
  vendor/github.com/ishidawataru/sctp/.gitignore
  vendor/github.com/ishidawataru/sctp/.travis.yml
  vendor/github.com/ishidawataru/sctp/GO_LICENSE
  vendor/github.com/ishidawataru/sctp/LICENSE
  vendor/github.com/ishidawataru/sctp/README.md
  vendor/github.com/ishidawataru/sctp/ipsock_linux.go
  vendor/github.com/ishidawataru/sctp/sctp.go
  vendor/github.com/ishidawataru/sctp/sctp_linux.go
  vendor/github.com/ishidawataru/sctp/sctp_unsupported.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#25 Have a custom pool that matches two out of three nodes.
  feature-configs/base/sctp/is_ready.sh
  feature-configs/base/sctp/sctp_module_mc.yaml
  feature-configs/e2e-gcp/sctp/sctp_module_mc_patch.yaml
  functests/sctp/sctp.go
  hack/setup-test-cluster.sh
Labels: approved, lgtm, size/M

#16 Add Marcin Mirecki as a reviewer
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#24 Added more tests to sctp feature. Tests: KernelModule, Connectivity
  functests/sctp/sctp.go
Labels: approved, lgtm, ok-to-test, size/L

#29 Fail if the deployment did not finish successfully.
  hack/feature-deploy.sh
Labels: approved, lgtm, size/XS

#28 Consume the new version of the Performance Operator
  README.md
  feature-configs/base/performance/operator_catalogsource.yaml
  feature-configs/base/performance/operator_subscription.yaml
  feature-configs/demo/performance/operator_catalogsource.patch.yaml
  feature-configs/demo/performance/performance_profile.patch.yaml
  feature-configs/e2e-gcp/performance/operator_catalogsource.patch.yaml
  feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
  hack/feature-deploy.sh
  hack/setup-test-cluster.sh
Labels: approved, lgtm, size/M

#31 Check for lenght of nodes and gracefully fail instead of throwing panics
  functests/sctp/sctp.go
Labels: approved, lgtm, size/XS

#32 Fix the machine config pool so the operator can recognize the pool
  hack/setup-test-cluster.sh
Labels: approved, lgtm, size/XS

#34 remove unused references to worker-rt label
  functests/utils/consts.go
Labels: approved, lgtm, size/XS

#33 Move the pause / unpause logic in feature_deploy.sh
  hack/feature-deploy.sh
  hack/feature-wait.sh
  hack/setup-test-cluster.sh
Labels: approved, lgtm, size/M

#36 Fix the sctp machine config role in demo layer
  feature-configs/demo/sctp/sctp_module_mc_patch.yaml
Labels: approved, lgtm, size/XS

#38 Install skopeo as it's needed to harvest origin test binary
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#37 Update README to the latest changes.
  README.md
Labels: approved, lgtm, size/M

#39 Alias oc with kubectl as it's needed to ose tests.
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#41 Use gimme to install Go
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/S

#43 Install findutils as they are not there anymore after removing Go
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#45 Align PATH to the new go location
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#46 Fix go lint by adding GOPATH/bin to PATH
  hack/lint.sh
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#47 Install gcc (hoping it's the last dependency)
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#42 Change the sriov network config in demo
  feature-configs/demo/sriov/sriov-networknodepolicy-dpdk.yaml
  feature-configs/demo/sriov/sriov-networknodepolicy.yaml
Labels: approved, lgtm, size/XS

#44 change wait timeout to accomomdate long boot times
  hack/feature-wait.sh
Labels: approved, lgtm, needs-ok-to-test, size/XS

#49 Makes variables section smaller as suggested
  README.md
Labels: approved, lgtm, size/XS

#53 Add ptp labels on the nodes
  hack/setup-test-cluster.sh
Labels: approved, lgtm, size/S

#54 Added python2 for making gcloud client in CI happy
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#50 Use mirrored upstream repo for performance images
  feature-configs/e2e-gcp/performance/operator_catalogsource.patch.yaml
Labels: approved, lgtm, size/XS

#56 Change the FEATURES example as we expect it to be a string in README
  README.md
Labels: approved, lgtm, size/XS

#58 Patch the cluster network operator for dhcp
  hack/setup-test-cluster.sh
Labels: approved, lgtm, size/XS

#59 Remove kubectl alias and create a symlink to oc.
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS
