Repository openshift-kni/cnf-features-deploy, pull requests merged in 2020-08, with the labels that each got.

#291 Fix the CPU set test
  functests/dpdk/dpdk.go
Labels: approved, lgtm

#290 Use default network for dpdk test
  functests/dpdk/dpdk.go
Labels: approved, lgtm

#288 Add sleep time before checking last dpdk s2i build
  feature-configs/deploy/dpdk/post_deploy.sh
Labels: approved, lgtm, ok-to-test

#294 Delete dpdk failed build
  feature-configs/deploy/dpdk/post_deploy.sh
Labels: approved, lgtm

#296 performance profile: consume api v1
  cnf-tests/README.md
  feature-configs/demo/performance/performance_profile.yaml
  feature-configs/integration-base/performance/performance_profile.yaml
  feature-configs/integration-kni1/performance/performance_profile_patch.yaml
  feature-configs/integration-u08/performance/performance_profile_patch.yaml
  feature-configs/integration-vms/performance/performance_profile_patch.yaml
  feature-configs/integration-wl4-d17u01b05/performance/performance_profile_patch.yaml
  feature-configs/typical-baremetal/performance/performance_profile.patch.yaml
  functests/dpdk/dpdk.go
  functests/utils/discovery/discovery.go
  functests/utils/k8sreporter/example/main.go
  functests/utils/reporter.go
Labels: approved, lgtm

#295 Update the CI performance profile
  feature-configs/typical-baremetal/performance/performance_profile.patch.yaml
Labels: approved, lgtm

#298 [release 4.5] Update owner base on master
  OWNERS_ALIASES
Labels: approved, lgtm

#300 Delete and recreate the dpdk build if the status is "Error"
  feature-configs/deploy/dpdk/post_deploy.sh
Labels: approved, lgtm

#297 [release 4.5] Fix the CPU set test
  functests/dpdk/dpdk.go
Labels: approved, lgtm

#299 [release 4.5] Use default network for dpdk test
  functests/dpdk/dpdk.go
Labels: approved, lgtm

#301 Bug 1870669: Bump latest sriov 4.6 tests
  go.mod
  go.sum
  vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/helper.go
  vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/github.com/openshift/sriov-network-operator/test/util/cluster/cluster.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#303 Fix the cpuset for huge-pages test
  functests/dpdk/dpdk.go
Labels: approved, lgtm

#302 support dpdk tests with ovn-kubernetes share gw
  functests/dpdk/dpdk.go
Labels: approved, lgtm

#306 Fix a nil pointer exception in the dpdk tests
  functests/dpdk/dpdk.go
Labels: approved, lgtm
