Repository openshift-kni/cnf-features-deploy, pull requests merged in 2020-03, with the labels that each got.

#106 Fixed MCP by removing null value
  hack/setup-test-cluster.sh
Labels: approved, lgtm, size/XS

#105 Added fixes to the kni1 environment
  feature-configs/integration-kni1/dpdk/kustomization.yaml
  feature-configs/integration-kni1/dpdk/sriov-networknodepolicy-dpdk.yaml
  feature-configs/integration-kni1/performance/kustomization.yaml
  feature-configs/integration-kni1/ptp/kustomization.yaml
  feature-configs/integration-kni1/ptp/ptpconfig-grandmaster.yaml
  feature-configs/integration-kni1/ptp/ptpconfig-slave.yaml
  feature-configs/integration-kni1/sctp/kustomization.yaml
  feature-configs/integration-kni1/sctp/sctp-demo-ns.yaml
  feature-configs/integration-kni1/sctp/sctp-demo-svc.yaml
  feature-configs/integration-kni1/sriov/kustomization.yaml
  feature-configs/integration-kni1/sriov/sriov-networknodepolicy.yaml
  feature-configs/integration-kni1/sriov/sriov-subscription.yaml
  feature-configs/integration-kni1/sriov/sriov-unsupported-nics-ds.yaml
  feature-configs/integration-kni1/sriov/sriov-unsupported-nics-entrypoint-cm.yaml
Labels: approved, lgtm, size/L

#109 Temporarily disable RT kernel
  feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
Labels: approved, lgtm, size/XS

#111 Revert "Temporarily disable RT kernel"
  feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
Labels: approved, lgtm, size/XS

#110 Be less verbose while waiting for all deployments to be successful
  hack/feature-deploy.sh
Labels: approved, lgtm, size/S

#108 Added new numa.topologyPolicy to performance profile for CI
  feature-configs/base/performance/performance_profile.yaml
  feature-configs/e2e-gcp/performance/performance_profile.patch.yaml
Labels: approved, lgtm, size/XS

#112 Update dpdk s2i build
  tools/s2i-dpdk/test/test-app/build.sh
  tools/s2i-dpdk/test/test-app/test-pmd/Makefile
  tools/s2i-dpdk/test/test-app/test-pmd/bpf_cmd.c
  tools/s2i-dpdk/test/test-app/test-pmd/bpf_cmd.h
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_flow.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_mtr.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_mtr.h
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_tm.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_tm.h
  tools/s2i-dpdk/test/test-app/test-pmd/config.c
  tools/s2i-dpdk/test/test-app/test-pmd/csumonly.c
  tools/s2i-dpdk/test/test-app/test-pmd/flowgen.c
  tools/s2i-dpdk/test/test-app/test-pmd/icmpecho.c
  tools/s2i-dpdk/test/test-app/test-pmd/ieee1588fwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/iofwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/macfwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/macswap.c
  tools/s2i-dpdk/test/test-app/test-pmd/meson.build
  tools/s2i-dpdk/test/test-app/test-pmd/noisy_vnf.c
  tools/s2i-dpdk/test/test-app/test-pmd/parameters.c
  tools/s2i-dpdk/test/test-app/test-pmd/rxonly.c
  tools/s2i-dpdk/test/test-app/test-pmd/softnicfwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/testpmd.c
  tools/s2i-dpdk/test/test-app/test-pmd/testpmd.h
  tools/s2i-dpdk/test/test-app/test-pmd/txonly.c
  tools/s2i-dpdk/test/test-app/test-pmd/util.c
  tools/s2i-dpdk/test/test-app/test-template.sh
Labels: approved, lgtm, size/XXL

#114 Add sriov tests for release 4.4
  external-tests/setup.sh
  external-tests/sriov/tests.sh
Labels: approved, lgtm

#116 [release-4.4] Change sriov tests to test
  external-tests/sriov/test.sh
Labels: approved, lgtm

#115 Fix dpdk test application
  tools/s2i-dpdk/test/test-app/test-template.sh
Labels: approved, lgtm

#118 Remove sriov ipv6 tests as they are moved to the sriov tests repo.
  functests/ipv6/ipv6.go
  functests/test_suite_test.go
Labels: approved, lgtm

#117 Add Numa aliment test for DPDK workload
  functests/dpdk/dpdk.go
Labels: approved, lgtm

#120 add support for setup-test-cluster rerun
  hack/setup-test-cluster.sh
Labels: approved, lgtm, ok-to-test

#113 Add SCTP tests validating network policy.
  functests/sctp/sctp.go
  functests/utils/client/clients.go
  functests/utils/namespaces/namespaces.go
  vendor/k8s.io/client-go/kubernetes/typed/networking/v1/doc.go
  vendor/k8s.io/client-go/kubernetes/typed/networking/v1/generated_expansion.go
  vendor/k8s.io/client-go/kubernetes/typed/networking/v1/networking_client.go
  vendor/k8s.io/client-go/kubernetes/typed/networking/v1/networkpolicy.go
  vendor/modules.txt
Labels: approved, lgtm

#123 Add Yuval Kashtan as a reviewer
  OWNERS_ALIASES
Labels: approved, lgtm, ok-to-test

#122 fix ptp labels to skip virtual machines
  hack/README.md
  hack/setup-test-cluster.sh
Labels: approved, lgtm, ok-to-test

#121 Hugepages allocation tests
  functests/dpdk/dpdk.go
  functests/utils/pods/pods.go
Labels: approved, lgtm

#127 Fixes wrong numa node in kni1 environment
  feature-configs/integration-kni1/performance/performance_profile_patch.yaml
Labels: approved, lgtm

#129 Add skip flag to ptp tests if less than 2 slaves, Nodes selected
  functests/ptp/ptp.go
Labels: approved, lgtm, ok-to-test

#130 Add Polarion reporter
  functests/test_suite_test.go
  go.mod
  go.sum
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: approved, lgtm

#128 add correct cwd to run functests
  hack/run-functests.sh
Labels: approved, lgtm

#133 Consume sriov tests from the sriov-operator repository.
  external-tests/sriov/test.sh
Labels: approved, lgtm
