Repository openshift-kni/cnf-features-deploy, pull requests merged in 2020-10, with the labels that each got.

#336 Don't call performance clean if discovery mode is enabled.
  functests/test_suite_test.go
Labels: approved, lgtm

#338 Consume the latest sriov / ptp tests.
  go.mod
  go.sum
  vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
  vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/modules.txt
Labels: approved, lgtm

#339 Fix the slave labelling selection for the ptp metrics test.
  functests/ptp/ptp.go
Labels: approved, lgtm

#340 Update performance tests.
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/profiles/profiles.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/utils.go
  vendor/modules.txt
Labels: approved, lgtm

#341 Update PAO dependencies
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/profiles/profiles.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/utils.go
  vendor/modules.txt
Labels: approved, lgtm

#344 Bug 1889631: Make dpdk test more robust
  functests/dpdk/dpdk.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#329 DPDK performance profile changes in doc / code.
  cnf-tests/README.md
  functests/dpdk/dpdk.go
Labels: approved, lgtm

#342 Bug 1889275: When looking for the mc that enables sctp, skip if the raw config is empty
  functests/sctp/sctp.go
  validationsuite/cluster/validation.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#347 Update sriov, ptp, performance dependencies.
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/hugepages.go
  vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
  vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/helper.go
  vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/modules.txt
Labels: approved, lgtm

#293 add xt_u32 as a feature
  feature-configs/demo/xt_u32/kustomization.yaml
  feature-configs/deploy/xt_u32/is_ready.sh
  feature-configs/deploy/xt_u32/kustomization.yaml
  feature-configs/deploy/xt_u32/xt_u32_module_mc.yaml
  feature-configs/typical-baremetal/xt_u32/kustomization.yaml
Labels: approved, lgtm

#351 Rename xt_u32 MachineConfig as it can't include '_' character
  feature-configs/deploy/xt_u32/xt_u32_module_mc.yaml
Labels: approved, lgtm

#349 Use index image to deploy PAO
  feature-configs/deploy/performance/operator_catalogsource.yaml
  feature-configs/deploy/performance/operator_operatorgroup.yaml
  feature-configs/deploy/performance/operator_subscription.yaml
Labels: approved, lgtm
