Repository openshift-kni/cnf-features-deploy, pull requests merged in 2020-07, with the labels that each got.

#274 Update PAO dependencies
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/apis/performance/v1alpha1/performanceprofile_types.go
  vendor/modules.txt
Labels: approved, lgtm

#266 Delegate the cleaning logic to each suite's clean.All method
  functests/dpdk/dpdk.go
  functests/test_suite_test.go
  functests/utils/clean/clean.go
  functests/utils/clean/sriov_clean.go
  go.mod
  go.sum
  hack/run-functests.sh
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/hugepages.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/topology_manager.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/clean/clean.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/consts.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/nodes/nodes.go
  vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
  vendor/github.com/openshift/ptp-operator/test/utils/clean/clean.go
  vendor/github.com/openshift/ptp-operator/test/utils/consts.go
  vendor/github.com/openshift/ptp-operator/test/utils/nodes/nodes.go
  vendor/github.com/openshift/ptp-operator/test/utils/pods/pods.go
  vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/helper.go
  vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/init.go
  vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/vfs_assignement.go
  vendor/github.com/openshift/sriov-network-operator/test/util/clean/clean.go
  vendor/github.com/openshift/sriov-network-operator/test/util/client/clients.go
  vendor/github.com/openshift/sriov-network-operator/test/util/cluster/cluster.go
  vendor/github.com/openshift/sriov-network-operator/test/util/namespaces/namespaces.go
  vendor/github.com/openshift/sriov-network-operator/test/util/nodes/nodes.go
  vendor/github.com/openshift/sriov-network-operator/test/util/pod/pod.go
  vendor/modules.txt
Labels: approved, lgtm

#273 Add discovery of performance profile in dpdk tests
  functests/dpdk/dpdk.go
  functests/utils/nodes/nodes.go
Labels: approved, lgtm

#275 Add typical baremetal config
  feature-configs/typical-baremetal/dpdk/kustomization.yaml
  feature-configs/typical-baremetal/performance/kustomization.yaml
  feature-configs/typical-baremetal/performance/performance_profile.patch.yaml
  feature-configs/typical-baremetal/ptp/kustomization.yaml
  feature-configs/typical-baremetal/sctp/kustomization.yaml
  feature-configs/typical-baremetal/sriov/kustomization.yaml
Labels: approved, lgtm, ok-to-test

#277 Add an integration test checking SCTP traffic across an SRIOV device.
  cnf-tests/README.md
  functests/dpdk/dpdk.go
  functests/sctp/sctp.go
  functests/sctp/sctp_sriov.go
  functests/utils/sriov/sriov.go
  go.mod
  go.sum
  vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/sriovnetwork_types.go
  vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/sriovnetworknodepolicy_types.go
  vendor/github.com/openshift/sriov-network-operator/pkg/client/clientset/versioned/typed/sriovnetwork/v1/generated_expansion.go
  vendor/github.com/openshift/sriov-network-operator/pkg/client/clientset/versioned/typed/sriovnetwork/v1/sriovnetwork.go
  vendor/github.com/openshift/sriov-network-operator/pkg/client/clientset/versioned/typed/sriovnetwork/v1/sriovnetwork_client.go
  vendor/github.com/openshift/sriov-network-operator/pkg/client/clientset/versioned/typed/sriovnetwork/v1/sriovnetworknodepolicy.go
  vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/github.com/openshift/sriov-network-operator/test/util/cluster/cluster.go
  vendor/github.com/openshift/sriov-network-operator/test/util/discovery/discovery.go
  vendor/modules.txt
Labels: approved, lgtm

#276 Discovery mode for sriov network policies
  functests/dpdk/dpdk.go
  functests/utils/discovery/discovery.go
  functests/utils/nodes/nodes.go
Labels: approved, lgtm

#279 Fix the dpdk sriov policy
  functests/dpdk/dpdk.go
Labels: approved, lgtm

#281 Add more approvers.
  OWNERS_ALIASES
Labels: approved, lgtm

#278 Discovery mode - README updated
  cnf-tests/README.md
Labels: approved, lgtm

#280 [release 4.5] Bug 1858849: Use right driver for dpdk 4.5
  functests/dpdk/dpdk.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#284 vendor latest sriov-network-operator release 4.6
  go.mod
  go.sum
  vendor/github.com/openshift/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/modules.txt
Labels: approved, lgtm

#269 Add dpdk s2i build script for dpdk deployment
  README.md
  feature-configs/deploy/dpdk/post_deploy.sh
  hack/feature-deploy.sh
Labels: approved, lgtm, ok-to-test

#286 [Release 4.5] Bump Sriov version
  go.mod
  go.sum
  vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/sriovnetworknodepolicy_types.go
  vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/sriovnetworknodestate_types.go
  vendor/github.com/openshift/sriov-network-operator/test/util/cluster/cluster.go
  vendor/modules.txt
Labels: approved, lgtm

#285 Add a note about how to not to clean the performance profile after the test is finished.
  cnf-tests/README.md
Labels: approved, lgtm

#287 Disable PTP offset test when not running in discovery mode.
  functests/ptp/ptp.go
Labels: approved, lgtm

#283 Use the imagestream if available in dpdk test
  functests/dpdk/dpdk.go
  functests/utils/client/clients.go
  vendor/github.com/openshift/api/image/docker10/doc.go
  vendor/github.com/openshift/api/image/docker10/dockertypes.go
  vendor/github.com/openshift/api/image/docker10/register.go
  vendor/github.com/openshift/api/image/docker10/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/dockerpre012/deepcopy.go
  vendor/github.com/openshift/api/image/dockerpre012/doc.go
  vendor/github.com/openshift/api/image/dockerpre012/dockertypes.go
  vendor/github.com/openshift/api/image/dockerpre012/register.go
  vendor/github.com/openshift/api/image/dockerpre012/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/consts.go
  vendor/github.com/openshift/api/image/v1/doc.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/generated.proto
  vendor/github.com/openshift/api/image/v1/legacy.go
  vendor/github.com/openshift/api/image/v1/register.go
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/image.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/image_client.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagesignature.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestream.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamimage.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamimport.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreammapping.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamtag.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagetag.go
  vendor/modules.txt
Labels: approved, lgtm
