Repository openshift-kni/cnf-features-deploy, pull requests merged in 2021-12, with the labels that each got.

#823 oot-driver: remove the patch package install
  tools/oot-driver/charts/iavf-driver-0.0.1/Dockerfile-driver.SRO
  tools/oot-driver/charts/ice-driver-0.0.1/Dockerfile-driver.SRO
Labels: approved, lgtm

#798 Update PAO manifests to use 4.10 images
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  feature-configs/deploy/performance/operator_catalogsource.yaml
  feature-configs/deploy/performance/operator_subscription.yaml
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/netqueues.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/daemonset/daemonset.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/events/events.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/images/images.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/images/prepull.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/nodes/nodes.go
  vendor/modules.txt
Labels: approved, lgtm

#814 cnf-tests: Fix ptp prometheus test
  cnf-tests/testsuites/e2esuite/ptp/prometheus.go
Labels: approved, lgtm

#827 oot-driver: remove the patch package install
  tools/oot-driver/charts/iavf-driver-0.0.1/Dockerfile-driver.SRO
  tools/oot-driver/charts/ice-driver-0.0.1/Dockerfile-driver.SRO
Labels: approved, lgtm

#822 ztp: Ignore hidden files in extra-manifests directories
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/user-extra-manifest/.bad-non-yaml-file.yaml
Labels: approved, lgtm

#831 ztp: Add templated MC objects for every defined role
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/role-templates/good.yaml.tmpl
Labels: approved, lgtm

#824 ztp: Update PolicyGenTemplate to use ArgoCD kustomize
  ztp/.gitignore
  ztp/gitops-subscriptions/argocd/deployment/app-project.yaml
  ztp/gitops-subscriptions/argocd/deployment/clusters-app.yaml
  ztp/gitops-subscriptions/argocd/deployment/gitops-policy-rolebinding.yaml
  ztp/gitops-subscriptions/argocd/deployment/hook-policies-sub-acm-binding.yaml
  ztp/gitops-subscriptions/argocd/deployment/hook-policies-sub-role.yaml
  ztp/gitops-subscriptions/argocd/deployment/kustomization.yaml
  ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
  ztp/gitops-subscriptions/argocd/deployment/policies-app.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/ns.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/post-sync.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/pre-sync.yaml
  ztp/policygenerator-kustomize-plugin/Makefile
  ztp/policygenerator-kustomize-plugin/kustomization.yaml
  ztp/policygenerator-kustomize-plugin/policyGenerator.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/policygenerator/Makefile
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilder_test.go
  ztp/policygenerator/policyGen/policyTemplate.go
  ztp/policygenerator/policyGenerator.go
  ztp/policygenerator/policyGenerator_test.go
  ztp/policygenerator/resources/cluster-crs.yaml
  ztp/policygenerator/utils/filesHandler.go
  ztp/policygenerator/utils/utils.go
  ztp/resource-generator/Containerfile
Labels: approved, lgtm

#825 Bug 2025082: ztp: Support complianceType for full PGT
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/common-ranGen.yaml
  ztp/ran-crd/policy-gen-template-crd.yaml
  ztp/source-crs/ClusterLogNS.yaml
  ztp/source-crs/ClusterLogOperGroup.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyBuilder.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyBuilder_test.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyHelper.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/testData/GenericSourceFiles/GenericNamespace.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/testData/GenericSourceFiles/GenericOperatorGroup.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/testData/GenericSourceFiles/GenericSubscription.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGenerator.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfig_test.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/utils/utils.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#835 ztp: Update PerformanceProfile source-cr to api v2
  ztp/source-crs/PerformanceProfile.yaml
Labels: approved, lgtm

#833 Bug 2028881: ztp: Support for user content not in the source-cr
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilderOverlay_test.go
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericCR.yaml
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericDataCR.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#830 vendor: update ptp operator vendored version
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  go.mod
  go.sum
  vendor/github.com/openshift/ptp-operator/api/v1/ptpconfig_types.go
  vendor/github.com/openshift/ptp-operator/api/v1/ptpconfig_webhook.go
  vendor/github.com/openshift/ptp-operator/api/v1/ptpoperatorconfig_types.go
  vendor/github.com/openshift/ptp-operator/api/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/ptp-operator/test/conformance/ptp/ptp.go
  vendor/github.com/openshift/ptp-operator/test/utils/client/clients.go
  vendor/github.com/openshift/ptp-operator/test/utils/consts.go
  vendor/modules.txt
Labels: approved, lgtm

#837 owners: Add Jim Ramsay (lack) to ZTP approvers list
  OWNERS_ALIASES
Labels: approved, lgtm

#840 ztp: fix ArgoCD deployment policies-app-project.yaml path
  ztp/gitops-subscriptions/argocd/deployment/kustomization.yaml
Labels: approved, lgtm, ok-to-test

#841 ztp: Remove incorrect labels from reference PGT
  ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/ns.yaml
Labels: approved, lgtm

#847 cnf-tests: Fix ptp Prometheus test
  cnf-tests/testsuites/e2esuite/ptp/prometheus.go
Labels: approved, lgtm

#725 cnf-tests: add tap device tests
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  go.mod
  go.sum
  vendor/github.com/cespare/xxhash/v2/.travis.yml
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodepolicy_types.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/zz_generated.deepcopy.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
  vendor/modules.txt
Labels: approved, lgtm

#846 cnf-tests: Fix ovs_qos flake
  cnf-tests/testsuites/e2esuite/ovs_qos/ovs_qos.go
Labels: approved, lgtm

#842 ztp: Fix siteConfig binary execution and Add more unit test
  ztp/siteconfig-generator/README.md
  ztp/siteconfig-generator/main.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Labels: approved, lgtm

#843 ztp: Update Readme with repo configuration details
  ztp/gitops-subscriptions/argocd/README.md
Labels: approved, lgtm

#854 ztp: Fix resourece-generator Make and Readme
  ztp/resource-generator/Containerfile
  ztp/resource-generator/Makefile
  ztp/resource-generator/README.md
Labels: approved, lgtm

#859 ztp: Minor cleanup of unit tests
  ztp/policygenerator/policyGen/policyBuilderOverlay_test.go
Labels: approved, lgtm

#849 ztp: Bug 2028590: Move our execstart last
  ztp/extra-manifests-builder/01-container-mount-ns-and-kubelet-conf/90-container-mount-namespace-kubelet.conf
  ztp/extra-manifests-builder/01-container-mount-ns-and-kubelet-conf/90-container-mount-namespace.conf
  ztp/extra-manifests-builder/01-container-mount-ns-and-kubelet-conf/build.sh
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/source-crs/extra-manifest/01-container-mount-ns-and-kubelet-conf-master.yaml
  ztp/source-crs/extra-manifest/01-container-mount-ns-and-kubelet-conf-worker.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#861 ztp: comment the getCluserCR unit test for not blocking other commits
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
Labels: approved, lgtm

#829 ztp: Added support for defining OCP release per cluster
  ztp/ran-crd/site-config-crd.yaml
  ztp/siteconfig-generator/siteConfig/clusterCRs.go
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
Labels: approved, lgtm, needs-ok-to-test

#844 ztp: BZ-2029181 Add reference of DisableSnoNetworkDiag.yaml to group-du-sno PolicyGenTemplate
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
Labels: approved, lgtm

#864 ztp: re-enable getClusterCR unitTest
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
Labels: approved, lgtm

#858 ztp: Add an initial example of a DU profile
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
Labels: approved, lgtm

#868 ztp: Fix policygenerator and siteconfig Makefiles
  ztp/policygenerator/Makefile
  ztp/siteconfig-generator/Makefile
Labels: approved, lgtm

#869 ztp: Set entire 3node group profile for 'master' and not 'worker'
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
Labels: approved, lgtm

#839 ztp: Update Readme and examples
  ztp/.gitignore
  ztp/gitops-subscriptions/argocd/README.md
  ztp/policygenerator-kustomize-plugin/README.md
  ztp/policygenerator/README.md
Labels: approved, lgtm

#629 cnf-tests: gatekeeper constraint validation test
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/gatekeeper/gatekeeper.go
  cnf-tests/testsuites/e2esuite/junit.xml/cnftests-junit.xml
  cnf-tests/testsuites/pkg/client/clients.go
  cnf-tests/testsuites/pkg/utils/consts.go
  cnf-tests/testsuites/pkg/utils/reporter.go
  go.mod
  go.sum
  vendor/github.com/open-policy-agent/gatekeeper/pkg/mutation/match/match.go
  vendor/modules.txt
Labels: approved, lgtm

#862 ztp: Add ztp-deploy-wave annotation in source CR
  ztp/Makefile
  ztp/source-crs/AcceleratorsNS.yaml
  ztp/source-crs/AcceleratorsOperGroup.yaml
  ztp/source-crs/AcceleratorsSubscription.yaml
  ztp/source-crs/AmqInstance.yaml
  ztp/source-crs/AmqSubscription.yaml
  ztp/source-crs/AmqSubscriptionNS.yaml
  ztp/source-crs/AmqSubscriptionOperGroup.yaml
  ztp/source-crs/ClusterLogCatSource.yaml
  ztp/source-crs/ClusterLogForwarder.yaml
  ztp/source-crs/ClusterLogNS.yaml
  ztp/source-crs/ClusterLogOperGroup.yaml
  ztp/source-crs/ClusterLogSubscription.yaml
  ztp/source-crs/ClusterLogging.yaml
  ztp/source-crs/ConsoleOperatorDisable.yaml
  ztp/source-crs/DefaultCatsrc.yaml
  ztp/source-crs/DisableSnoNetworkDiag.yaml
  ztp/source-crs/DisconnectedICSP.yaml
  ztp/source-crs/OperatorHub.yaml
  ztp/source-crs/PaoSubscription.yaml
  ztp/source-crs/PaoSubscriptionCatalogSource.yaml
  ztp/source-crs/PaoSubscriptionNS.yaml
  ztp/source-crs/PaoSubscriptionOperGroup.yaml
  ztp/source-crs/PerformanceProfile.yaml
  ztp/source-crs/PtpCatSource.yaml
  ztp/source-crs/PtpConfigMaster.yaml
  ztp/source-crs/PtpConfigSlave.yaml
  ztp/source-crs/PtpConfigSlaveCvl.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
  ztp/source-crs/PtpSubscription.yaml
  ztp/source-crs/PtpSubscriptionNS.yaml
  ztp/source-crs/PtpSubscriptionOperGroup.yaml
  ztp/source-crs/ReduceMonitoringFootprint.yaml
  ztp/source-crs/SriovCatSource.yaml
  ztp/source-crs/SriovNetwork.yaml
  ztp/source-crs/SriovNetworkNodePolicy.yaml
  ztp/source-crs/SriovOperatorConfig.yaml
  ztp/source-crs/SriovSubscription.yaml
  ztp/source-crs/SriovSubscriptionNS.yaml
  ztp/source-crs/SriovSubscriptionOperGroup.yaml
  ztp/source-crs/StorageCatSource.yaml
  ztp/source-crs/StorageLV.yaml
  ztp/source-crs/StorageNS.yaml
  ztp/source-crs/StorageOperGroup.yaml
  ztp/source-crs/StorageSubscription.yaml
  ztp/source-crs/TunedPerformancePatch.yaml
Labels: approved, lgtm

#853 ztp: Clean up StorageLV source-crs and SNO example
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/source-crs/StorageLV.yaml
Labels: approved, lgtm

#870 ztp: Add upgrade.md
  ztp/gitops-subscriptions/argocd/Upgrade.md
Labels: approved, lgtm

#836 ztp: CNF-3661 Reduce number of policies
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
Labels: approved, lgtm

#873 cnf-tests: add tap device tests
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  go.mod
  go.sum
  vendor/github.com/cespare/xxhash/v2/.travis.yml
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodepolicy_types.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/zz_generated.deepcopy.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
  vendor/modules.txt
Labels: approved, lgtm

#863 ztp: Add ztp-deploy-wave annotation in generated policy
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilderOverlay_test.go
  ztp/policygenerator/policyGen/policyBuilder_test.go
  ztp/policygenerator/policyGen/policyHelper.go
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericCR.yaml
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericConfig.yaml
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericConfigWithoutWave.yaml
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericNamespace.yaml
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericOperatorGroup.yaml
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericSubscription.yaml
  ztp/policygenerator/utils/utils.go
Labels: approved, lgtm

#800 ztp: Add platform update source CR for upgrades operator interoperability
  ztp/source-crs/ClusterVersion.yaml
Labels: approved, lgtm

#881 [Release 4.7] bump CI image version
  go.mod
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#878 Bug 2034974: cnf-tests: Update gatekeeper config definition
  feature-configs/deploy/gatekeeper/config.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#882 [Release 4.7] Bump to use go mod in the openshift CI image build
  hack/build-test-bin.sh
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#883 bug 2035318: added upstream field in the clusterVerion CR
  ztp/source-crs/ClusterVersion.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#877 cnf-tests: add tap device tests
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodepolicy_types.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/zz_generated.deepcopy.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/modules.txt
Labels: approved, lgtm

#876 Bug 2034300: ztp: Fix the name issue in validator source cr
  ztp/source-crs/validatorCRs/informDuValidator.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#879 Bug 2033440: cnf-tests: Update gatekeeper config definition
  feature-configs/deploy/gatekeeper/config.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#885 [release 4.7] install golint as part of the ci image
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#886 [release-4.7] install ginkgo as part of the openshift-ci dockerfile
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#880 Bug 2003446: [release 4.7] bump ptp-operator
  go.mod
  go.sum
  hack/build-test-bin.sh
  hack/lint.sh
  vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#890 cnf-tests: use go install instead of go get for golint package
  cnf-tests/hack/build-test-bin.sh
  cnf-tests/hack/lint.sh
Labels: approved, lgtm

#887 [release 4.7] remove the mod from the go install commands
  hack/build-test-bin.sh
  hack/lint.sh
Labels: approved, lgtm

#888 [release 4.8] use go install for golint package like ginkgo
  cnf-tests/hack/build-test-bin.sh
  cnf-tests/hack/lint.sh
Labels: approved, lgtm

#889 [release 4.9] cnf-tests: use go install instead of go get for golint
  cnf-tests/hack/build-test-bin.sh
  cnf-tests/hack/lint.sh
Labels: approved, lgtm
