Repository openshift-kni/cnf-features-deploy, pull requests merged in 2021-09, with the labels that each got.

#674 bug 1999862: ztp: Ensure the tuned performance-patch matches the PAO policy name
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/test-sno.yaml
  ztp/source-crs/TunedPerformancePatch.yaml
  ztp/ztp-policy-generator/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#675 Add README for resource-generator
  ztp/gitops-subscriptions/README.md
  ztp/gitops-subscriptions/argocd/README.md
  ztp/resource-generator/README.md
Labels: approved, lgtm

#677 ztp: update build_requirements.txt for cachito build
  ztp/resource-generator/tools/cachito/build_requirements.in
  ztp/resource-generator/tools/cachito/build_requirements.txt
  ztp/resource-generator/tools/cachito/requirements.txt
Labels: approved, lgtm

#673 ztp: tests update for policyGenerator after day2 changes
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/UNITTESTS.md
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyBuilder.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGenerator.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGenerator_test.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder_test.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestMachineConfigPool/sourcePolicies/TestMachineConfigPool.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestMachineConfigPool/templates/TestMachineConfigPool.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestNamespace/sourcePolicies/TestNamespace.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestNamespace/templates/TestNamespace.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestOperatorGroup/sourcePolicies/TestOperatorGroup.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestOperatorGroup/templates/TestOperatorGroup.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestPtpConfig/templates/TestPtpConfig.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestSriovNetwork/sourcePolicies/TestSriovNetwork.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestSriovNetwork/templates/TestSriovNetwork.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestSubscription/sourcePolicies/TestSubscription.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestSubscription/templates/TestSubscription.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestOperatorGroup/templates/TestOperatorGroup.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestPtpConfig/templates/TestPtpConfig.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestSriovNetwork/templates/TestSriovNetwork.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testSource/TestAssertions.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testSource/TestConstants.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testSource/TestGetters.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testSource/TestHelpers.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/utils/filesHandler.go
Labels: approved, lgtm

#666 ztp: reduce sno monitoring footprint
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/common-ranGen.yaml
  ztp/source-crs/ReduceMonitoringFootprint.yaml
  ztp/ztp-policy-generator/testPolicyGenTemplate/common-ranGen.yaml
Labels: approved, lgtm

#680 vendor: Update vendor PAO dependencies
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/api/v2/performanceprofile_validation.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/netqueues.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/modules.txt
Labels: approved, lgtm

#682 cnf-tests: bump images to 4.9
  cnf-tests/testsuites/pkg/images/images.go
Labels: approved, lgtm

#685 Add bmh role annotation
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/resources/cluster-crs.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfig.go
Labels: approved, lgtm

#683 ztp: Update kernel args for performance
  ztp/source-crs/PerformanceProfile.yaml
Labels: approved, lgtm

#687 ztp: Add SNO accelerated startup services
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/source-crs/MachineConfigAcceleratedStartup.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup.yaml
  ztp/ztp-policy-generator/testPolicyGenTemplate/group-du-ranGen.yaml
  ztp/ztp-policy-generator/testPolicyGenTemplate/group-du-sno-ranGen.yaml
Labels: approved, lgtm

#688 Nummasters
  ztp/ran-crd/site-config-crd.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/resources/cluster-crs.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfig.go
Labels: approved, lgtm

#686 ztp: add standard cluster deployment
  ztp/ran-crd/site-config-crd.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/resources/cluster-crs.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder.go
  ztp/ztp-policy-generator/testSiteConfig/site2-standard-du.yaml
Labels: approved, lgtm

#681 Bug 2000726: ztp: fix rv data name and path
  ztp/resource-generator/src/get-pre-sync-rv.sh
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#690 ztp: Fix raw CR generation for multi-entry sources
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyBuilder.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGenerator.go
Labels: approved, lgtm

#614 cnf-tests: Add metallb feature configs
  Makefile
  cnf-tests/README.md
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/docgen/validation.json
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/validationsuite/test_suite_test.go
  feature-configs/deploy/metallb/kustomization.yaml
  feature-configs/deploy/metallb/operator_catalogsource.yaml
  feature-configs/deploy/metallb/operator_namespace.yaml
  feature-configs/deploy/metallb/operator_operatorgroup.yaml
  feature-configs/deploy/metallb/operator_subscription.yaml
  go.mod
  go.sum
  hack/run-functests.sh
  vendor/github.com/metallb/metallb-operator/LICENSE
  vendor/github.com/metallb/metallb-operator/api/v1alpha1/addresspool_types.go
  vendor/github.com/metallb/metallb-operator/api/v1alpha1/groupversion_info.go
  vendor/github.com/metallb/metallb-operator/api/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/metallb/metallb-operator/api/v1beta1/groupversion_info.go
  vendor/github.com/metallb/metallb-operator/api/v1beta1/metallb_types.go
  vendor/github.com/metallb/metallb-operator/api/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/metallb/metallb-operator/pkg/platform/platform.go
  vendor/github.com/metallb/metallb-operator/pkg/platform/types.go
  vendor/github.com/metallb/metallb-operator/pkg/status/status.go
  vendor/github.com/metallb/metallb-operator/test/consts/const.go
  vendor/github.com/metallb/metallb-operator/test/e2e/client/client.go
  vendor/github.com/metallb/metallb-operator/test/e2e/functional/tests/e2e.go
  vendor/github.com/metallb/metallb-operator/test/e2e/metallb/metallb.go
  vendor/github.com/metallb/metallb-operator/test/e2e/validation/tests/validation.go
  vendor/github.com/mitchellh/copystructure/copystructure.go
  vendor/github.com/mitchellh/copystructure/go.mod
  vendor/github.com/mitchellh/copystructure/go.sum
  vendor/github.com/mitchellh/reflectwalk/reflectwalk.go
  vendor/modules.txt
Labels: approved, lgtm

#693 ztp: disable SNO network diagnostics
  ztp/source-crs/DisableSnoNetworkDiag.yaml
  ztp/ztp-policy-generator/testPolicyGenTemplate/group-du-sno-ranGen.yaml
Labels: approved, lgtm

#694 ztp: Fix mc-accelerated-startup-policy-worker-du policy name more than 63 chars
  ztp/ztp-policy-generator/testPolicyGenTemplate/group-du-ranGen.yaml
  ztp/ztp-policy-generator/testPolicyGenTemplate/group-du-sno-ranGen.yaml
Labels: approved, lgtm

#697 infra: add make print-features
  Makefile
Labels: approved, lgtm

#695 ztp: fix sample for standard cluster
  ztp/ztp-policy-generator/testSiteConfig/site1-sno-du.yaml
  ztp/ztp-policy-generator/testSiteConfig/site2-sno-du.yaml
  ztp/ztp-policy-generator/testSiteConfig/site2-standard-du.yaml
Labels: approved, lgtm

#700 ztp/make ci job
  Makefile
  ztp/Makefile
Labels: approved, lgtm

#702 ztp/add gotest
  ztp/Makefile
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/utils/utils.go
Labels: approved, lgtm

#704 infra: fix our invocation of 'go vet' to run everywhere
  Makefile
Labels: approved, lgtm

#705 ztp: Increase the gitOps controller pod memory
  ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops.yaml
  ztp/gitops-subscriptions/argocd/deployment/kustomization.yaml
Labels: approved, lgtm

#710 Bug 2002357: Backport test changes after Day2 updates and downstream build python dependencies for cachito
  ztp/resource-generator/tools/cachito/build_requirements.in
  ztp/resource-generator/tools/cachito/build_requirements.txt
  ztp/resource-generator/tools/cachito/requirements.in
  ztp/resource-generator/tools/cachito/requirements.txt
  ztp/resource-generator/tools/cachito/setup.cfg
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/UNITTESTS.md
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyBuilder.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGenerator.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGenerator_test.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestMachineConfigPool/sourcePolicies/TestMachineConfigPool.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestMachineConfigPool/templates/TestMachineConfigPool.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestNamespace/sourcePolicies/TestNamespace.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestNamespace/templates/TestNamespace.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestOperatorGroup/sourcePolicies/TestOperatorGroup.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestOperatorGroup/templates/TestOperatorGroup.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestPtpConfig/templates/TestPtpConfig.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestSriovNetwork/sourcePolicies/TestSriovNetwork.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestSriovNetwork/templates/TestSriovNetwork.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestSubscription/sourcePolicies/TestSubscription.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testData/TestSubscription/templates/TestSubscription.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestOperatorGroup/templates/TestOperatorGroup.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestPtpConfig/templates/TestPtpConfig.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestSriovNetwork/templates/TestSriovNetwork.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testSource/TestAssertions.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testSource/TestConstants.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testSource/TestGetters.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testSource/TestHelpers.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/utils/filesHandler.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#699 ztp: Detect steady-state for accelerated startup
  ztp/source-crs/MachineConfigAcceleratedStartup.yaml
Labels: approved, lgtm

#715 ztp: Reduce kubelet CPU usage
  feature-configs/deploy/container-mount-namespace/container-private-mounts/mc-container-mount-namespace.yaml
  ztp/source-crs/MachineConfigContainerMountNS.yaml
  ztp/source-crs/extra-manifest/01-container-mount-ns-and-kubelet-conf.yaml
  ztp/source-crs/extra-manifest/01-container-mount-ns.yaml
Labels: approved, lgtm

#696 ztp: support networkType parametrization
  ztp/ran-crd/site-config-crd.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/resources/cluster-crs.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfig.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder.go
Labels: approved, lgtm, ok-to-test

#720 ztp: fixes issue when adding more clusters to a siteconfig
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/resources/cluster-crs.yaml
Labels: approved, lgtm, needs-ok-to-test

#719 ztp: Added support for defining proxy settings
  ztp/ran-crd/site-config-crd.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/resources/cluster-crs.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfig.go
Labels: approved, lgtm, needs-ok-to-test

#722 Bug 2004510: ztp: Add authentication retries to ztp container
  ztp/resource-generator/src/common.sh
  ztp/resource-generator/src/get-pre-sync-rv.sh
  ztp/resource-generator/src/post-sync-entrypoint.sh
  ztp/resource-generator/src/pre-sync-entrypoint.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
