Repository openshift-kni/cnf-features-deploy, pull requests merged in 2021-11, with the labels that each got.

#765 ztp: Add sriov-fec operator installation manifests
  ztp/source-crs/AcceleratorsNS.yaml
  ztp/source-crs/AcceleratorsOperGroup.yaml
  ztp/source-crs/AcceleratorsSubscription.yaml
Labels: approved, lgtm

#750 ztp: add conditional chronyd on day-0
  ztp/source-crs-builder/MachineConfigChronyDynamicMaster/20-conditional-start.conf
  ztp/source-crs-builder/MachineConfigChronyDynamicMaster/README.md
  ztp/source-crs-builder/MachineConfigChronyDynamicMaster/build.sh
  ztp/source-crs-builder/MachineConfigChronyDynamicMaster/chronyd-restart.service
  ztp/source-crs-builder/MachineConfigChronyDynamicMaster/chronyd-restart.timer
  ztp/source-crs-builder/MachineConfigChronyDynamicMaster/ptp-sync-check
  ztp/source-crs-builder/MachineConfigChronyDynamicMaster/restart-chronyd
  ztp/source-crs-builder/MachineConfigChronyDynamicMaster/test.sh
  ztp/source-crs/MachineConfigChronyDynamicMaster.yaml
  ztp/source-crs/extra-manifest/05-chrony-dynamic.yaml
Labels: approved, lgtm

#755 features: Add create a demo local-bfd deployment
  feature-configs/demo/local_bfd/01_configmap_workers.yaml
  feature-configs/demo/local_bfd/02_configmap_master.yaml
  feature-configs/demo/local_bfd/03_daemonset.yaml
  feature-configs/demo/local_bfd/04_deployment.yaml
  feature-configs/demo/local_bfd/kustomization.yaml
Labels: approved, lgtm, ok-to-test

#763 cnf-tests: update image version in images.json
  cnf-tests/mirror/images.json
Labels: approved, lgtm, needs-ok-to-test

#769 ztp: add default catsrc to source crs
  ztp/source-crs/DefaultCatsrc.yaml
Labels: approved, lgtm

#773 Bug 2017547: ztp: Support SiteConfig default values
  ztp/policygenerator/siteConfig/siteConfig.go
  ztp/policygenerator/siteConfig/siteConfigBuilder.go
  ztp/policygenerator/siteConfig/siteConfig_test.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#770 ztp: remove machineconfig disabling chronyd
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/source-crs/MachineConfigDisableChronyd.yaml
Labels: approved, lgtm

#783 ztp: Create a fixed ACM inform policy
  ztp/policygenerator/resources/acm-policy-du-platform-check-template.yaml
Labels: approved, lgtm

#771 Fix CI system
  feature-configs/ci/ptp/kustomization.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/kustomization.yaml
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#727 Bug 2009660:cnf-tests:add mlockall arg to cyclictest runner
  cnf-tests/pod-utils/cyclictest-runner/main.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#740 Bug 2009770:cnf-tests:run cyclictest using priority 95
  cnf-tests/pod-utils/cyclictest-runner/main.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#732 Bug 2006675:cnf-tests: cyclictest and hwlat recieve start delay arg as an integer
  cnf-tests/pod-utils/cyclictest-runner/main.go
  cnf-tests/pod-utils/hwlatdetect-runner/main.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#777 cnf-tests: Add default namespace to reporter
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/utils/reporter.go
Labels: approved, lgtm

#782 Fix the source CR PaoSubscriptionNS
  ztp/source-crs/PaoSubscriptionNS.yaml
Labels: approved, lgtm

#776 ztp: CNF-3071 Reduce Prometheus retention period
  ztp/source-crs/ReduceMonitoringFootprint.yaml
Labels: approved, lgtm

#789 cnf-tests: [release-4.9] bump image mirror tags
  cnf-tests/mirror/images.json
Labels: approved, lgtm

#794 ztp:Add Ptp operator config to enable fast event
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm

#799 ztp: Fix typo in source-crs-builder README
  ztp/source-crs-builder/README.md
Labels: approved, lgtm

#797 features: Fix gatekeeper deployment
  feature-configs/deploy/gatekeeper/config.yaml
Labels: approved, lgtm

#790 cnf-tests: bump image mirror to 4.10
  cnf-tests/mirror/images.json
Labels: approved, lgtm

#807 [release-4.8] disable gatekeeper tests
  Makefile
Labels: approved, lgtm

#757 mcmaker versionbump
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
  vendor/github.com/lack/mcmaker/pkg/mcmaker.go
  vendor/modules.txt
Labels: approved, lgtm

#808 ztp: add missing type for new boolean attribute 'wrapInPolicy'
  ztp/ran-crd/policy-gen-template-crd.yaml
Labels: approved, lgtm

#804 Bug 2009233: ztp: Support complianceType override for CRs
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/common-ranGen.yaml
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilder_test.go
  ztp/policygenerator/policyGen/policyHelper.go
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericNamespace.yaml
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericOperatorGroup.yaml
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericSubscription.yaml
  ztp/policygenerator/utils/filesHandler.go
  ztp/policygenerator/utils/utils.go
  ztp/ran-crd/policy-gen-template-crd.yaml
Labels: approved, lgtm, bugzilla/severity-unspecified, bugzilla/valid-bug

#796 [release-4.8] vendor: Update PAO dependencies
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/netqueues.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/nodes/nodes.go
  vendor/modules.txt
Labels: approved, lgtm

#810 oot-driver: update Dockerfiles for oot-drivers
  tools/oot-driver/charts/dpdk-kni-driver-0.0.1/Dockerfile-driver.SRO
  tools/oot-driver/charts/iavf-driver-0.0.1/Dockerfile-driver.SRO
  tools/oot-driver/charts/ice-driver-0.0.1/Dockerfile-driver.SRO
Labels: approved, lgtm

#802 Bug 2019181: ztp: Update PAO subscription catalog source
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/common-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-ranGen.yaml
  ztp/ran-crd/policy-gen-template-ex.yaml
  ztp/source-crs/PaoSubscription.yaml
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium

#812 ztp: Remove extra CR separator from StorageLV
  ztp/source-crs/StorageLV.yaml
Labels: approved, lgtm

#811 ztp: Add example configs for standard and 3-node clusters
  ztp/gitops-subscriptions/argocd/resource-hook-example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/resource-hook-example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/resource-hook-example/siteconfig/example-standard.yaml
  ztp/gitops-subscriptions/argocd/resource-hook-example/siteconfig/kustomization.yaml
  ztp/gitops-subscriptions/argocd/resource-hook-example/siteconfig/test-sno.yaml
Labels: approved, lgtm

#816 ztp: added logic to override remediationAction from PGT
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilder_test.go
  ztp/policygenerator/testData/TestMachineConfigPool/templates/TestMachineConfigPool.yaml
  ztp/policygenerator/utils/utils.go
  ztp/ran-crd/policy-gen-template-crd.yaml
Labels: approved, lgtm

#819 cnf-tests: Improve ovs_qos debuggability
  cnf-tests/testsuites/e2esuite/ovs_qos/ovs_qos.go
Labels: approved, lgtm

#821 cnf-tests: bump the images for cnf-test to 4.10
  cnf-tests/testsuites/pkg/images/images.go
Labels: approved, lgtm

#815 Bug 2009233: ztp: Support complianceType for full PGT
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/common-ranGen.yaml
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilder_test.go
  ztp/policygenerator/policyGen/policyHelper.go
  ztp/policygenerator/policyGenerator.go
  ztp/policygenerator/utils/utils.go
  ztp/ran-crd/policy-gen-template-crd.yaml
  ztp/source-crs/ClusterLogNS.yaml
  ztp/source-crs/ClusterLogOperGroup.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#805 ztp: Update PolicyGen to create static inform policy
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/common-ranGen.yaml
  ztp/policygenerator/resources/acm-policy-du-platform-check-template.yaml
  ztp/source-crs/validatorCRs/informDuValidator.yaml
Labels: approved, lgtm

#813 ztp: Use common CatalogSource for all subscriptions
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/source-crs/PtpSubscription.yaml
Labels: approved, lgtm

#806 ztp: Cleanup multinode siteconfig schema
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
  ztp/ran-crd/site-config-cr-ex.yaml
  ztp/ran-crd/site-config-crd.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-sno-du.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-standard-du.yaml
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfig_test.go
Labels: approved, lgtm
