Repository openshift-kni/cnf-features-deploy, pull requests merged in 2021-08, with the labels that each got.

#633 gofmt fixes
  Makefile
  cnf-tests/pod-utils/cyclictest-runner/main.go
  cnf-tests/pod-utils/hwlatdetect-runner/main.go
  cnf-tests/testsuites/e2esuite/sctp/sctp.go
  hack/gofmt.sh
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyBuilder.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyHelper.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGenerator.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfig.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/utils/filesHandler.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/utils/utils.go
Labels: approved, lgtm

#626 vendor: update pao dependencies
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/hugepages.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/nodes/nodes.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/pods/pods.go
  vendor/modules.txt
Labels: approved, lgtm

#647 Fix bug in cluster validation findMachineConfigPool function
  validationsuite/cluster/validation.go
Labels: approved, lgtm

#650 features: bump operators to 4.8
  feature-configs/deploy/ptp/03_subscription.yaml
  feature-configs/deploy/sriov/03-sriov-subscription.yaml
Labels: approved, lgtm

#640 ztp: Add extra manifest sctp and Tuned performance patch kernel
  ztp/source-cluster-crs/extra-manifest/01-container-mount-ns.yaml
  ztp/source-cluster-crs/extra-manifest/02-operators-groups.yaml
  ztp/source-cluster-crs/extra-manifest/03-sctp-machine-config.yaml
  ztp/source-cluster-crs/mount-ns/01-container-mount-ns.yaml
  ztp/source-policy-crs/TunedPerformancePatch.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfig.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/utils/filesHandler.go
  ztp/ztp-policy-generator/ranPolicyGenTempExamples/site-du-sno-1-ranGen.yaml
Labels: approved, lgtm

#644 Bug 1986410: Control CPUs amount under latency-test pod
  cnf-tests/README.md
  cnf-tests/docgen/e2e.json
  cnf-tests/pod-utils/cyclictest-runner/main.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#642 ztp: Split CRs for policyGen
  ztp/source-policy-crs/ClusterLogOperGroup.yaml
  ztp/source-policy-crs/ClusterLogSubscription.yaml
  ztp/ztp-policy-generator/ranPolicyGenTempExamples/common-ranGen.yaml
Labels: approved, lgtm

#639 NDBE and ZTP integration
  ztp/ran-site-plan-crd/site-config-cr-ex.yaml
  ztp/ran-site-plan-crd/site-config-crd.yaml
  ztp/source-cluster-crs/extra-manifest/disk-encryption.yaml.tmpl
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/go.mod
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/go.sum
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfig.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder_test.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/testdata/empty.yaml.tmpl
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/testdata/execution_failure.yaml.tmpl
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/testdata/good.yaml.tmpl
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/testdata/parse_failure.yaml.tmpl
  ztp/ztp-policy-generator/siteConfigExamples/site1-sno-du.yaml
Labels: approved, lgtm

#652 ztp: remove soft links to deployment
  ztp/source-policy-crs/MachineConfigContainerMountNS.yaml
  ztp/source-policy-crs/MachineConfigSctp.yaml
  ztp/source-policy-crs/PaoSubscription.yaml
  ztp/source-policy-crs/PaoSubscriptionCatalogSource.yaml
  ztp/source-policy-crs/PaoSubscriptionNS.yaml
  ztp/source-policy-crs/PaoSubscriptionOperGroup.yaml
  ztp/source-policy-crs/PtpSubscription.yaml
  ztp/source-policy-crs/PtpSubscriptionNS.yaml
  ztp/source-policy-crs/PtpSubscriptionOperGroup.yaml
  ztp/source-policy-crs/SriovSubscription.yaml
  ztp/source-policy-crs/SriovSubscriptionNS.yaml
  ztp/source-policy-crs/SriovSubscriptionOperGroup.yaml
Labels: approved, lgtm

#654 Add ztp local gitignore
  ztp/.gitignore
Labels: approved, lgtm

#593 ztp: added new tests for policyGenerator
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/UNITTESTS.md
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/go.mod
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGenerator.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGenerator_test.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestMachineConfigPool/sourcePolicies/TestMachineConfigPool.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestMachineConfigPool/templates/TestMachineConfigPool.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestNamespace/sourcePolicies/TestNamespace.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestNamespace/templates/TestNamespace.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestOperatorGroup/sourcePolicies/TestOperatorGroup.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestOperatorGroup/templates/TestOperatorGroup.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestPtpConfig/templates/TestPtpConfig.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestSriovNetwork/sourcePolicies/TestSriovNetwork.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestSriovNetwork/templates/TestSriovNetwork.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestSubscription/sourcePolicies/TestSubscription.yaml
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/testFiles/TestSubscription/templates/TestSubscription.yaml
Labels: approved, lgtm, needs-ok-to-test

#634 ztp: add Argo CD resource hook container image
  ztp/gitops-subscriptions/argocd/app-project.yaml
  ztp/gitops-subscriptions/argocd/deployment/app-project.yaml
  ztp/gitops-subscriptions/argocd/deployment/clusters-app.yaml
  ztp/gitops-subscriptions/argocd/deployment/common-app.yaml
  ztp/gitops-subscriptions/argocd/deployment/gitops-cluster-rolebinding.yaml
  ztp/gitops-subscriptions/argocd/deployment/groups-app.yaml
  ztp/gitops-subscriptions/argocd/deployment/kustomization.yaml
  ztp/gitops-subscriptions/argocd/deployment/resource-hook-cluster-role.yaml
  ztp/gitops-subscriptions/argocd/deployment/resource-hook-role-binding.yaml
  ztp/gitops-subscriptions/argocd/deployment/sites-app.yaml
  ztp/gitops-subscriptions/argocd/resource-hook-example/kustomization.yaml
  ztp/gitops-subscriptions/argocd/resource-hook-example/post-sync.yaml
  ztp/gitops-subscriptions/argocd/resource-hook-example/pre-sync.yaml
  ztp/gitops-subscriptions/argocd/resource-hook-example/test-sno.yaml
  ztp/ran-site-plan-crd/kustomization.yaml
  ztp/resource-generator/Containerfile
  ztp/resource-generator/Makefile
  ztp/resource-generator/assets/flow.png
  ztp/resource-generator/src/common.sh
  ztp/resource-generator/src/get-pre-sync-rv.sh
  ztp/resource-generator/src/pol_gen.yaml.j2
  ztp/resource-generator/src/post-sync-entrypoint.sh
  ztp/resource-generator/src/pre-sync-entrypoint.sh
  ztp/resource-generator/src/watcher.py
Labels: approved, lgtm

#659 ztp: refactor argocd container image
  ztp/resource-generator/Containerfile
  ztp/resource-generator/Containerfile.base
  ztp/resource-generator/Makefile
  ztp/resource-generator/src/pol_gen.yaml.j2
  ztp/resource-generator/src/post-sync-entrypoint.sh
  ztp/resource-generator/src/watcher.py
Labels: approved, lgtm

#655 Update PAO dependencies
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/netqueues.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/nodes/nodes.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/pods/pods.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/profiles/profiles.go
  vendor/modules.txt
Labels: approved, lgtm

#671 [release-4.8] switch the ptp and sriov operators to 4.8
  feature-configs/deploy/ptp/03_subscription.yaml
  feature-configs/deploy/sriov/03-sriov-subscription.yaml
Labels: approved, lgtm

#672 ztp: add requirements.txt for python dependencies of the downstream container build
  ztp/resource-generator/tools/cachito/build_requirements.txt
  ztp/resource-generator/tools/cachito/requirements.in
  ztp/resource-generator/tools/cachito/requirements.txt
  ztp/resource-generator/tools/cachito/setup.cfg
Labels: approved, lgtm

#670 [release-4.8] cnf-tests: bump PAO vendor
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/client/clients.go
  vendor/modules.txt
Labels: approved, lgtm

#615 cnf-tests: Use the supported-nic-ids ConfigMap for the test table
  Makefile
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/pkg/utils/consts.go
Labels: approved, lgtm
