Repository openshift-kni/cnf-features-deploy, pull requests merged in 2021-07, with the labels that each got.

#590 infra: remove gatekeeper from default FEATURES
  Makefile
Labels: approved, lgtm

#540 a fancy verify commits makefile target
  .githooks/commit-msg
  .githooks/components.sh
  Makefile
  hack/print-git-components.sh
  hack/verify-commits.sh
Labels: approved, lgtm

#595 infra: remove ovs_qos from default FEATURES
  Makefile
Labels: approved, lgtm

#594 Bug 1979554: Update the oslat version to 2.0
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  cnf-tests/pod-utils/oslat-runner/main.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#588 [release-4.7] Fix the s2i example
  feature-configs/deploy/dpdk/build-config.yaml
  tools/s2i-dpdk/Dockerfile
  tools/s2i-dpdk/test/test-app/build.sh
  tools/s2i-dpdk/test/test-app/test-pmd/5tswap.c
  tools/s2i-dpdk/test/test-app/test-pmd/Makefile
  tools/s2i-dpdk/test/test-app/test-pmd/bpf_cmd.c
  tools/s2i-dpdk/test/test-app/test-pmd/bpf_cmd.h
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_flow.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_mtr.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_tm.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_tm.h
  tools/s2i-dpdk/test/test-app/test-pmd/config.c
  tools/s2i-dpdk/test/test-app/test-pmd/csumonly.c
  tools/s2i-dpdk/test/test-app/test-pmd/flowgen.c
  tools/s2i-dpdk/test/test-app/test-pmd/icmpecho.c
  tools/s2i-dpdk/test/test-app/test-pmd/iofwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/macfwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/macswap.c
  tools/s2i-dpdk/test/test-app/test-pmd/meson.build
  tools/s2i-dpdk/test/test-app/test-pmd/noisy_vnf.c
  tools/s2i-dpdk/test/test-app/test-pmd/parameters.c
  tools/s2i-dpdk/test/test-app/test-pmd/rxonly.c
  tools/s2i-dpdk/test/test-app/test-pmd/softnicfwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/testpmd.c
  tools/s2i-dpdk/test/test-app/test-pmd/testpmd.h
  tools/s2i-dpdk/test/test-app/test-pmd/txonly.c
  tools/s2i-dpdk/test/test-app/test-pmd/util.c
Labels: approved, lgtm

#586 [release-4.8] Add a ref field to the dpdk build config
  feature-configs/deploy/dpdk/build-config.yaml
Labels: approved, lgtm

#587 [release-4.6] Add a ref field to the dpdk build config
  feature-configs/deploy/dpdk/build-config.yaml
Labels: approved, lgtm

#583 Fixing README typos
  cnf-tests/README.md
Labels: approved, lgtm, ok-to-test

#591 Update openshift-ci base image to fedora 34
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#599 Update PerformanceProfile kernel args
  ztp/source-policy-crs/PerformanceProfile.yaml
Labels: approved, lgtm

#603 add jq to Dockerfile.tools
  .githooks/components.sh
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#582 Support running dpdk tests on secure boot environment
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/sctp/sctp_sriov.go
Labels: approved, lgtm

#479 Add custom RPMs utility
  Makefile
  README.md
  hack/custom_rpms.sh
Labels: approved, lgtm

#602 fix CI commit verifier (hack/verify-commits.sh)
  hack/verify-commits.sh
Labels: approved, lgtm

#613 ztp: remove provisioning from ClusterDeployment
  ztp/source-cluster-crs/cluster-crs.yaml
Labels: approved, lgtm

#618 infra: allow verify-commit to success if no changes
  hack/verify-commits.sh
Labels: approved, lgtm

#617 operator: move to 4.9
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  feature-configs/deploy/performance/operator_catalogsource.yaml
  feature-configs/deploy/performance/operator_subscription.yaml
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/nodes/nodes.go
  vendor/modules.txt
Labels: approved, lgtm

#621 Ship latency tools
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  cnf-tests/README.md
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/pod-utils/cyclictest-runner/main.go
  cnf-tests/pod-utils/hwlatdetect-runner/main.go
  cnf-tests/pod-utils/oslat-runner/main.go
  cnf-tests/pod-utils/pkg/node/node.go
  hack/run-functests.sh
Labels: approved, lgtm

#616 [release 4.8] Support secure boot in sriov and dpdk tests
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/sctp/sctp_sriov.go
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/client/clients.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/pod/pod.go
  vendor/modules.txt
Labels: approved, lgtm

#608 infra: update the vendor list in the githooks
  .githooks/components.sh
Labels: approved, lgtm

#585 features: Add a ref field to the dpdk build config
  feature-configs/deploy/dpdk/build-config.yaml
Labels: approved, lgtm

#600 features: Bump the custom catalog for intel operator
  feature-configs/deploy/n3000/catalogSource.yaml
Labels: approved, lgtm

#604 cnf-test: Fix dpdk tests in discovery mode
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/pkg/discovery/discovery.go
Labels: approved, lgtm

#623 Update PAO dependency
  .githooks/components.sh
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/api/v2/performanceprofile_types.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/hugepages.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/mcps/mcps.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/pods/pods.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/profiles/profiles.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/profile/profile.go
  vendor/modules.txt
Labels: approved, lgtm

#622 ztp: removing userData temporarily to enable testing for ztp
  ztp/source-cluster-crs/cluster-crs.yaml
Labels: approved, lgtm

#578 Bug 1976243: Add partitioning annotation to PAO CatalogSource.
  feature-configs/deploy/performance/operator_catalogsource.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#627 cnf-tests: Fix the sriov sctp test when secure boot is enable
  cnf-tests/testsuites/e2esuite/sctp/sctp_sriov.go
Labels: approved, lgtm
