Repository openshift-kni/cnf-features-deploy, pull requests merged in 2021-05, with the labels that each got.

#504 Add SNO drain handle to dpdk tests
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/clean/clean.go
  vendor/modules.txt
Labels: approved, lgtm

#494 Update go version to 1.16.3
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
  vendor/modules.txt
Labels: approved, lgtm

#511 improve du performance profile
  feature-configs/5g-ref-nw/profile-base/du-dual/performance/kustomization.yaml
  feature-configs/5g-ref-nw/profile-base/du-dual/performance/performance-profile.yaml
  feature-configs/5g-ref-nw/profile-base/du-general/performance/kustomization.yaml
  feature-configs/5g-ref-nw/profile-base/du-general/performance/performance-profile.yaml
  feature-configs/5g-ref-nw/profile-base/du-single/performance/kustomization.yaml
  feature-configs/5g-ref-nw/profile-base/du-single/performance/performance-profile.yaml
Labels: approved, lgtm

#512 Fix delete missing spec items and add labels
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyBuilder.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/utils/utils.go
  ztp/ztp-policy-generator/policyGenTemplates/policyGenTemplate.yaml
  ztp/ztp-policy-generator/ranPolicyGenTempExamples/group-du-ranGen.yaml
  ztp/ztp-policy-generator/sourcePolicies/MachineConfigPool.yaml
  ztp/ztp-policy-generator/sourcePolicies/SriovNetwork.yaml
Labels: approved, lgtm

#516 Add iperf3 to the Dockerfiles
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
Labels: approved, lgtm

#513 Bug 1956788: VRF SR-IOV integration: use netdevice type for vfs
  cnf-tests/testsuites/e2esuite/vrf/vrf_sriov.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#515 Allow multiple yamls structure in same file for generated policy
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyBuilder.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/policyGen/policyHelper.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/utils/utils.go
  ztp/ztp-policy-generator/ranPolicyGenTempExamples/common-ranGen.yaml
  ztp/ztp-policy-generator/sourcePolicies/ClusterLogSubscription.yaml
  ztp/ztp-policy-generator/sourcePolicies/ClusterLogSubscriptionNS.yaml
  ztp/ztp-policy-generator/sourcePolicies/ClusterLogSubscriptionOperGroup.yaml
Labels: approved, lgtm

#520 add-ztp-readme-again
  ztp/README.md
Labels: approved, lgtm

#517 Change the artifact location
  hack/common.sh
Labels: approved, lgtm

#529 fix dpdk dockerfile rpm dependencies
  tools/s2i-dpdk/Dockerfile
Labels: approved, lgtm

#526 Add missing attributes to performance profile
  ztp/source-policy-crs/PerformanceProfile.yaml
Labels: approved, lgtm

#532 Add disableDrain flag to SRIOV config
  ztp/source-policy-crs/SriovOperatorConfig.yaml
Labels: approved, lgtm

#533 Set DU profile default SRIOV disableDrain false
  ztp/source-policy-crs/SriovOperatorConfig.yaml
  ztp/ztp-policy-generator/ranPolicyGenTempExamples/group-du-sno-ranGen.yaml
Labels: approved, lgtm

#531 Assign more hugepages for dpdk test
  feature-configs/typical-baremetal/performance/performance_profile.patch.yaml
Labels: approved, lgtm

#524 Adding monitor label to the namespace
  feature-configs/deploy/n3000/namespace.yaml
  feature-configs/deploy/sriov-fec/namespace.yaml
Labels: approved, lgtm

#539 Assign more hugepages for dpdk test
  feature-configs/typical-baremetal/performance/performance_profile.patch.yaml
Labels: approved, lgtm

#534 Consume latest ptp-operator / sriovoperator tests
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
  vendor/modules.txt
Labels: approved, lgtm

#541 Validate sriov nodes are targeted by the performance profile
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/pkg/nodes/nodes.go
Labels: approved, lgtm

#482 Add tests for OVS QoS bandwidth limitations
  Makefile
  cnf-tests/README.md
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/ovs_qos/ovs_qos.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/nodes/nodes.go
  cnf-tests/testsuites/pkg/pods/pods.go
  cnf-tests/testsuites/pkg/utils/consts.go
  cnf-tests/testsuites/pkg/utils/reporter.go
Labels: approved, lgtm

#523 Add Downward API test
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm, ok-to-test
