Repository openshift-kni/cnf-features-deploy, pull requests merged in 2021-01, with the labels that each got.

#386 use the same interface for both ptp profiles
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
Labels: approved, lgtm

#406 Bump sriov-network-operator
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/network/network.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#407 Update PAO dependency
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/hugepages.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/rt-kernel.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/pods/pods.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/utils.go
  vendor/modules.txt
Labels: approved, lgtm

#389 Use standalone kustomize tool
  hack/feature-deploy.sh
Labels: approved, lgtm

#410 Update PAO dependency
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/modules.txt
Labels: approved, lgtm

#412 Bump SRIOV and PTP
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/images/images.go
  vendor/github.com/openshift/ptp-operator/test/ptp/ptp.go
  vendor/modules.txt
Labels: approved, lgtm

#409 Update 4.8 dependencies.
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  cnf-tests/images.json
  external-tests/origintests/test.sh
  feature-configs/deploy/performance/operator_catalogsource.yaml
  feature-configs/deploy/performance/operator_subscription.yaml
  feature-configs/deploy/ptp/03_subscription.yaml
  feature-configs/deploy/sriov/03-sriov-subscription.yaml
  functests/utils/images/images.go
  go.mod
  hack/run-functests.sh
Labels: approved, lgtm

#414 Fix bug in cluster validation findMachineConfigPool function
  validationsuite/cluster/validation.go
Labels: approved, lgtm

#415 CNFTests: Update the PAO tests dependencies.
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/0_config/config.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/clean/clean.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/mcps/mcps.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/consts.go
  vendor/modules.txt
Labels: approved, lgtm

#393 added test removed from test suite case
  cnf-tests/docgen/cmd/fill.go
Labels: approved, lgtm, needs-ok-to-test

#395 Fix docgen shuffling order of markdown everytime
  cnf-tests/docgen/cmd/generate.go
Labels: approved, lgtm, ok-to-test

#417 change PerformanceProfiles to v2
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/performance/performance-profile.yaml
  feature-configs/demo/performance/performance_profile.yaml
  feature-configs/integration-base/performance/performance_profile.yaml
  feature-configs/integration-kni1/performance/performance_profile_patch.yaml
  feature-configs/integration-u08/performance/performance_profile_patch.yaml
  feature-configs/integration-vms/performance/performance_profile_patch.yaml
  feature-configs/integration-wl4-d17u01b05/performance/performance_profile_patch.yaml
  feature-configs/typical-baremetal/performance/performance_profile.patch.yaml
Labels: approved, lgtm

#403 Find SCTP MachineConfigPool also via MatchLabels
  functests/sctp/sctp.go
  functests/xt_u32/xt_u32.go
  validationsuite/cluster/validation.go
Labels: approved, lgtm

#397 Added to ci-job comparison of newly generated docs to existing docs
  Makefile
  cnf-tests/TESTLIST.md
  hack/compare-gen-md.sh
Labels: approved, lgtm

#405 Change custom reporter logs layout
  configsuite/test_suite_test.go
  functests/test_suite_test.go
  functests/utils/k8sreporter/example/main.go
  functests/utils/k8sreporter/reporter.go
  functests/utils/namespaces/namespaces.go
  functests/utils/reporter.go
  go.mod
  go.sum
  hack/run-functests.sh
  validationsuite/test_suite_test.go
  vendor/github.com/kennygrant/sanitize/.gitignore
  vendor/github.com/kennygrant/sanitize/.travis.yml
  vendor/github.com/kennygrant/sanitize/LICENSE
  vendor/github.com/kennygrant/sanitize/README.md
  vendor/github.com/kennygrant/sanitize/sanitize.go
  vendor/modules.txt
Labels: approved, lgtm

#375 Make the dpdk / sctp-sriov tests work with single cluster.
  functests/dpdk/dpdk.go
  functests/sctp/sctp_sriov.go
  functests/utils/sriov/sriov.go
  go.sum
Labels: approved, lgtm

#368 Dpdk tests: add a test that runs a pod using netdevice together with dpdk.
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  functests/dpdk/dpdk.go
  functests/utils/pods/pods.go
Labels: approved, lgtm

#420 Add origin-tests
  Makefile
  README.md
  external-tests/origintests/test.sh
  hack/common.sh
  hack/run-functests.sh
  hack/run-origin-tests.sh
Labels: approved, lgtm
