Repository openshift-kni/cnf-features-deploy, pull requests merged in 2021-06, with the labels that each got.

#543 Vendor the latest PAO tests
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/api/v1/performanceprofile_types.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/0_config/config.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/hugepages.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/cluster/cluster.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/mcps/mcps.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/nodes/nodes.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/profiles/profiles.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/utils.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/utils.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/tuned_types.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/zz_generated.deepcopy.go
  vendor/github.com/vincent-petithory/dataurl/dataurl.go
  vendor/modules.txt
Labels: approved, lgtm

#452 gatekeeper operator catalog deployment
  Makefile
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/validation.json
  cnf-tests/testsuites/pkg/utils/consts.go
  cnf-tests/testsuites/validationsuite/cluster/validation.go
  feature-configs/deploy/gatekeeper/config.yaml
  feature-configs/deploy/gatekeeper/kustomization.yaml
  feature-configs/deploy/gatekeeper/operatorGroup.yaml
  feature-configs/deploy/gatekeeper/subscription.yaml
Labels: approved, lgtm, ok-to-test

#544 Add management workload annotations
  feature-configs/deploy/performance/operator-namespace.yaml
  feature-configs/deploy/ptp/01_namespace.yaml
  feature-configs/deploy/sriov/01-sriov-namespace.yaml
  ztp/source-policy-crs/ClusterLogSubscription.yaml
Labels: approved, lgtm

#510 Skip xt_u32 test in sno
  cnf-tests/testsuites/e2esuite/xt_u32/xt_u32.go
Labels: approved, lgtm

#551 Update dpdk version to 20.11
  feature-configs/deploy/dpdk/build-config.yaml
  tools/s2i-dpdk/Dockerfile
Labels: approved, lgtm

#553 Downward API disable Discovery Mode
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm, needs-ok-to-test

#552 Allow to run fec tests on SNO
  cnf-tests/testsuites/e2esuite/fec/fec.go
Labels: approved, lgtm

#547 Increase dpdk suite timeouts for single node test environments
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go
  cnf-tests/testsuites/pkg/sriov/sriov.go
Labels: approved, lgtm

#554 Removed sleep 900 from Downward API
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm, needs-ok-to-test

#549 Add reporting and operator test fixes for gatekeeper
  cnf-tests/testsuites/e2esuite/gatekeeper/gatekeeper.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/pkg/utils/consts.go
  cnf-tests/testsuites/pkg/utils/reporter.go
Labels: approved, lgtm

#560 rename the sriov-fec feature to fec
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/kustomization.yaml
  feature-configs/deploy/fec/kustomization.yaml
  feature-configs/deploy/fec/namespace.yaml
  feature-configs/deploy/fec/operatorgroup.yaml
  feature-configs/deploy/fec/subscription.yaml
Labels: approved, lgtm

#556 Run cnf-test with host network
  hack/run-functests.sh
Labels: approved, lgtm

#561 Bug 1971274: Fix dpdk hugepages test
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#557 default to podman
  hack/common.sh
Labels: approved, lgtm

#566 Add site config CRD
  ztp/ran-site-plan-crd/site-config-cr-ex.yaml
  ztp/ran-site-plan-crd/site-config-crd.yaml
Labels: approved, lgtm

#570 Fix dpdk test on SNO
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm

#568 Update PAO dependencies
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/modules.txt
Labels: approved, lgtm

#558 Print more detailed test output to the console
  hack/run-functests.sh
Labels: approved, lgtm

#567 [release-4.8] Update PAO dependencies
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/modules.txt
Labels: approved, lgtm

#573 Update PAO dependency
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/consts.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/utils.go
  vendor/modules.txt
Labels: approved, lgtm

#555 Add --pacing-timer to iperf3 sender pod
  cnf-tests/testsuites/e2esuite/ovs_qos/ovs_qos.go
Labels: approved, lgtm

#574 [release-4.8] Update PAO dependency
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/consts.go
  vendor/modules.txt
Labels: approved, lgtm

#562 add workaround for bz1929160 as a feature
  feature-configs/deploy/localhost-workaround/kustomization.yaml
  feature-configs/deploy/localhost-workaround/mc-wa-bz1929160-master.yaml
  feature-configs/deploy/localhost-workaround/mc-wa-bz1929160-worker.yaml
Labels: approved, lgtm

#559 add container-mount-namespace to typical-baremetal
  feature-configs/typical-baremetal/container-mount-namespace/kustomization.yaml
Labels: approved, lgtm

#576 Bump sriov and ptp operator using release 4.9 branch
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/client/clients.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/pod/pod.go
  vendor/modules.txt
Labels: approved, lgtm

#579 Fix the s2i example
  tools/s2i-dpdk/Dockerfile
  tools/s2i-dpdk/test/test-app/build.sh
  tools/s2i-dpdk/test/test-app/test-pmd/5tswap.c
  tools/s2i-dpdk/test/test-app/test-pmd/Makefile
  tools/s2i-dpdk/test/test-app/test-pmd/bpf_cmd.c
  tools/s2i-dpdk/test/test-app/test-pmd/bpf_cmd.h
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_flow.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_mtr.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_tm.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_tm.h
  tools/s2i-dpdk/test/test-app/test-pmd/config.c
  tools/s2i-dpdk/test/test-app/test-pmd/csumonly.c
  tools/s2i-dpdk/test/test-app/test-pmd/flowgen.c
  tools/s2i-dpdk/test/test-app/test-pmd/icmpecho.c
  tools/s2i-dpdk/test/test-app/test-pmd/iofwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/macfwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/macswap.c
  tools/s2i-dpdk/test/test-app/test-pmd/meson.build
  tools/s2i-dpdk/test/test-app/test-pmd/noisy_vnf.c
  tools/s2i-dpdk/test/test-app/test-pmd/parameters.c
  tools/s2i-dpdk/test/test-app/test-pmd/rxonly.c
  tools/s2i-dpdk/test/test-app/test-pmd/softnicfwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/testpmd.c
  tools/s2i-dpdk/test/test-app/test-pmd/testpmd.h
  tools/s2i-dpdk/test/test-app/test-pmd/txonly.c
  tools/s2i-dpdk/test/test-app/test-pmd/util.c
Labels: approved, lgtm
