Repository openshift-kni/cnf-features-deploy, pull requests merged in 2022-09, with the labels that each got.

#1236 cnf-tests: rename s2i so it will not run on dpdk focus
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/s2i/s2i.go
Labels: approved, lgtm

#1237 cnf-tests: tests in container: set FEATURES to a single string
  hack/run-functests.sh
Labels: approved, lgtm

#1229 OCPBUGS-414: ztp: default to split DU MachineConfig CRs and allow splitting as opt-in feature
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/01-container-mount-ns-and-kubelet-conf-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/01-container-mount-ns-and-kubelet-conf-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/03-sctp-machine-config-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/03-sctp-machine-config-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/04-accelerated-container-startup-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/04-accelerated-container-startup-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/06-kdump-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/06-kdump-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/disk-encryption.yaml.tmpl
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/image-registry-partition-mc.yaml.tmpl
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/workload/03-workload-partitioning.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/workload/crio.conf
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/workload/kubelet.conf
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1241 cnf-tests: Set MetalLB Namespace env var for running tests in container
  hack/run-functests.sh
Labels: approved, lgtm

#1239 s2i: switch to generic platform dpdk
  tools/s2i-dpdk/Dockerfile
Labels: approved, lgtm

#1249 ztp: OCPBUGS-239: run SR-IOV daemons on workers - Revert
  ztp/source-crs/SriovOperatorConfig.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1250 ztp: OCPBUGS-217: run PTP daemons on worker nodes only - Revert
  ztp/source-crs/PtpOperatorConfig.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1251 ztp: OCPBUGS-495: run SR-IOV daemons on workers revert
  ztp/source-crs/SriovOperatorConfig.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1252 [release-4.11] ztp: OCPBUGS-496: run PTP daemons on worker nodes only - Revert
  ztp/source-crs/PtpOperatorConfig.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1254 Revert "[release-4.10] ztp: OCPBUGS-502: run PTP daemons on worker nodes only"
  ztp/source-crs/PtpOperatorConfig.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1216 ztp: add SNO expansion readme
  ztp/gitops-subscriptions/argocd/SNOExpansion.md
Labels: approved, lgtm

#1257 [release-4.11]: cnf-tests: Cherry picks from master to allow running the tests in parallel
  Makefile
  README.md
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/pkg/clean/clean.go
  cnf-tests/testsuites/pkg/features/features.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/utils/consts.go
  cnf-tests/testsuites/pkg/utils/reporter.go
  hack/run-functests.sh
Labels: approved, lgtm

#1238 cnf-tests: add PSA labels to the default namespace
  cnf-tests/testsuites/e2esuite/sctp/sctp.go
  cnf-tests/testsuites/e2esuite/sctp/sctp_sriov.go
  cnf-tests/testsuites/pkg/features/features.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
Labels: approved, lgtm

#1261 ztp: OCPBUGS-217: set PTP daemonsetNodeSelector
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1262 ztp: OCPBUGS-239: set SR-IOV node selector
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1267 ztp: OCPBUGS-1365: Update kargs in reference performance profile CR
  ztp/source-crs/PerformanceProfile.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1258 CNF-5287: ztp: add doc for using ACM policy generator
  ztp/gitops-subscriptions/ACMPolicyGeneratorIntergration.md
Labels: approved, lgtm

#1263 CNF-5540: ztp: include machine config to allow crio config update via PGT for w…
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-ranGen.yaml
Labels: approved, lgtm

#1224 OCPBUGS-467: ztp: Validate policy evaluation intervals
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilder_test.go
  ztp/policygenerator/policyGen/policyHelper.go
  ztp/policygenerator/utils/utils.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low
