Repository openshift-kni/cnf-features-deploy, pull requests merged in 2022-03, with the labels that each got.

#987 ztp: PGT supports status updates or overlays
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilderOverlay_test.go
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericStatusCR.yaml
  ztp/policygenerator/utils/utils.go
  ztp/ran-crd/policy-gen-template-crd.yaml
Labels: approved, lgtm

#985 Bug 2047871: ztp: Add mechanism to patch inner container references at build
  ztp/resource-generator/Containerfile
  ztp/resource-generator/Makefile
  ztp/resource-generator/README.md
  ztp/resource-generator/tools/patchImageReference.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#984 Bug 2058630: ztp: Add proxy definition for AgentClusterInstall
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/resources/cluster-crs.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#989 Bug 2059663: ztp: Suppress NMStateConfig when nodeNetwork empty
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfig.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/siteConfigBuilder_test.go
  ztp/ztp-policy-generator/kustomize/plugin/policyGenerator/v1/policygenerator/siteConfig/testdata/extra-manifest/empty
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#994 owners: add Angie to ZTP and RAN Approvers
  OWNERS_ALIASES
Labels: lgtm

#1000 Bug 2061782: ztp: Add mechanism to patch inner container references at build
  ztp/resource-generator/Containerfile
  ztp/resource-generator/Makefile
  ztp/resource-generator/README.md
  ztp/resource-generator/tools/patchImageReference.sh
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#995 ztp: cleanup sourceCRs to be used for platform upgrade using PGT
  ztp/source-crs/ClusterVersion.yaml
  ztp/source-crs/ClusterVersionUpgradeGraph.yaml
Labels: approved, lgtm

#996 Bug 2038954: ztp: ClusterVersion changes for platform upgrade
  ztp/source-crs/ClusterVersion.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#997 ztp: Bug 2021688: add mutex lock for ArgoCD apps
  ztp/resource-generator/src/post-sync-entrypoint.sh
  ztp/resource-generator/src/pre-sync-entrypoint.sh
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#998 Bug 2060554: ztp: fix PersistentVolumeClaim source cr
  ztp/source-crs/StoragePVC.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1002 ztp: Update the ArgoCD upgrade procedure
  ztp/gitops-subscriptions/argocd/Upgrade.md
Labels: approved, lgtm

#990 Bug 2034926: ztp: Readme updates for ztp-deploy-wave
  ztp/gitops-subscriptions/argocd/README.md
  ztp/policygenerator/README.md
  ztp/source-crs/README.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#1001 Bug 2058997: Set ice-ptp threads to FIFO 10
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml
  ztp/source-crs/TunedPerformancePatch.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#1004 Bug 2050391: ztp: delete wave annotation from the policy-wrapped CRs
  ztp/policygenerator/README.md
  ztp/policygenerator/policyGen/policyBuilder_test.go
  ztp/policygenerator/policyGen/policyHelper.go
  ztp/source-crs/README.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1013 Bug 2063298: ztp: Set ice-ptp threads to FIFO 10
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/test-sno.yaml
  ztp/source-crs/TunedPerformancePatch.yaml
  ztp/ztp-policy-generator/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#971 Bug 2051540: cnf-tests: filter main CPU's thread siblings under the cyclic test
  cnf-tests/pod-utils/cyclictest-runner/main.go
  cnf-tests/pod-utils/pkg/node/node.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1018 Bug 2062450: ztp: Enable kdump in the DU profile
  ztp/extra-manifests-builder/06-kdump/build.sh
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/source-crs/extra-manifest/06-kdump-master.yaml
  ztp/source-crs/extra-manifest/06-kdump-worker.yaml
Labels: approved, lgtm, needs-ok-to-test, bugzilla/severity-high, bugzilla/valid-bug

#1003 vendor: bump PAO to master branch 20220309
  feature-configs/deploy/performance/operator_catalogsource.yaml
  feature-configs/deploy/performance/operator_subscription.yaml
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/build/assets/assets.go
  vendor/github.com/openshift-kni/performance-addon-operators/build/assets/configs/99-low-latency-hooks.json
  vendor/github.com/openshift-kni/performance-addon-operators/build/assets/configs/99-netdev-rps.rules
  vendor/github.com/openshift-kni/performance-addon-operators/build/assets/configs/99-runtimes.conf
  vendor/github.com/openshift-kni/performance-addon-operators/build/assets/scripts/hugepages-allocation.sh
  vendor/github.com/openshift-kni/performance-addon-operators/build/assets/scripts/low-latency-hooks.sh
  vendor/github.com/openshift-kni/performance-addon-operators/build/assets/scripts/set-rps-mask.sh
  vendor/github.com/openshift-kni/performance-addon-operators/build/assets/tuned/openshift-node-performance
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/netqueues.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  vendor/modules.txt
Labels: approved, lgtm

#1023 ztp: Make the KlusterletAddonConfigOverride purpose more clear in a comment
  ztp/gitops-subscriptions/argocd/example/siteconfig/KlusterletAddonConfigOverride.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
Labels: approved, lgtm

#1033 Bug 2062917: ztp: support adding configmap for image signature
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilderOverlay_test.go
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericCR.yaml
  ztp/policygenerator/utils/utils.go
  ztp/ran-crd/policy-gen-template-crd.yaml
  ztp/source-crs/ImageSignature.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1028 [release-4.9] ztp: Add mechanism to patch inner container references at build
  ztp/resource-generator/Containerfile
  ztp/resource-generator/Makefile
  ztp/resource-generator/README.md
  ztp/resource-generator/tools/patchImageReference.sh
Labels: approved, lgtm

#1019 ztp: Update subscription channels to latest
  ztp/source-crs/PaoSubscription.yaml
  ztp/source-crs/PtpSubscription.yaml
  ztp/source-crs/SriovSubscription.yaml
  ztp/source-crs/StorageSubscription.yaml
Labels: approved, lgtm

#1030 ztp: bug 2065713: remove sync lock on sync fail
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/post-sync.yaml
  ztp/gitops-subscriptions/argocd/resource-hook-example/siteconfig/post-sync.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#1038 Bug 2026130: fix creation of empty policy objects
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilder_test.go
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericCRWithTrailingSeparators.yaml
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-low

#963 docs: Update Custom RPMs info
  README.md
Labels: approved, lgtm

#1044 infra: Prevent annoying 'unary operator expected' messages in logs
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1029 ztp: secure boot doc for ZTP
  ztp/gitops-subscriptions/argocd/SecureBoot.md
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
  ztp/ran-crd/site-config-crd.yaml
  ztp/source-crs/PerformanceProfile.yaml
Labels: approved, lgtm

#988 vendor: Bump mcmaker dependency to v0.0.6
  go.mod
  go.sum
  vendor/github.com/lack/mcmaker/pkg/mcmaker.go
  vendor/github.com/lack/yamltrim/README.md
  vendor/github.com/lack/yamltrim/yamltrim.go
  vendor/modules.txt
Labels: approved, lgtm

#939 ztp: Add a local registry to the SNO DU profile (CNF-3759)
  go.mod
  ztp/gitops-subscriptions/argocd/ImageRegistry.md
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/siteConfig_test.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/source-crs/ImageRegistryPV.yaml
  ztp/source-crs/extra-manifest/image-registry-partition-mc.yaml.tmpl
Labels: approved, lgtm

#1046 Bug 2044400: enable siteConfig generator to accept both relative and absolute manifest paths
  ztp/siteconfig-generator/siteConfig/filesHandler.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
Labels: approved, lgtm, bugzilla/severity-unspecified, bugzilla/valid-bug
