Repository openshift-kni/cnf-features-deploy, pull requests merged in 2022-04, with the labels that each got.

#1047 ztp: Merge extra manifests to one MC
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
  ztp/siteconfig-generator/siteConfig/siteConfigHelper_test.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/user-extra-manifest/override-extra-manifest/predefined-extra-manifests-master.yaml
Labels: approved, lgtm

#1053 Bug 2071075: Update pao subscription channel to latest
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1040 ztp: Annotate generated CRs for traceability
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
  ztp/siteconfig-generator/siteConfig/siteConfigHelper_test.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Labels: approved, lgtm

#1056 Bug 2064825: add sanity checks prior to instantiating CR
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingArgocdAnnotation.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadata.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadataAnnotations.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1059 ztp: update container Makefile to support Mac
  ztp/resource-generator/Makefile
Labels: approved, lgtm

#1048 Bug 2065969: ztp: filter ztp extra manifest
  ztp/gitops-subscriptions/argocd/ExtraManifestsFilter.md
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/user-extra-manifest/user-extra-manifest.yaml
  ztp/siteconfig-generator/siteConfig/testdata/user-extra-manifest/override-extra-manifest/03-sctp-machine-config-master.yaml
Labels: approved, lgtm, bugzilla/severity-unspecified, bugzilla/valid-bug

#1037 [release-4.9] ztp: bug 2068098: Remove workload management annotation from AMQ namespace
  ztp/source-crs/AmqSubscriptionNS.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#1055 Bug 2054407: ztp: add the Operator source CR for each subscription
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/source-crs/AcceleratorsOperatorStatus.yaml
  ztp/source-crs/AmqOperatorStatus.yaml
  ztp/source-crs/ClusterLogOperatorStatus.yaml
  ztp/source-crs/PaoOperatorStatus.yaml
  ztp/source-crs/PtpOperatorStatus.yaml
  ztp/source-crs/SriovOperatorStatus.yaml
  ztp/source-crs/StorageOperatorStatus.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#1063 Bug 2072086 ztp: add v4.10 label for policies in v4.10 branch.
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-validator-ranGen.yaml
Labels: approved, lgtm

#1065 Bug 2073439: ztp: Disable podman logging when extracting container data
  ztp/gitops-subscriptions/argocd/README.md
  ztp/resource-generator/Makefile
  ztp/resource-generator/entrypoints/entrypoints
  ztp/resource-generator/entrypoints/extract
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1066 Bug 2073498: ztp: Disable podman logging when extracting container data
  ztp/gitops-subscriptions/argocd/README.md
  ztp/resource-generator/Makefile
  ztp/resource-generator/entrypoints/entrypoints
  ztp/resource-generator/entrypoints/extract
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1043 Bug 2051540: cnf-tests:cyclictest: remove smi option
  cnf-tests/pod-utils/cyclictest-runner/main.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1072 Remove PAO subscription from DU profile
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/source-crs/PaoSubscription.yaml
  ztp/source-crs/PaoSubscriptionCatalogSource.yaml
  ztp/source-crs/PaoSubscriptionNS.yaml
  ztp/source-crs/PaoSubscriptionOperGroup.yaml
Labels: approved, lgtm

#1071 Revert "ztp: include non yaml files from sourceCRs in container"
  ztp/resource-generator/Containerfile
Labels: approved, lgtm

#1061 ignore jetbrains and macos auto generated folders and files
  .gitignore
Labels: approved, lgtm

#1075 infra: Disable SRO tests on CI
  Makefile
Labels: approved, lgtm

#1078 ztp: fix broken systemd unit file path used for disk paritioning
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/source-crs/extra-manifest/image-registry-partition-mc.yaml.tmpl
Labels: approved, lgtm

#1073 Improve dpdk test debuggability
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/pkg/pods/pods.go
Labels: approved, lgtm, ok-to-test

#1077 Bug 2047291: fix siteConfig test cases which are dependant on MachineConfigs in ztp/source-crs/extra-manifests
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/01-predefined-mc-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/01-predefined-mc-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/image-registry-partition-mc.yaml.tmpl
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/workload/03-workload-partitioning.yaml
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/workload/crio.conf
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/workload/kubelet.conf
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/user-extra-manifest/override-extra-manifest/01-predefined-mc-master.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1087 owners: refresh list of compute contributors
  OWNERS_ALIASES
Labels: approved, lgtm

#1086 infra: Stop setup cluster if zero worker-cnf nodes
  hack/setup-test-cluster.sh
Labels: approved, lgtm

#1084 cnf-tests: use worker-cnf nodes in dpdk tests
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm, ok-to-test

#1081 Bug 2057566: ztp: add doc explaining mustonlyhave use when modifying list via PGT
  ztp/gitops-subscriptions/argocd/IssueWithCRGeneratedViaPolicy.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1082 cnf-tests: consume latest test additions
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/openshift-kni/numaresources-operator/internal/baseload/baseload.go
  vendor/github.com/openshift-kni/numaresources-operator/internal/resourcelist/resourcelist.go
  vendor/github.com/openshift-kni/numaresources-operator/test/deviceplugin/pkg/numacell/manifests/manifests.go
  vendor/github.com/openshift-kni/numaresources-operator/test/deviceplugin/pkg/numacell/plugin/numacell.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/config/config.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/config/fixture.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/config/infra.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/configuration.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/non_regression.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/resource_accounting.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/sched_removal.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/workload_overhead.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/workload_placement.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/workload_placement_nodelabel.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/workload_placement_nodesel.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/workload_placement_taint.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/workload_placement_tmpol.go
  vendor/github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/workload_unschedulable.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/images/images.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/noderesourcetopologies/noderesourcetopologies.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/objects/consts.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/objects/daemonset.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/objects/deployment.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/objects/objects.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/objects/pod.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/objects/wait/daemonset.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/objects/wait/deployment.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/objects/wait/errors.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/objects/wait/machineconfig.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/objects/wait/numaresources.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/objects/wait/paddingpods.go
  vendor/github.com/openshift-kni/numaresources-operator/test/utils/objects/wait/pod.go
  vendor/modules.txt
Labels: approved, lgtm

#1092 Backport extra manifest filter
  ztp/gitops-subscriptions/argocd/ExtraManifestsFilter.md
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/user-extra-manifest/user-extra-manifest.yaml
Labels: approved, lgtm

#1083 ztp: update disk partitioning docs to include use of rootDeviceHint
  ztp/gitops-subscriptions/argocd/ImageRegistry.md
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
Labels: approved, lgtm

#1085 ztp: Move disable chronyd to tuned patch
  ztp/extra-manifests-builder/05-chrony-dynamic/20-conditional-start.conf
  ztp/extra-manifests-builder/05-chrony-dynamic/README.md
  ztp/extra-manifests-builder/05-chrony-dynamic/build.sh
  ztp/extra-manifests-builder/05-chrony-dynamic/chronyd-restart.service
  ztp/extra-manifests-builder/05-chrony-dynamic/chronyd-restart.timer
  ztp/extra-manifests-builder/05-chrony-dynamic/ptp-sync-check
  ztp/extra-manifests-builder/05-chrony-dynamic/restart-chronyd
  ztp/extra-manifests-builder/05-chrony-dynamic/test.sh
  ztp/gitops-subscriptions/argocd/Upgrade.md
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/source-crs/TunedPerformancePatch.yaml
  ztp/source-crs/extra-manifest/05-chrony-dynamic-master.yaml
  ztp/source-crs/extra-manifest/05-chrony-dynamic-worker.yaml
Labels: approved, lgtm
