Repository openshift-kni/cnf-features-deploy, pull requests merged in 2022-05, with the labels that each got.

#927 cnf-tests: fix dpdk vhost test
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm

#1096 infra: improve build index image script
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1042 Bug 2060492: ztp: Update network_transport to L2
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
  ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
  ztp/source-crs/PtpConfigMaster.yaml
  ztp/source-crs/PtpConfigSlave.yaml
  ztp/source-crs/PtpConfigSlaveCvl.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#1107 infra: fix verify script to avoid git security check
  hack/verify-commits.sh
Labels: approved, lgtm

#1106 ztp: Redo the ContainerFile for ztp-site-generator
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json
  ztp/policygenerator-kustomize-plugin/Makefile
  ztp/resource-generator/Containerfile
  ztp/resource-generator/Makefile
  ztp/resource-generator/README.md
  ztp/resource-generator/tools/patchImageReference.sh
  ztp/siteconfig-generator-kustomize-plugin/Makefile
Labels: approved, lgtm

#1090 Bug 2066701: ztp: Match PerformanceProfile name with informDuValidator
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml
  ztp/source-crs/PerformanceProfile.yaml
  ztp/source-crs/TunedPerformancePatch.yaml
  ztp/source-crs/validatorCRs/informDuValidator.yaml
Labels: approved, lgtm, needs-ok-to-test, bugzilla/severity-unspecified, bugzilla/valid-bug

#1110 Bug 2074070: cnf-tests:PTP time diff between GM and Slave metrics error fix
  cnf-tests/testsuites/e2esuite/ptp/ptp.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#1100 Add netcat to cnftests image
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
Labels: approved, lgtm

#1115 [release-4.10] Bug 2064585: cnf-tests: remove mainaffinity option
  cnf-tests/pod-utils/cyclictest-runner/main.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1097 infra: bump operators and ocp version to 4.11
  hack/common.sh
Labels: approved, lgtm

#1094 cnf-tests: support multiple hugepages size
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm

#1067 cnf-tests: tuning-cni tests
  Makefile
  cnf-tests/README.md
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/security/tuning.go
  cnf-tests/testsuites/e2esuite/security/tuning_sriov.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/pkg/networks/network.go
  cnf-tests/testsuites/pkg/networks/sriov.go
Labels: approved, lgtm

#1118 [release-4.10] Bug 2068917: vendor: bump pao dependencies
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/images/images.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#1121 Fix dpdk pci allocation
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodestate_types.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
  vendor/modules.txt
Labels: approved, lgtm

#1122 vendor: [Bug 2057451] bump sriov package to support the ice driver
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
  vendor/modules.txt
Labels: approved, lgtm
