Repository openshift-kni/cnf-features-deploy, pull requests merged in 2022-02, with the labels that each got.

#937 ztp: SiteConfig template overrides
  ztp/ran-crd/site-config-crd.yaml
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/siteConfig_test.go
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badAnnotation.yaml
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badName.yaml
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badNamespace.yaml
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-NotTemplated.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride.yaml
  ztp/siteconfig-generator/siteConfig/testdata/notyaml.yaml
Labels: approved, lgtm

#924 ztp: ovs-vswitchd running more threads than expected
  ztp/extra-manifests-builder/04-accelerated-container-startup/accelerated-container-startup.sh
  ztp/extra-manifests-builder/04-accelerated-container-startup/test.sh
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-master.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-worker.yaml
Labels: approved, lgtm, ok-to-test

#941 features: Fix ran profile CI lane
  feature-configs/ci/sro/nfd-subscription.yaml
  feature-configs/cn-ran-overlays/ran-profile-gcp/cluster-config/ci/sro/nfd-subscription.yaml
Labels: approved, lgtm

#918 Bug 2038253: ztp: Add bindingExcludedRules in PGT
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilder_test.go
  ztp/policygenerator/policyGen/policyHelper.go
  ztp/policygenerator/utils/utils.go
  ztp/ran-crd/policy-gen-template-crd.yaml
  ztp/source-crs/validatorCRs/informDuValidator.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#935 ztp/more doc cleanup 4.10
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/ztp_gitops_flow.png
Labels: approved, lgtm

#943 ztp/bug2049154 document ztp namespace restriction
  ztp/gitops-subscriptions/argocd/README.md
Labels: approved, lgtm

#940 ztp: Expand content in upgrade guide.
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/Upgrade.md
Labels: approved, lgtm

#936 Bug2046775: ztp add openshift gitops operator
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/deployment/openshift-gitops-operator.yaml
Labels: approved, lgtm

#947 ztp: Move obsolete policy handling to README
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/Upgrade.md
Labels: approved, lgtm

#951 ztp: Add another example error to the troubleshooting section
  ztp/gitops-subscriptions/argocd/README.md
Labels: approved, lgtm

#926 ztp: update default subscription CRs
  ztp/source-crs/AcceleratorsSubscription.yaml
  ztp/source-crs/AmqSubscription.yaml
  ztp/source-crs/ClusterLogSubscription.yaml
  ztp/source-crs/PaoSubscription.yaml
  ztp/source-crs/PtpSubscription.yaml
  ztp/source-crs/SriovSubscription.yaml
  ztp/source-crs/StorageSubscription.yaml
Labels: approved, lgtm

#953 ztp: update README and validator policy examples
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-validator-ranGen.yaml
Labels: approved, lgtm

#942 Bug 2050393: ztp: Add support for customer features
  ztp/source-crs/ImageRegistryConfig.yaml
  ztp/source-crs/MachineConfigGeneric.yaml
  ztp/source-crs/StoragePVC.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#850 features: Move our mount namespace execstart last
  feature-configs/deploy/container-mount-namespace/container-private-mounts/mc-container-mount-namespace.yaml
Labels: approved, lgtm

#961 [release-4.7] vendor: bump PAO to 4.7-release 20220214
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-version/CHANGELOG.md
  vendor/github.com/hashicorp/go-version/LICENSE
  vendor/github.com/hashicorp/go-version/README.md
  vendor/github.com/hashicorp/go-version/constraint.go
  vendor/github.com/hashicorp/go-version/go.mod
  vendor/github.com/hashicorp/go-version/version.go
  vendor/github.com/hashicorp/go-version/version_collection.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/nodes/nodes.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/utils.go
  vendor/modules.txt
Labels: approved, lgtm

#948 Bug 2051443: cnf-tests: filter main thread CPU siblings under the oslat test
  cnf-tests/pod-utils/oslat-runner/main.go
  cnf-tests/pod-utils/pkg/node/node.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#968 Bug 2044339 ztp: update ClusterVersion source CR
  ztp/source-crs/ClusterVersion.yaml
Labels: approved, lgtm

#966 [release-4.8] Bump pao dependency 4.8 158bf9c5
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/api/v2/performanceprofile_types.go
  vendor/modules.txt
Labels: approved, lgtm

#964 [release-4.9] Bump pao dependency 4.9 149545b9
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodestate_types.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
  vendor/github.com/openshift-kni/performance-addon-operators/api/v2/performanceprofile_types.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/netqueues.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/daemonset/daemonset.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/images/images.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/images/prepull.go
  vendor/modules.txt
Labels: approved, lgtm

#973 Bug 2046775: ztp update Argocd patch
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json
  ztp/gitops-subscriptions/argocd/deployment/deployment-openshift-repo-server-patch.json
  ztp/gitops-subscriptions/argocd/deployment/openshift-gitops-operator.yaml
  ztp/resource-generator/Makefile
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#949 ztp: Redo the ContainerFile for ztp-site-generator
  ztp/policygenerator-kustomize-plugin/Makefile
  ztp/resource-generator/Containerfile
  ztp/resource-generator/Makefile
  ztp/resource-generator/entrypoints/extract
  ztp/siteconfig-generator-kustomize-plugin/Makefile
Labels: approved, lgtm

#959 Top-level README.md updates
  .githooks/components.sh
  README.md
Labels: approved, lgtm

#922 Bug 2040799: Set summary_interval and logSyncInterval to 0
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
  ztp/policygenerator/testData/TestPtpConfig/templates/TestPtpConfig.yaml
  ztp/source-crs/PtpConfigMaster.yaml
  ztp/source-crs/PtpConfigSlave.yaml
  ztp/source-crs/PtpConfigSlaveCvl.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#977 ztp: Update container builder to golang 1.17
  ztp/resource-generator/Containerfile
Labels: approved, lgtm

#976 Bug 2056968: ztp: Added proxy definition for AgentClusterInstall
  ztp/siteconfig-generator/siteConfig/clusterCRs.go
Labels: approved, lgtm, ok-to-test, bugzilla/severity-high, bugzilla/valid-bug

#979 ztp: Update upstream container location to quay.io/openshift-kni/ztp-site-generator
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json
  ztp/resource-generator/Makefile
  ztp/resource-generator/README.md
Labels: approved

#974 ztp: Adding SriovFec configuration
  ztp/source-crs/SriovFecClusterConfig.yaml
Labels: approved, lgtm, needs-ok-to-test
