Repository openshift-kni/cnf-features-deploy, pull requests merged in 2022-01, with the labels that each got.

#865 infra: bump operators to 4.10
  feature-configs/ci/sro/sro-subscription.yaml
  feature-configs/cn-ran-overlays/ran-profile-gcp/cluster-config/ci/sro/sro-subscription.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
  feature-configs/deploy/metallb/operator_subscription.yaml
  feature-configs/deploy/ptp/03_subscription.yaml
  feature-configs/deploy/sriov/03-sriov-subscription.yaml
  feature-configs/deploy/sro/nfd-subscription.yaml
  feature-configs/deploy/sro/sro-subscription.yaml
  hack/common.sh
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#891 infra: remove temp use of metallb frr image from ci registry
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#860 Update OWNERS_ALIASES file.
  OWNERS_ALIASES
Labels: approved, lgtm

#792 Bug 2021077: ztp: add local volume provisioning
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/source-crs/StorageLV.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#855 ztp: move sno PerformanceProfile to group
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/source-crs/PerformanceProfile.yaml
  ztp/source-crs/TunedPerformancePatch.yaml
Labels: approved, lgtm

#872 ztp/multinode policy reduction
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
Labels: approved, lgtm

#894 cnf-tests: fix the dpdk command indentation
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm

#892 oot-driver: use DockerImage insted of ImageStreamTag for the driverContainer
  tools/oot-driver/Makefile
  tools/oot-driver/hack/create-special-resource.sh
Labels: approved, lgtm, ok-to-test

#791 Bug 2002376: add local volume provisioning
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/source-crs/StorageLV.yaml
  ztp/source-crs/StorageSubscription.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#899 owners: Update OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: approved, lgtm

#897 owners: Update OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: approved, lgtm

#898 owners: Update OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: approved, lgtm

#902 Bug 2039981: ztp: Ensure standard cluster masters do not get stalld
  ztp/source-crs/TunedPerformancePatch.yaml
Labels: approved, lgtm, bugzilla/severity-unspecified, bugzilla/valid-bug

#900 Bug 2036990: Adjust ztp-done policy to work with multi-node clusters (plus 50-nto-* MC)
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/source-crs/validatorCRs/informDuValidator.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#908 Bug 2035015: ztp: Do not specify openshift namespaces in the ClusterLogForwarder CR
  ztp/source-crs/ClusterLogForwarder.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#905 features: Update PTP config to pass validations
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
Labels: approved, lgtm

#901 Bug 2039425: disable klusterlet applactionManager
  ztp/siteconfig-generator/siteConfig/clusterCRs.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#903 oot-driver: address lingering containers during reboot cycles
  tools/oot-driver/files/script/oot-driver
Labels: approved, lgtm, ok-to-test

#913 Bug 2037554: ztp: Add detail to error message for policy wave mis-match
  ztp/policygenerator/policyGen/policyHelper.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#914 Bug 2037939 ztp fix cluster version source-crs
  ztp/source-crs/ClusterVersion.yaml
Labels: approved, lgtm

#917 Bug 2041639: ztp: Add DisableSnoNetworkDiag to group-du-sno PolicyGenTemplate
  ztp/gitops-subscriptions/argocd/resource-hook-example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/ztp-policy-generator/testPolicyGenTemplate/group-du-sno-ranGen.yaml
Labels: approved, lgtm, needs-ok-to-test, bugzilla/valid-bug, bugzilla/severity-medium

#911 Bug 2040791: ztp: Change the default PolicyGenerator to generate inform, not enforce policies
  ztp/policygenerator/policyGen/policyBuilder_test.go
  ztp/policygenerator/policyGen/policyTemplate.go
  ztp/policygenerator/utils/utils.go
  ztp/ran-crd/policy-gen-template-crd.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#906 Bug 2040467: fix build ztp-site-generator image
  ztp/resource-generator/Containerfile
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#920 ztp: Remove PtpOperatorConfig from SNO and 3node example PGTs
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
Labels: approved, lgtm

#923 ztp: Support existing customer Storage config
  ztp/source-crs/StorageClass.yaml
  ztp/source-crs/StorageLocalVolume.yaml
Labels: approved, lgtm

#928 ztp/entrypoint reshuffle
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
  ztp/policygenerator/README.md
  ztp/resource-generator/Containerfile
  ztp/resource-generator/entrypoints/entrypoints
  ztp/resource-generator/entrypoints/extract
Labels: approved, lgtm

#934 vendor: update MetalLB dependencies
  go.mod
  go.sum
  vendor/github.com/metallb/metallb-operator/api/v1beta1/bgppeer_types.go
  vendor/github.com/metallb/metallb-operator/api/v1beta1/bgppeer_webhook.go
  vendor/github.com/metallb/metallb-operator/test/e2e/functional/tests/e2e.go
  vendor/github.com/metallb/metallb-operator/test/e2e/metallb/metallb.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test
