Repository openshift-kni/cnf-features-deploy, pull requests merged in 2022-12, with the labels that each got.

#1319 ztp: OCPBUGS-3005: set step_threshold to 2.0
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
  ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
  ztp/source-crs/PtpConfigMaster.yaml
  ztp/source-crs/PtpConfigSlave.yaml
  ztp/source-crs/PtpConfigSlaveCvl.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1318 ztp: OCPBUGS-2336: Set dataset_comparison to G.8275.x
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
  ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
  ztp/source-crs/PtpConfigMaster.yaml
  ztp/source-crs/PtpConfigSlave.yaml
  ztp/source-crs/PtpConfigSlaveCvl.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1353 [release-4.11] cnf-tests: improve sriov nic selector
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/pkg/networks/sriov.go
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
  vendor/modules.txt
Labels: approved, lgtm

#1337 fix for ptp interfaces test failure
  go.mod
  go.sum
  vendor/github.com/test-network-function/l2discovery-lib/l2lib.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#1352 infra: revert "cnf-tests: Filter tests by features suites"
  hack/run-functests.sh
Labels: approved, lgtm

#1355 [release-4.11] infra: Fix SRO deployment
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1359 cnf-tests: add PSA for performance tests` NS
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
Labels: approved, lgtm

#1356 infra: Add feature-deploy-on-ci task to Makefile for U/S CI
  Makefile
Labels: approved, lgtm
