Repository openshift-kni/cnf-features-deploy, pull requests merged in 2022-06, with the labels that each got.

#1125 ztp: Bump gitops operator version in docs
  ztp/gitops-subscriptions/argocd/README.md
Labels: approved, lgtm, needs-ok-to-test

#1123 cnf-tests: Fix dpdk tests
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm

#1127 cnf-tests: fix tuning tests
  cnf-tests/testsuites/e2esuite/security/tuning_sriov.go
Labels: approved, lgtm

#1133 infra: use a specific podman version to build the index images
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1132 cnf-tests: Bump test images to 4.11
  cnf-tests/mirror/images.json
  cnf-tests/testsuites/pkg/images/images.go
  hack/run-functests.sh
Labels: approved, lgtm

#1134 Bug 2087208 - informDuValidator (multi-yaml) policy fails when overlay status in multi yaml file
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilderOverlay_test.go
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericMultiYaml.yaml
Labels: approved, lgtm

#1119 cnf-tests: networkAttachmentDefinitionBuilder refactoring
  cnf-tests/testsuites/e2esuite/security/tuning.go
  cnf-tests/testsuites/e2esuite/security/tuning_sriov.go
  cnf-tests/testsuites/pkg/networks/network.go
Labels: approved, lgtm

#1138 cnf-tests: Fix dpdk tests
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm

#1141 cnf-tests: [release-4.7] Fix dpdk tests
  functests/dpdk/dpdk.go
Labels: approved, lgtm

#1142 cnf-tests: fix for failing tuning over sriov test
  cnf-tests/testsuites/e2esuite/security/tuning_sriov.go
Labels: approved, lgtm

#1147 features: MetalLB: remove targetNamespaces
  feature-configs/deploy/metallb/operator_operatorgroup.yaml
Labels: approved, lgtm

#1120 cnf-tests: bond cni on over macvlan test
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/bond/bond.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
Labels: approved, lgtm

#1146 Bug 2098156: ptp offset metrics for master count should be one
  cnf-tests/testsuites/e2esuite/ptp/ptp.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#1137 Bug 2093969: cnf-tests: [release 4.9] Fix dpdk tests
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#1145 s2i: bump dpdk version to 21.11
  tools/s2i-dpdk/Dockerfile
Labels: approved, lgtm

#1155 Bug 2101356: ztp: Increase kdump size to 512M
  ztp/extra-manifests-builder/06-kdump/build.sh
  ztp/source-crs/extra-manifest/06-kdump-master.yaml
  ztp/source-crs/extra-manifest/06-kdump-worker.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
