Repository openshift-kni/cnf-features-deploy, pull requests merged in 2022-10, with the labels that each got.

#1264 ztp: Add an option to enable/disable inspection
  ztp/ran-crd/site-config-crd.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-sno-du.yaml
  ztp/siteconfig-generator/siteConfig/clusterCRs.go
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
Labels: approved, lgtm

#1286 [release-4.10] Bug 2109882: ztp: Update cpuset calculation in accelerated-container-startup.sh
  ztp/extra-manifests-builder/04-accelerated-container-startup/accelerated-container-startup.sh
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-master.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-worker.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#1287 cnf-tests: intentionally ignore NROP setup errors
  cnf-tests/testsuites/pkg/features/features.go
Labels: approved, lgtm

#1113 Multus network policies
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  cnf-tests/README.md
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/docgen/validation.json
  cnf-tests/testsuites/e2esuite/multinetworkpolicy/multinetworkpolicy_sriov.go
  cnf-tests/testsuites/e2esuite/multinetworkpolicy/reachmatcher.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/pkg/client/clients.go
  cnf-tests/testsuites/pkg/client/wait.go
  cnf-tests/testsuites/pkg/features/features.go
  cnf-tests/testsuites/pkg/k8sreporter/reporter.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/networkpolicy/multinetworkpolicy.go
  cnf-tests/testsuites/pkg/networks/sriov.go
  cnf-tests/testsuites/pkg/nodes/nodes.go
  cnf-tests/testsuites/pkg/pods/pods.go
  cnf-tests/testsuites/pkg/utils/consts.go
  cnf-tests/testsuites/pkg/utils/reporter.go
  cnf-tests/testsuites/validationsuite/cluster/validation.go
  feature-configs/ci/multinetworkpolicy/kustomization.yaml
  feature-configs/deploy/multinetworkpolicy/enable_multinetworkpolicy.yaml
  feature-configs/deploy/multinetworkpolicy/kustomization.yaml
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/LICENSE
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/register.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1beta1/doc.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1beta1/register.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1beta1/types.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1beta2/doc.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1beta2/register.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1beta2/types.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1beta2/zz_generated.deepcopy.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/client/clientset/versioned/typed/k8s.cni.cncf.io/v1beta1/doc.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/client/clientset/versioned/typed/k8s.cni.cncf.io/v1beta1/generated_expansion.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/client/clientset/versioned/typed/k8s.cni.cncf.io/v1beta1/k8s.cni.cncf.io_client.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/client/clientset/versioned/typed/k8s.cni.cncf.io/v1beta1/multinetworkpolicy.go
  vendor/modules.txt
Labels: approved, lgtm

#1268 vendor: update 4.10 pao dependencies
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/openshift-kni/performance-addon-operators/api/v2/performanceprofile_types.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/1_performance/performance.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/4_latency/latency.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/images/prepull.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/pods/pods.go
  vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/profiles/profiles.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  vendor/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/profile/profile.go
  vendor/modules.txt
Labels: approved, lgtm

#1285 OCPBUGS-1898: ztp: Allow Argocd policy app to sync configmap
  ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1256 infra: Bump CNF deployment and tests to 4.12
  cnf-tests/mirror/images.json
  cnf-tests/testsuites/pkg/images/images.go
  hack/common.sh
  hack/run-functests.sh
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1143 Bug 2051443: cnf-tests: verify minimal CPUs requirement for oslat test
  cnf-tests/pod-utils/oslat-runner/main.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#1297 ztp: OCPBUGS-2329: fix deployment order and tuned name
  ztp/gitops-subscriptions/argocd/SNOExpansion.md
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#1300 ztp: fix sno expansion tuned include directive
  ztp/gitops-subscriptions/argocd/SNOExpansion.md
Labels: approved, lgtm

#1294 cnf-tests: Skip test if multinetpolicy CRD is not present
  cnf-tests/testsuites/e2esuite/multinetworkpolicy/multinetworkpolicy_sriov.go
  cnf-tests/testsuites/pkg/networkpolicy/multinetworkpolicy.go
  cnf-tests/testsuites/validationsuite/cluster/validation.go
Labels: approved, lgtm

#1293 OCPBUGS-1594: Fec tests: do not clean in discovery mode
  cnf-tests/testsuites/e2esuite/fec/fec.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1305 infra: Pin packages for go version dependency
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#1304 ztp: set AMQP as default transport type
  ztp/source-crs/HardwareEvent.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm
