Repository openshift-kni/cnf-features-deploy, pull requests merged in 2022-08, with the labels that each got.

#1190 ztp: Enable workload partitioning on SNO worker
  ztp/siteconfig-generator-kustomize-plugin/kustomization.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-expansion.yaml
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/source-crs/extra-manifest/workload/03-workload-partitioning.yaml
Labels: approved, lgtm

#1201 cnf-tests: Add support for PSA on test namespaces
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
Labels: approved, lgtm

#1163 [release-4.10] Bug 2102386: ztp: Increase kdump size to 512M
  ztp/extra-manifests-builder/06-kdump/build.sh
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/source-crs/extra-manifest/06-kdump-master.yaml
  ztp/source-crs/extra-manifest/06-kdump-worker.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1186 Bug 2110015: Revert ptp interval changes
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
  ztp/policygenerator/testData/TestPtpConfig/templates/TestPtpConfig.yaml
  ztp/source-crs/PtpConfigMaster.yaml
  ztp/source-crs/PtpConfigSlave.yaml
  ztp/source-crs/PtpConfigSlaveCvl.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1204 ztp: rename Bare Metal Event Relay feature
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml
  ztp/source-crs/BareMetalEventRelaySubscription.yaml
  ztp/source-crs/BareMetalEventRelaySubscriptionNS.yaml
  ztp/source-crs/BareMetalEventRelaySubscriptionOperGroup.yaml
  ztp/source-crs/HardwareEvent.yaml
Labels: approved, lgtm

#1202 fix `[sriov] Bond CNI integration bond cni over sriov` test
  cnf-tests/testsuites/e2esuite/bond/bond.go
  cnf-tests/testsuites/e2esuite/bond/bond_sriov.go
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/s2i/s2i.go
  cnf-tests/testsuites/e2esuite/security/tuning.go
  cnf-tests/testsuites/e2esuite/security/tuning_sriov.go
  cnf-tests/testsuites/e2esuite/vrf/vrf.go
  cnf-tests/testsuites/e2esuite/vrf/vrf_sriov.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/networks/sriov.go
Labels: approved, lgtm

#1195 cnf-tests: Split setup and cleanup by feature
  Makefile
  README.md
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/pkg/clean/clean.go
  cnf-tests/testsuites/pkg/features/features.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/utils/consts.go
  cnf-tests/testsuites/pkg/utils/reporter.go
  hack/run-functests.sh
Labels: approved, lgtm

#1209 [release-4.10] fix [sriov] Bond CNI integration bond cni over sriov test
  cnf-tests/testsuites/e2esuite/bond/bond.go
  cnf-tests/testsuites/e2esuite/bond/bond_sriov.go
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/vrf/vrf.go
  cnf-tests/testsuites/e2esuite/vrf/vrf_sriov.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/networks/sriov.go
Labels: approved, lgtm

#1210 Bug 2104669: pin metallb-operator to openshift/metallb-operator@release-4.9
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/metallb/metallb-operator/api/v1beta1/metallb_types.go
  vendor/github.com/metallb/metallb-operator/api/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/metallb/metallb-operator/test/e2e/functional/tests/e2e.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1206 Move disable chronyd to tuned patch
  ztp/extra-manifests-builder/05-chrony-dynamic/20-conditional-start.conf
  ztp/extra-manifests-builder/05-chrony-dynamic/README.md
  ztp/extra-manifests-builder/05-chrony-dynamic/build.sh
  ztp/extra-manifests-builder/05-chrony-dynamic/chronyd-restart.service
  ztp/extra-manifests-builder/05-chrony-dynamic/chronyd-restart.timer
  ztp/extra-manifests-builder/05-chrony-dynamic/ptp-sync-check
  ztp/extra-manifests-builder/05-chrony-dynamic/restart-chronyd
  ztp/extra-manifests-builder/05-chrony-dynamic/test.sh
  ztp/gitops-subscriptions/argocd/Upgrade.md
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/source-crs/MachineConfigChronyDynamicMaster.yaml
  ztp/source-crs/TunedPerformancePatch.yaml
  ztp/source-crs/extra-manifest/05-chrony-dynamic-master.yaml
  ztp/source-crs/extra-manifest/05-chrony-dynamic-worker.yaml
Labels: approved, lgtm

#1215 cnf-tests: Fix PSA and S2I filter
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/gatekeeper/gatekeeper.go
  cnf-tests/testsuites/e2esuite/s2i/s2i.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/pods/pods.go
Labels: approved, lgtm

#1222 Bug 2049306: ztp: Fix the user overrides for a list
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilderOverlay_test.go
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericCR.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1208 ztp: Prevent changing immutable objects on sno expansion
  ztp/siteconfig-generator/siteConfig/siteConfig.go
Labels: approved, lgtm

#1213 ztp: OCPBUGS-217: run PTP daemons on worker nodes only
  ztp/source-crs/PtpOperatorConfig.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1214 ztp: OCPBUGS-239: run SR-IOV daemons on workers
  ztp/source-crs/SriovOperatorConfig.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1218 cnf-tests: Avoid clean SR-IOV resources
  cnf-tests/testsuites/e2esuite/sctp/sctp_sriov.go
  cnf-tests/testsuites/e2esuite/vrf/vrf_sriov.go
Labels: approved, lgtm

#1221 bug 2057566: ztp: remove invalid doc describing a problem that is set to go away
  ztp/gitops-subscriptions/argocd/IssueWithCRGeneratedViaPolicy.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#1212 cnf-tests: reporter: Grab MetalLB logs
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/utils/reporter.go
  feature-configs/ci/metallb/operator_subscription.yaml
  feature-configs/deploy/metallb/operator_namespace.yaml
  feature-configs/deploy/metallb/operator_operatorgroup.yaml
  feature-configs/deploy/metallb/operator_subscription.yaml
  hack/common.sh
Labels: approved, lgtm

#1223 infra: Fix wait for build index container loop
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1220 cnf-tests: Allow focusing on features by ginkgo describe or context
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/docgen/validation.json
  cnf-tests/testsuites/e2esuite/bond/bond.go
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/fec/fec.go
  cnf-tests/testsuites/e2esuite/gatekeeper/gatekeeper.go
  cnf-tests/testsuites/e2esuite/junit.xml/cnftests-junit.xml
  cnf-tests/testsuites/e2esuite/ovs_qos/ovs_qos.go
  cnf-tests/testsuites/e2esuite/ptp/ptp.go
  cnf-tests/testsuites/e2esuite/s2i/s2i.go
  cnf-tests/testsuites/e2esuite/sctp/sctp.go
  cnf-tests/testsuites/e2esuite/security/tuning.go
  cnf-tests/testsuites/e2esuite/sro/sro.go
  cnf-tests/testsuites/e2esuite/xt_u32/xt_u32.go
  cnf-tests/testsuites/validationsuite/cluster/validation.go
Labels: approved, lgtm

#1230 cnf-tests: Set FEATURES env var for running tests in container
  hack/run-functests.sh
Labels: approved, lgtm

#884 Bug 2008689: deploy a MC to enable iommu when fec is requested
  feature-configs/deploy/fec/kustomization.yaml
  feature-configs/deploy/fec/mc-worker.yaml
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug
