Repository openshift-kni/cnf-features-deploy, pull requests merged in 2022-07, with the labels that each got.

#1150 infra: Improve feature-wait timeout
  hack/feature-wait.sh
Labels: approved, lgtm

#1153 cnf-tests: Add bond related resources to reporter
  cnf-tests/testsuites/e2esuite/bond/bond.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/utils/reporter.go
Labels: approved, lgtm

#1156 Bug 2101812: cnf-tests: fix tuning sriov skip on discovery mode
  cnf-tests/testsuites/e2esuite/security/tuning_sriov.go
Labels: approved, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#1174 cnf-tests: add mtu to nad builder
  cnf-tests/testsuites/e2esuite/bond/bond.go
  cnf-tests/testsuites/e2esuite/security/tuning_sriov.go
  cnf-tests/testsuites/pkg/networks/network.go
Labels: approved, lgtm

#1129 cnf-tests: tuning over bond interfaces should be able to ping
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/security/tuning.go
Labels: approved, lgtm

#1159 cnf-tests: bond cni over sriov
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/bond/bond_sriov.go
Labels: approved, lgtm

#1175 cnf-tests: NetworkAttachmentDefinitionBuilder refactoring
  cnf-tests/testsuites/pkg/networks/network.go
Labels: approved, lgtm

#1176 cnf-tests: bond cni on macvlan test
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/bond/bond.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
Labels: approved, lgtm

#1167 Allow running cnf-tests in parallel
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  hack/run-functests.sh
  hack/setup-test-cluster.sh
Labels: approved, lgtm

#1182 ztp: Remove `run-level: "1"` annotation from the SR-IOV Namespace source CR
  ztp/source-crs/SriovSubscriptionNS.yaml
Labels: approved, lgtm

#1171 rename Bare Metal Event Relay feature
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml
  ztp/source-crs/BareMetalEventRelaySubscription.yaml
  ztp/source-crs/BareMetalEventRelaySubscriptionNS.yaml
  ztp/source-crs/BareMetalEventRelaySubscriptionOperGroup.yaml
  ztp/source-crs/HardwareEvent.yaml
Labels: approved, lgtm, ok-to-test

#1180 cnf-tests: Add bond related resources to reporter
  cnf-tests/testsuites/e2esuite/bond/bond.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/utils/reporter.go
Labels: approved, lgtm

#1168 add a new s2i FEATURE
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/docgen/validation.json
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/s2i/s2i.go
  cnf-tests/testsuites/e2esuite/sctp/sctp_sriov.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/e2esuite/vrf/vrf_sriov.go
  cnf-tests/testsuites/pkg/networks/sriov.go
  cnf-tests/testsuites/pkg/performanceprofile/performanceprofile.go
  cnf-tests/testsuites/pkg/pods/pods.go
  cnf-tests/testsuites/pkg/sriov/sriov.go
  cnf-tests/testsuites/validationsuite/cluster/validation.go
  feature-configs/ci/s2i/kustomization.yaml
  feature-configs/ci/s2i/post_deploy.sh
  feature-configs/demo/s2i/deployment-config.yaml
  feature-configs/demo/s2i/dpdk-network.yaml
  feature-configs/demo/s2i/kustomization.yaml
  feature-configs/demo/s2i/scc.yaml
  feature-configs/demo/s2i/sriov-networknodepolicy-dpdk.yaml
  feature-configs/deploy/s2i/build-config.yaml
  feature-configs/deploy/s2i/kustomization.yaml
  feature-configs/deploy/s2i/namespace.yaml
  feature-configs/deploy/s2i/post_deploy.sh
  tools/s2i-dpdk/Dockerfile
  tools/s2i-dpdk/test/test-app/build.sh
  tools/s2i-dpdk/test/test-app/l2fwd/Makefile
  tools/s2i-dpdk/test/test-app/l2fwd/main.c
  tools/s2i-dpdk/test/test-app/l2fwd/meson.build
  tools/s2i-dpdk/test/test-app/run.sh
  tools/s2i-dpdk/test/test-app/test-pmd/5tswap.c
  tools/s2i-dpdk/test/test-app/test-pmd/bpf_cmd.c
  tools/s2i-dpdk/test/test-app/test-pmd/bpf_cmd.h
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_flow.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_mtr.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_mtr.h
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_tm.c
  tools/s2i-dpdk/test/test-app/test-pmd/cmdline_tm.h
  tools/s2i-dpdk/test/test-app/test-pmd/config.c
  tools/s2i-dpdk/test/test-app/test-pmd/csumonly.c
  tools/s2i-dpdk/test/test-app/test-pmd/flowgen.c
  tools/s2i-dpdk/test/test-app/test-pmd/icmpecho.c
  tools/s2i-dpdk/test/test-app/test-pmd/ieee1588fwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/iofwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/macfwd.c
  tools/s2i-dpdk/test/test-app/test-pmd/macswap.c
  tools/s2i-dpdk/test/test-app/test-pmd/macswap.h
  tools/s2i-dpdk/test/test-app/test-pmd/macswap_common.h
  tools/s2i-dpdk/test/test-app/test-pmd/macswap_neon.h
  tools/s2i-dpdk/test/test-app/test-pmd/macswap_sse.h
  tools/s2i-dpdk/test/test-app/test-pmd/meson.build
  tools/s2i-dpdk/test/test-app/test-pmd/noisy_vnf.c
  tools/s2i-dpdk/test/test-app/test-pmd/parameters.c
  tools/s2i-dpdk/test/test-app/test-pmd/rxonly.c
  tools/s2i-dpdk/test/test-app/test-pmd/testpmd.c
  tools/s2i-dpdk/test/test-app/test-pmd/testpmd.h
  tools/s2i-dpdk/test/test-app/test-pmd/txonly.c
  tools/s2i-dpdk/test/test-app/test-pmd/util.c
  tools/s2i-dpdk/test/test-app/test-template.sh
Labels: approved, lgtm

#1191 cnf-tests: add mtu to nad builder
  cnf-tests/testsuites/e2esuite/bond/bond.go
  cnf-tests/testsuites/pkg/networks/network.go
Labels: approved, lgtm

#1178 Bug 2097488 cnf-tests: bump `sriov-network-operator` commit
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/sriov_operator.go
  vendor/modules.txt
Labels: approved, lgtm

#1193 cnf-tests: bond cni over sriov
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/bond/bond_sriov.go
  cnf-tests/testsuites/pkg/networks/sriov.go
Labels: approved, lgtm

#1177 Bug 2104611: Bug 2104604: [release-4.9] Backport #1117, #1095
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1162 features: dpdk build: Check for more states in post deploy script
  feature-configs/deploy/s2i/post_deploy.sh
Labels: approved, lgtm
