Repository openshift-kni/cnf-features-deploy, pull requests merged in 2023-09, with the labels that each got.

#1629 [release-4.13] Backport of `[sriov] NUMA` ExcludeTopology test cases
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
  cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go
  cnf-tests/testsuites/pkg/nodes/nodes.go
  cnf-tests/testsuites/pkg/performanceprofile/performanceprofile.go
  cnf-tests/testsuites/pkg/pods/pods.go
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodepolicy_types.go
  vendor/modules.txt
Labels: approved, lgtm

#1628 cnf-tests: Run unit tests during CI
  Makefile
Labels: approved, lgtm

#1634 Bump cnf-features-deploy to go 1.20
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  go.mod
  openshift-ci/Dockerfile.tools
  ztp/resource-generator/Containerfile
Labels: approved, lgtm

#1633 cnf-tests: fix `ApplyKubeletConfigToNode` cleanup
  cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go
Labels: approved, lgtm

#1638 ztp: correct examples using InstallerArgs
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-expansion.yaml
Labels: approved, lgtm, needs-ok-to-test

#1639 vendor: bump nto deps
  go.mod
  go.sum
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/performance.go
  vendor/modules.txt
Labels: approved, lgtm

#1644 cnf-tests: Dump correct code line on failure
  cnf-tests/testsuites/configsuite/test_suite_test.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/validationsuite/test_suite_test.go
Labels: approved, lgtm

#1642 cnf-tests: Bump origin-oc-rpms version
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
Labels: approved, lgtm

#1647 cnf-tests: Add fsGroup for rootless dpdk pod
  cnf-tests/testsuites/pkg/pods/pods.go
  tools/s2i-dpdk/Dockerfile
Labels: approved, lgtm

#1653 OCPBUGS-19041: ztp: set BC clock_class_threshold to 135
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-boundary.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-boundary.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1645 vendor: bump NTO version
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/client/client.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/client/listers.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/hugepages.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/netqueues.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/performance.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/4_latency/latency.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  vendor/modules.txt
Labels: approved, lgtm

#1652 OCPBUGS-18717: ztp: Add dplll settings to wpc gm ptpconfig
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1657 [release-4.13] OCPBUGS-18553: Disable rcu_expedited after node has finished booting
  ztp/extra-manifests-builder/08-set-rcu-normal/README.md
  ztp/extra-manifests-builder/08-set-rcu-normal/build.sh
  ztp/extra-manifests-builder/08-set-rcu-normal/set-rcu-normal.service
  ztp/extra-manifests-builder/08-set-rcu-normal/set-rcu-normal.sh
  ztp/extra-manifests-builder/08-set-rcu-normal/test.sh
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/source-crs/extra-manifest/08-set-rcu-normal-master.yaml
  ztp/source-crs/extra-manifest/08-set-rcu-normal-worker.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1648 ztp: Pin all examples for the 4.14 release
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-multinode-site.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-3node-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-standard-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
Labels: approved, lgtm

#1663 OCPBUGS-19041: ztp: fix clock_class_threshold for BC 4.15
  ztp/source-crs/PtpConfigBoundary.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1664 OCPBUGS-19066: ztp: fix clock_class_threshold for BC 4.14
  ztp/source-crs/PtpConfigBoundary.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
