Repository openshift-kni/cnf-features-deploy, pull requests merged in 2023-01, with the labels that each got.

#1361 ztp: Remove ovs from accelerated-container-startup
  ztp/extra-manifests-builder/04-accelerated-container-startup/accelerated-container-startup.sh
  ztp/extra-manifests-builder/04-accelerated-container-startup/test.sh
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-master.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-worker.yaml
Labels: approved, lgtm, ok-to-test

#1375 update aliases 20230109
  OWNERS_ALIASES
Labels: approved, lgtm

#1322 cnf-tests: avoid run multinetpol tests with sriov
  cnf-tests/README.md
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/multinetworkpolicy/multinetworkpolicy_sriov.go
Labels: approved, lgtm

#1374 cnf-tests: Add option for custom GINKGO_PARAMS for tests
  hack/run-functests.sh
Labels: approved, lgtm

#1381 ztp: OCPBUGS-4449: Disable ice module when doing a kdump
  ztp/extra-manifests-builder/05-kdump-config/build.sh
  ztp/extra-manifests-builder/05-kdump-config/kdump-remove-ice-module.sh
  ztp/extra-manifests-builder/05-kdump-config/test.sh
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/source-crs/extra-manifest/05-kdump-config-master.yaml
  ztp/source-crs/extra-manifest/05-kdump-config-worker.yaml
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1386 ztp: example config of composable Openshift
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
Labels: approved, lgtm

#1388 Bug 2111108: ztp: Remove container-mount-namespace.service installation warnings
  ztp/extra-manifests-builder/01-container-mount-ns-and-kubelet-conf/build.sh
  ztp/source-crs/extra-manifest/01-container-mount-ns-and-kubelet-conf-master.yaml
  ztp/source-crs/extra-manifest/01-container-mount-ns-and-kubelet-conf-worker.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
