Repository openshift-kni/cnf-features-deploy, pull requests merged in 2023-08, with the labels that each got.

#1576 cnf-tests: log test pod events on failure
  cnf-tests/testsuites/e2esuite/sctp/sctp.go
  cnf-tests/testsuites/e2esuite/security/tuning.go
  cnf-tests/testsuites/e2esuite/vrf/vrf.go
  cnf-tests/testsuites/pkg/pods/pods.go
Labels: approved, lgtm

#1563 vendor: bump NTO dependencies 20230714 release-4.13
  go.mod
  go.sum
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/scripts/cpuset-configure.sh
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  vendor/modules.txt
Labels: approved, lgtm

#1584 ztp: update performance profile to load vfio-pci
  ztp/source-crs/PerformanceProfile-SetSelector.yaml
  ztp/source-crs/PerformanceProfile.yaml
Labels: approved, lgtm

#1591 s2i: add supplementary group 801 to 1001 user
  tools/s2i-dpdk/Dockerfile
Labels: approved, lgtm

#1594 ztp: [release 4.13] update fec config to use vfio-pci
  ztp/source-crs/PerformanceProfile.yaml
  ztp/source-crs/SriovFecClusterConfig.yaml
Labels: approved, lgtm

#1585 OCPBUGS-7092 SiteConfig crTemplates override does not work with a ConfigMap CR
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/ConfigMapOverride.yaml
Labels: approved, lgtm

#1586 ztp: Remove dangling symbolic link to removed MC
  ztp/policygenerator-kustomize-plugin/README.md
  ztp/source-crs/MachineConfigAcceleratedStartup.yaml
Labels: approved, lgtm, ok-to-test

#1601 ztp: Add additional node labels example
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
Labels: approved, lgtm

#1590 cnf-tests: Add numa tests with multiple interfaces
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
Labels: approved, lgtm, ok-to-test

#1600 [release-4.11] Bump metallb vendor
  go.mod
  go.sum
  vendor/github.com/metallb/metallb-operator/pkg/status/status.go
  vendor/github.com/metallb/metallb-operator/test/e2e/functional/tests/e2e.go
  vendor/github.com/metallb/metallb-operator/test/e2e/metallb/metallb.go
  vendor/modules.txt
Labels: approved, lgtm

#1598 [release-4.13] Bump metallb vendor
  go.mod
  go.sum
  vendor/github.com/Masterminds/semver/v3/.golangci.yml
  vendor/github.com/Masterminds/semver/v3/CHANGELOG.md
  vendor/github.com/Masterminds/semver/v3/constraints.go
  vendor/github.com/Masterminds/semver/v3/doc.go
  vendor/github.com/Masterminds/semver/v3/version.go
  vendor/github.com/Masterminds/sprig/v3/CHANGELOG.md
  vendor/github.com/Masterminds/sprig/v3/README.md
  vendor/github.com/metallb/metallb-operator/pkg/status/status.go
  vendor/github.com/metallb/metallb-operator/test/e2e/functional/tests/e2e.go
  vendor/github.com/metallb/metallb-operator/test/e2e/metallb/metallb.go
  vendor/modules.txt
Labels: approved, lgtm

#1603 ztp: Update reference CR to disable telemeterClient
  ztp/source-crs/ReduceMonitoringFootprint.yaml
Labels: approved, lgtm

#1562 ztp: Update reference CRs to use vector
  ztp/source-crs/ClusterLogForwarder.yaml
  ztp/source-crs/ClusterLogging.yaml
Labels: approved, lgtm

#1604 ztp: Uncomment logging collector
  ztp/source-crs/ClusterLogging.yaml
Labels: approved, lgtm

#1605 ztp: Align reference PGT with vector
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/policygenerator/README.md
Labels: approved, lgtm

#1597 [release-4.14] Bump metallb vendor
  go.mod
  go.sum
  vendor/github.com/Masterminds/semver/v3/.golangci.yml
  vendor/github.com/Masterminds/semver/v3/CHANGELOG.md
  vendor/github.com/Masterminds/semver/v3/constraints.go
  vendor/github.com/Masterminds/semver/v3/doc.go
  vendor/github.com/Masterminds/semver/v3/version.go
  vendor/github.com/Masterminds/sprig/v3/CHANGELOG.md
  vendor/github.com/Masterminds/sprig/v3/README.md
  vendor/github.com/metallb/metallb-operator/api/v1beta1/metallb_types.go
  vendor/github.com/metallb/metallb-operator/pkg/status/status.go
  vendor/github.com/metallb/metallb-operator/test/e2e/functional/tests/e2e.go
  vendor/github.com/metallb/metallb-operator/test/e2e/metallb/metallb.go
  vendor/modules.txt
Labels: approved, lgtm

#1421 cnf-tests: Add rootless vhostnet test using tap and vlan plugins
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/pkg/networks/network.go
  cnf-tests/testsuites/pkg/networks/sriov.go
  cnf-tests/testsuites/pkg/pods/pods.go
  cnf-tests/testsuites/pkg/utils/selinux.go
Labels: approved, lgtm, ok-to-test

#1609 fix: update wording to correctly reflect version 4.14
  ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Labels: approved, lgtm, ok-to-test

#1610 OCPBUGS-13313: fix: error in messaging for cpu partitioning
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningWarningTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Labels: approved, lgtm, ok-to-test, jira/valid-bug, jira/valid-reference

#1612 ztp: Remove redundant overlay content
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
Labels: approved, lgtm

#1583 cnf-tests: dynamically created KubeletConfig
  cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
  cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go
  cnf-tests/testsuites/pkg/nodes/nodes.go
Labels: approved, lgtm

#1596 ztp: extramnifests searchPath section is re-written
  ztp/gitops-subscriptions/argocd/README.md
Labels: approved, lgtm

#1592 cnf-tests: SRIOV/NUMA consume all VFs
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
Labels: approved, lgtm

#1617 Modify k8s reporter
  cnf-tests/testsuites/configsuite/test_suite_test.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/validationsuite/test_suite_test.go
  go.mod
  go.sum
  vendor/github.com/openshift-kni/k8sreporter/client.go
  vendor/github.com/openshift-kni/k8sreporter/reporter.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/kube-openapi/pkg/cached/cache.go
  vendor/k8s.io/kube-openapi/pkg/handler3/handler.go
  vendor/k8s.io/kube-openapi/pkg/internal/handler/handler_cache.go
  vendor/modules.txt
Labels: approved, lgtm

#1616 OCPBUGS-17699: Update WPC GM config
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1621 ztp: OCPBUGS-18151: Reduce SRIOV log verbosity
  ztp/source-crs/SriovOperatorConfig-SetSelector.yaml
  ztp/source-crs/SriovOperatorConfig.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1623 cnf-tests: Fix flaky tuningcni tests
  cnf-tests/testsuites/e2esuite/security/tuning.go
  cnf-tests/testsuites/pkg/pods/pods.go
Labels: approved, lgtm

#1622 OCPBUGS-15790, OCPBUGS-15791: cnf-tests: Use `lspcu --parse` to get NUMA node
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
  cnf-tests/testsuites/pkg/numa/numa.go
  cnf-tests/testsuites/pkg/numa/numa_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1607 cnf-tests: sriov-network-operator bump 4.14
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovoperatorconfig_types.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/test_sriov_operator.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/client/clients.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
  vendor/modules.txt
Labels: approved, lgtm

#1627 OCPBUGS-17660: Disable rcu_expedited after node has finished booting
  ztp/extra-manifests-builder/08-set-rcu-normal/README.md
  ztp/extra-manifests-builder/08-set-rcu-normal/build.sh
  ztp/extra-manifests-builder/08-set-rcu-normal/set-rcu-normal.service
  ztp/extra-manifests-builder/08-set-rcu-normal/set-rcu-normal.sh
  ztp/extra-manifests-builder/08-set-rcu-normal/test.sh
  ztp/source-crs/extra-manifest/08-set-rcu-normal-master.yaml
  ztp/source-crs/extra-manifest/08-set-rcu-normal-worker.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
