Repository openshift-kni/cnf-features-deploy, pull requests merged in 2023-12, with the labels that each got.

#1686 cnf-tests: Increase `ginkgo.timeout`
  hack/run-functests.sh
Labels: approved, lgtm

#1716 ztp: CNF-9171: Update the templated reference configuration to be in line with 4.15 TALM
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-example-multinode-site-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-example-sno-site-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-3node-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-sno-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-standard-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/configMaps/group-hardware-types-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/configMaps/group-zones-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/configMaps/site-data-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/site-du-3nc-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/site-du-multinode-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/site-du-sno-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/site-du-standard-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/kustomization.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/configMaps/group-hardware-types-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/configMaps/group-zones-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/configMaps/site-data-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/example-multinode-site-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/example-sno-site-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-3node-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-standard-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/site-du-3nc-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/site-du-multinode-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/site-du-sno-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/site-du-standard-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
Labels: approved, lgtm, jira/valid-reference

#1723 ztp: Make PG examples more general consistent
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-3node-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-sno-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-standard-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/configMaps/group-hardware-types-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/configMaps/group-hardware-types-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-3node-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-standard-ranGen-templated.yaml
Labels: approved, lgtm

#1725 cnf-tests: bump everything from 4.14 to 4.15
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
Labels: approved, lgtm

#1721 cnf-tests: Remove NTO's 4_latency test suite
  hack/common.sh
Labels: approved, lgtm

#1726 ztp: Add cpuPartitioningMode to site-config-crd
  ztp/ran-crd/site-config-crd.yaml
Labels: approved, lgtm, ok-to-test

#1724 cnf-tests: Set DISCOVERY_MODE to true by default
  cnf-tests/entrypoint/test-run.sh
Labels: approved, lgtm
