Repository openshift-kni/cnf-features-deploy, pull requests merged in 2023-05, with the labels that each got.

#1486 OCPBUGS-12965: ztp: update isRdma to false to match default value suggested in SriovNetworkNodePolicy doc
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1487 ztp: CNF-7722 Fix ordering of common-subscriptions policies
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-ranGen.yaml
Labels: approved, lgtm

#1460 ztp: [CNF-8046] Replacing LVMS source-crs instead of LVMO
  ztp/source-crs/LVMOperatorStatus.yaml
  ztp/source-crs/StorageLVMCluster.yaml
  ztp/source-crs/StorageLVMSubscription.yaml
  ztp/source-crs/StorageLVMSubscriptionNS.yaml
  ztp/source-crs/StorageLVMSubscriptionOperGroup.yaml
Labels: approved, lgtm

#1497 OCPBUGS-13290: ztp: fix annotation name
  ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1494 cnf-tests: Use the built-in oc kustomize
  hack/feature-deploy.sh
Labels: approved, lgtm

#1483 owners: add zeeke in cnf-features-approvers
  OWNERS_ALIASES
Labels: approved, lgtm

#1445 cnf-tests: Avoid clean pods after test in tuningcni tests
  cnf-tests/testsuites/e2esuite/security/tuning.go
  cnf-tests/testsuites/e2esuite/security/tuning_sriov.go
  cnf-tests/testsuites/pkg/features/features.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/utils/reporter.go
Labels: approved, lgtm

#1503 cnf-tests: Use the built-in oc kustomize (4.13 backport)
  hack/feature-deploy.sh
Labels: approved, lgtm

#1499 OCPBUGS-13050: ztp: Update reference configs
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-boundary.yaml
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-boundary.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
  ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
  ztp/source-crs/PtpConfigBoundary.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigMaster.yaml
  ztp/source-crs/PtpConfigSlave.yaml
  ztp/source-crs/PtpConfigSlaveCvl.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1502 Fix default value of the "junit" flag
  cnf-tests/testsuites/e2esuite/junit.xml/cnftests-junit.xml
  cnf-tests/testsuites/e2esuite/test_suite_test.go
Labels: approved, lgtm

#1509 remove runlevel 1
  feature-configs/deploy/sriov/01-sriov-namespace.yaml
  ztp/policygenerator/testData/TestNamespace/sourcePolicies/TestNamespace.yaml
  ztp/policygenerator/testData/TestUnwrappedNamespace/sourcePolicies/TestUnwrappedNamespace.yaml
Labels: approved, lgtm

#1506 OCPBUGS-6763: ztp: Cleanup some source CRs
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/policygenerator/README.md
  ztp/ran-crd/policy-gen-template-ex.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/source-crs/SriovOperatorConfig.yaml
  ztp/source-crs/TunedPerformancePatch.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1498 OCPBUGS-13981: feat: update example to use new cpu partitioning mode
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
Labels: approved, lgtm, ok-to-test, jira/valid-bug, jira/valid-reference

#1500 OCPBUGS-12966: ztp: fix argocd patch volume keys
  ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1481 CNF-8518: ztp: Update DefaultCatSrc with Status and add depreciation warning in the rest of the cat sources
  ztp/policygenerator-kustomize-plugin/README.md
  ztp/source-crs/ClusterLogCatSource.yaml
  ztp/source-crs/DefaultCatsrc.yaml
  ztp/source-crs/PaoSubscriptionCatalogSource.yaml
  ztp/source-crs/PtpCatSource.yaml
  ztp/source-crs/SriovCatSource.yaml
  ztp/source-crs/StorageCatSource.yaml
Labels: approved, lgtm, jira/valid-reference

#1520 CNF-8413: ztp: add annotation in source-cr pp to assist with search
  ztp/source-crs/PerformanceProfile.yaml
Labels: approved, lgtm, jira/valid-reference

#1504 OCPBUGS-13070: set gitOps operator channel
  ztp/gitops-subscriptions/argocd/deployment/openshift-gitops-operator.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference
