Repository openshift-kni/cnf-features-deploy, pull requests merged in 2023-04, with the labels that each got.

#1443 Bump operators 4.14
  cnf-tests/mirror/images.json
  cnf-tests/testsuites/pkg/images/images.go
  feature-configs/deploy/s2i/build-config.yaml
  hack/common.sh
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1451 OCPBUGS-11065: [release-4.13] cnf-tests: sriov-network-operator bump 4.13
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodepolicy_types.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodestate_types.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/network/network.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1432 OCPBUGS-5121: cnf-tests: fix xt_u32 negative test
  cnf-tests/testsuites/e2esuite/xt_u32/xt_u32.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1456 ztp: Add soaking annotation patch to inform validators
  ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
  ztp/policygenerator-kustomize-plugin/kustomization.yaml
Labels: approved, lgtm

#1440 ztp: Add persist storage for cloud events
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/policygenerator-kustomize-plugin/README.md
  ztp/policygenerator-kustomize-plugin/kustomization.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-2-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-ranGen.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/source-crs/StoragePV.yaml
Labels: approved, lgtm

#1458 ztp: OCPBUGS-8718: Unload idrma driver for DU profile
  ztp/source-crs/PerformanceProfile.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1457 ztp: config crun as the default container runtime for 4.13+
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
  ztp/source-crs/optional-extra-manifest/enable-crun-master.yaml
  ztp/source-crs/optional-extra-manifest/enable-crun-worker.yaml
Labels: approved, lgtm

#1062 ztp: add latest label for policies in master branch.
  README.md
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
Labels: approved, lgtm

#1464 [release-4.13] ztp: config crun as the default container runtime for 4.13+
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
  ztp/source-crs/optional-extra-manifest/enable-crun-master.yaml
  ztp/source-crs/optional-extra-manifest/enable-crun-worker.yaml
Labels: approved, lgtm

#1467 ztp: add persist storage for cloud events 4.13
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/policygenerator-kustomize-plugin/README.md
  ztp/policygenerator-kustomize-plugin/kustomization.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-2-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-ranGen.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/source-crs/StoragePV.yaml
Labels: approved, lgtm

#1452 Remove the ptp parallel tests
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  go.mod
  go.sum
  vendor/github.com/creasty/defaults/.gitignore
  vendor/github.com/creasty/defaults/LICENSE
  vendor/github.com/creasty/defaults/Makefile
  vendor/github.com/creasty/defaults/README.md
  vendor/github.com/creasty/defaults/defaults.go
  vendor/github.com/creasty/defaults/setter.go
  vendor/github.com/openshift/ptp-operator/test/conformance/config/ptptestconfig.go
  vendor/github.com/openshift/ptp-operator/test/conformance/config/ptptestconfig.yaml
  vendor/github.com/openshift/ptp-operator/test/conformance/parallel/ptp.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#1341 OCPBUGS-4378: Fix the hwlatdetect default window duration
  cnf-tests/pod-utils/hwlatdetect-runner/main.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#1436 infra: added github configuration file for dependabot with commit prefix
  .githooks/components.sh
  .github/dependabot.yml
  ztp/resource-generator/tools/cachito/build_requirements.in
  ztp/resource-generator/tools/cachito/build_requirements.txt
  ztp/resource-generator/tools/cachito/requirements.in
  ztp/resource-generator/tools/cachito/requirements.txt
  ztp/resource-generator/tools/cachito/setup.cfg
Labels: approved, lgtm

#1454 ztp: CNF-7798: git-first-search-path-for-ztp
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilderOverlay_test.go
  ztp/policygenerator/utils/filesHandler.go
Labels: approved, lgtm, jira/valid-reference
