Repository openshift-kni/cnf-features-deploy, pull requests merged in 2023-02, with the labels that each got.

#1389 cnf-tests: multinetworkpolicy typo fix in validationsuit
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/validation.json
  cnf-tests/testsuites/validationsuite/cluster/validation.go
Labels: approved, lgtm

#1393 infra: Update openshift-ci base image to fedora 37
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#1391 ztp: Add workloadHints to source-crs/PerformanceProfile
  ztp/source-crs/PerformanceProfile.yaml
Labels: approved, lgtm

#1392 Add bartwensley to cnf-features-reviewers
  OWNERS_ALIASES
Labels: approved, lgtm, ok-to-test

#1387 ztp: CNF-7061: add crio wipe disable to reference configuration
  ztp/extra-manifests-builder/99-crio-disable-wipe/build.sh
  ztp/extra-manifests-builder/99-crio-disable-wipe/crio-disable-wipe.toml
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/source-crs/extra-manifest/99-crio-disable-wipe-master.yaml
  ztp/source-crs/extra-manifest/99-crio-disable-wipe-worker.yaml
Labels: approved, lgtm, jira/valid-reference

#1395 ztp: Add documentation for configuring power modes with ztp
  ztp/gitops-subscriptions/argocd/PowerConfiguration.md
Labels: approved, lgtm

#1394 infra: bump golang to 1.19 on openshift-ci image
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  go.mod
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#1403 ztp: Make formatting compatible with golang1.19
  cnf-tests/testsuites/e2esuite/multinetworkpolicy/reachmatcher.go
  cnf-tests/testsuites/e2esuite/ovs_qos/ovs_qos.go
  cnf-tests/testsuites/pkg/pods/pods.go
  ztp/policygenerator/policyGen/policyHelper.go
Labels: approved, lgtm

#1404 Add ACM policyGenerator to ArgoCD ZTP workflow
  ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json
  ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
Labels: approved, lgtm

#1402 ztp: remove systemd from accelerated-container-startup
  ztp/extra-manifests-builder/04-accelerated-container-startup/accelerated-container-startup.sh
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-master.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-worker.yaml
Labels: approved, lgtm

#1266 cnf-tests: allocate more dpdknic res in vhostnet
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm

#1406 infra: Hide podman login in logs to prevent password leaks
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1409 Revert "Add ACM policyGenerator to ArgoCD ZTP workflow"
  ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json
  ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
Labels: approved, lgtm

#1408 ztp: Add ts2phc configuration to new ptpconfig
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm

#1412 ztp: Add NodeTuning operator to installConfigOverrides for 4.13
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
Labels: approved, lgtm

#1413 cnf-tests: Fix the JUnit reporter
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/docgen/validation.json
  cnf-tests/hack/build-test-bin.sh
  cnf-tests/testsuites/configsuite/test_suite_test.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/validationsuite/test_suite_test.go
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/core_dsl.go
  vendor/github.com/onsi/ginkgo/v2/ginkgo_cli_dependencies.go
  vendor/github.com/onsi/ginkgo/v2/reporters/junit_report.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/have_exact_elements.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/modules.txt
Labels: approved, lgtm, needs-ok-to-test

#1414 ztp: Only provide composable openshift examples for SNO clusters
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
Labels: approved, lgtm
