Repository openshift-kni/cnf-features-deploy, pull requests merged in 2023-03, with the labels that each got.

#1415 [release-4.12] OCPBUGS-5380: ztp: remove systemd from accelerated-container-startup
  ztp/extra-manifests-builder/04-accelerated-container-startup/accelerated-container-startup.sh
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-master.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-worker.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1401 owners: Add Sharat Akhoury to review and approval list for ZTP and RAN
  OWNERS_ALIASES
Labels: approved, lgtm

#1418 ztp: Update ice-gnss tuning to SCHED_FIFO 10
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-1-ranGen.yaml
  ztp/source-crs/TunedPerformancePatch.yaml
Labels: approved, lgtm

#1422 OCPBUGS-7652: ztp: add patch in deployment directory to remove cluster-proxy-addon
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/deployment/disable-cluster-proxy-addon.json
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1426 [release-4.10] OCPBUGS-8527: ztp: Remove ovs from accelerated-container-startup
  ztp/extra-manifests-builder/04-accelerated-container-startup/accelerated-container-startup.sh
  ztp/extra-manifests-builder/04-accelerated-container-startup/test.sh
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-master.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-worker.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1431 OCPBUGS-8238: ztp: Remove incorrect macAddress field
  ztp/gitops-subscriptions/argocd/SNOExpansion.md
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
  ztp/ran-crd/site-config-cr-ex.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-expansion.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-sno-du.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-standard-du.yaml
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1312 Add a holdInstallation flag to SiteConfig
  ztp/ran-crd/site-config-crd.yaml
  ztp/siteconfig-generator/siteConfig/clusterCRs.go
  ztp/siteconfig-generator/siteConfig/siteConfig.go
Labels: approved, lgtm, ok-to-test

#1411 ztp: Add ACM policyGenerator to ArgoCD ZTP workflow
  ztp/gitops-subscriptions/argocd/deployment/argocd-openshift-gitops-patch.json
  ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
Labels: approved, lgtm

#1435 OCPBUGS 7464: ztp: Comment out workloadHints in ZTP 4.13
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/source-crs/PerformanceProfile.yaml
Labels: approved, lgtm

#1438 ztp: Add one-shot time sync on boot
  ztp/extra-manifests-builder/99-sync-time-once/build.sh
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/source-crs/extra-manifest/99-sync-time-once-master.yaml
  ztp/source-crs/extra-manifest/99-sync-time-once-worker.yaml
Labels: approved, lgtm

#1420 Update references to `networks-status`
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/multinetworkpolicy/reachmatcher.go
Labels: approved, lgtm

#1448 OCPBUGS-9272: ztp: validate disk partitioning is applied only for SNO
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfig_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#1442 [release-4.13] Bump operators 4.13
  cnf-tests/mirror/images.json
  cnf-tests/testsuites/pkg/images/images.go
  feature-configs/deploy/s2i/build-config.yaml
  hack/common.sh
  hack/run-functests.sh
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1450 cnf-tests: sriov-network-operator bump 4.14
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodepolicy_types.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodestate_types.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/conformance/tests/test_sriov_operator.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/client/clients.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/discovery/discovery.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/namespaces/namespaces.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/network/network.go
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/nodes/nodes.go
  vendor/modules.txt
Labels: approved, lgtm
