Repository openshift-kni/cnf-features-deploy, pull requests merged in 2023-06, with the labels that each got.

#1514 OCPBUGS-9413: ztp: remove the deprecated curation section from ClusterLogging CR
  feature-configs/5g-ref-nw/clusters/otwaon34567sno/nw-config/logging/README.md
  feature-configs/5g-ref-nw/profile-base/sno-general/cluster-logging.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/policygenerator/README.md
  ztp/ran-crd/policy-gen-template-ex.yaml
  ztp/source-crs/ClusterLogging.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#1513 s2i: bump dpdk s2i to centos stream 9 and dpdk version 22.11.2
  tools/s2i-dpdk/Dockerfile
Labels: approved, lgtm

#1519 CNF-8619: ztp: diff acm's polcies with pgt's polcies
  go.mod
  go.sum
  vendor/github.com/shopspring/decimal/.gitignore
  vendor/github.com/shopspring/decimal/.travis.yml
  vendor/github.com/shopspring/decimal/CHANGELOG.md
  vendor/github.com/shopspring/decimal/README.md
  vendor/github.com/shopspring/decimal/decimal.go
  vendor/github.com/shopspring/decimal/rounding.go
  vendor/modules.txt
  vendor/open-cluster-management.io/config-policy-controller/LICENSE
  vendor/open-cluster-management.io/config-policy-controller/api/v1/configurationpolicy_types.go
  vendor/open-cluster-management.io/config-policy-controller/api/v1/groupversion_info.go
  vendor/open-cluster-management.io/config-policy-controller/api/v1/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/governance-policy-propagator/LICENSE
  vendor/open-cluster-management.io/governance-policy-propagator/api/v1/groupversion_info.go
  vendor/open-cluster-management.io/governance-policy-propagator/api/v1/placementbinding_types.go
  vendor/open-cluster-management.io/governance-policy-propagator/api/v1/policy_types.go
  vendor/open-cluster-management.io/governance-policy-propagator/api/v1/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/multicloud-operators-subscription/LICENSE
  vendor/open-cluster-management.io/multicloud-operators-subscription/pkg/apis/apps/placementrule/v1/doc.go
  vendor/open-cluster-management.io/multicloud-operators-subscription/pkg/apis/apps/placementrule/v1/placementrule_types.go
  vendor/open-cluster-management.io/multicloud-operators-subscription/pkg/apis/apps/placementrule/v1/register.go
  vendor/open-cluster-management.io/multicloud-operators-subscription/pkg/apis/apps/placementrule/v1/zz_generated.deepcopy.go
  ztp/tools/policy-object-template-diff/Makefile
  ztp/tools/policy-object-template-diff/README.md
  ztp/tools/policy-object-template-diff/main.go
  ztp/tools/policy-object-template-diff/override/PerformanceProfile.yaml
  ztp/tools/policy-object-template-diff/override/PtpConfig.yaml
  ztp/tools/policy-object-template-diff/override/SriovNetworkNodePolicy.yaml
  ztp/tools/policy-object-template-diff/override/SriovOperatorConfig.yaml
  ztp/tools/policy-object-template-diff/override/Tuned.yaml
Labels: approved, lgtm, jira/valid-reference

#1533 ztp: Expose disk cleaning option through SiteConfig
  ztp/ran-crd/site-config-crd.yaml
  ztp/siteconfig-generator/siteConfig/clusterCRs.go
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigHelper_test.go
  ztp/siteconfig-generator/siteConfig/siteConfig_test.go
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badAnnotation.yaml
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badName.yaml
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badNamespace.yaml
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride.yaml
Labels: approved, lgtm

#1528 OCPBUGS-14511: ztp: disable OLM pprof collection on SNO
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/source-crs/DisableOLMPprof.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1516 s2i: add capabilities on testpmd and testbbdev bins
  tools/s2i-dpdk/Dockerfile
Labels: approved, lgtm, ok-to-test

#1531 ztp: copy source-crs in current working directory to mimic git behavior in Makefile
  ztp/policygenerator-kustomize-plugin/Makefile
Labels: approved, lgtm

#1536 CNF-8672: ztp: Exclude builtin CRs in siteconfig and only include custom extra manifest from searchPaths
  ztp/gitops-subscriptions/argocd/ExtraManifestsFilter.md
  ztp/gitops-subscriptions/argocd/README.md
  ztp/ran-crd/site-config-crd.yaml
  ztp/siteconfig-generator-kustomize-plugin/kustomization.yaml
  ztp/siteconfig-generator/siteConfig/filesHandler.go
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
Labels: approved, lgtm, jira/valid-reference

#1482 CNF-7424: Add ACM policy generator examples
  ztp/.gitignore
  ztp/Makefile
  ztp/gitops-subscriptions/Makefile
  ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/README.md
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-multinode-site.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-3node-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-standard-validator-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/kustomization.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/ns.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
  ztp/source-crs/ClusterLogForwarder.yaml
  ztp/source-crs/ClusterLogging.yaml
  ztp/source-crs/DisconnectedICSP.yaml
  ztp/source-crs/PerformanceProfile-SetSelector.yaml
  ztp/source-crs/PtpOperatorConfig-SetSelector.yaml
  ztp/source-crs/PtpOperatorConfigForEvent-SetSelector.yaml
  ztp/source-crs/SriovNetwork.yaml
  ztp/source-crs/SriovNetworkNodePolicy-SetSelector.yaml
  ztp/source-crs/SriovOperatorConfig-SetSelector.yaml
  ztp/source-crs/validatorCRs/informDuValidatorMaster.yaml
  ztp/source-crs/validatorCRs/informDuValidatorWorker.yaml
  ztp/tools/policy-object-template-diff/Makefile
Labels: approved, lgtm, jira/valid-reference

#1526 OCPBUGS-3513: use manifestsConfigMapRefs
  ztp/siteconfig-generator/siteConfig/clusterCRs.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#1545 Revert "ztp: copy source-crs in current working directory to mimic git behavior in Makefile"
  ztp/policygenerator-kustomize-plugin/Makefile
Labels: approved, lgtm
