Repository openshift-kni/cnf-features-deploy, pull requests merged in 2023-11, with the labels that each got.

#1679 cnf-tests: Increase delay in WaitStable
  cnf-tests/testsuites/pkg/networks/sriov.go
Labels: approved, lgtm

#1646 ztp: CNF-9171: DU reference config with hub side templating
  ztp/gitops-subscriptions/argocd/example/README.md
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-example-multinode-site-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-example-sno-site-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-3node-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-sno-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-standard-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/site-du-3nc-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/site-du-multinode-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/site-du-sno-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/site-du-standard-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/kustomization.yaml
  ztp/gitops-subscriptions/argocd/example/configuration-groups.md
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/example-multinode-site-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/example-sno-site-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-3node-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-standard-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/site-du-3nc-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/site-du-multinode-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/site-du-sno-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/site-du-standard-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
Labels: approved, lgtm, jira/valid-reference

#1693 OCPBUGS-22812: ztp: Enable newly required OperatorLifecycleManager capability for 4.15
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1694 ztp: Add V2 to the SiteConfig CRD
  ztp/ran-crd/site-config-crd.yaml
Labels: approved, lgtm

#1677 ztp: CNF-9171: siteconfig-generator: generate new ConfigMap
  ztp/ran-crd/site-config-crd.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/siteconfig-generator/siteConfig/clusterCRsV2.go
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/siteConfig_test.go
  ztp/siteconfig-generator/siteConfig/testdata/ConfigMapOverride-AddAnnotations.yaml
  ztp/siteconfig-generator/siteConfig/testdata/ConfigMapOverride-OverrideSiteConfigMap.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigV2TestOutput.yaml
Labels: approved, lgtm, jira/valid-reference

#1678 ztp: CNF-10088 container image updated to rhel9
  ztp/resource-generator/Containerfile
Labels: approved, lgtm

#1698 ztp: OCPBUGS-21740: fix sync-time-once / chronyd contention
  ztp/extra-manifests-builder/99-sync-time-once/build.sh
  ztp/source-crs/extra-manifest/99-sync-time-once-master.yaml
  ztp/source-crs/extra-manifest/99-sync-time-once-worker.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1702 ztp: remove chrony sync ExecCondition sleep
  ztp/extra-manifests-builder/99-sync-time-once/build.sh
  ztp/source-crs/extra-manifest/99-sync-time-once-master.yaml
  ztp/source-crs/extra-manifest/99-sync-time-once-worker.yaml
Labels: approved, lgtm

#1706 cnf-tests: Add +x permissions to test-run.sh
  cnf-tests/entrypoint/test-run.sh
Labels: approved, lgtm

#1689 cnf-tests: look for suitable node for SRIOV/NUMA
  cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
Labels: approved, lgtm

#1691 cnf-tests: Multinetwork Policy IPv6
  cnf-tests/testsuites/e2esuite/multinetworkpolicy/multinetworkpolicy_sriov.go
Labels: approved, lgtm

#1709 ztp: Cleanup hub templating to better match non templated examples
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-3node-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-sno-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-standard-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/kustomization.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-3node-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-standard-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
Labels: approved, lgtm

#1704 ztp: Notes added to reflect on new midstream info in the containerFile
  ztp/resource-generator/Containerfile
Labels: approved, lgtm

#1710 cnf-test: Fix `ncat` timeout error message
  cnf-tests/testsuites/e2esuite/multinetworkpolicy/reachmatcher.go
Labels: approved, lgtm

#1696 OCPBUGS-23425: Bump Go to v1.19 in release-4.12
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
  ztp/resource-generator/Containerfile
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
