Repository openshift-kni/cnf-features-deploy, pull requests merged in 2023-07, with the labels that each got.

#1549 OCPBUGS-15470: Fix PCI addr calculation in DPDK tests
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1525 vendor: bump NTO dependencies 20230606
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/configs/01-use-ovs-slice.conf
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/configs/99-default-rps-mask.conf
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/configs/99-netdev-physical-rps.rules
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/configs/ovs-enable-dynamic-cpu-affinity
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/configs/ovs.slice
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/scripts/cpuset-configure.sh
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/tuned/openshift-node-performance
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/tuned_types.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/0_config/config.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/performance.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/4_latency/latency.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/utils/pods/pods.go
  vendor/modules.txt
Labels: approved, lgtm

#1546 CNF-7818: ztp: Uncomment workloadHints object in PerformanceProfile
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/source-crs/PerformanceProfile-SetSelector.yaml
  ztp/source-crs/PerformanceProfile.yaml
Labels: approved, lgtm, jira/valid-reference

#1542 ztp: rename DefaultCatsrc to inform that CR is for disconnected env and update all subscriptions
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/source-crs/AmqSubscription.yaml
  ztp/source-crs/BareMetalEventRelaySubscription.yaml
  ztp/source-crs/ClusterLogSubscription.yaml
  ztp/source-crs/PaoSubscription.yaml
  ztp/source-crs/PtpSubscription.yaml
  ztp/source-crs/SriovSubscription.yaml
  ztp/source-crs/StorageLVMOSubscription.yaml
  ztp/source-crs/StorageLVMSubscription.yaml
  ztp/source-crs/StorageSubscription.yaml
Labels: approved, lgtm

#1551 [release-4.12] OCPBUGS-15912: ztp: disable OLM pprof collection on SNO
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/source-crs/DisableOLMPprof.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1558 OCPBUGS-16094: Revert "OCPBUGS-3513: use manifestsConfigMapRefs "
  ztp/siteconfig-generator/siteConfig/clusterCRs.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1560 Bug OCPBUGS-14921: ztp: Use HTTP as default transport for cloud events
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/source-crs/HardwareEvent.yaml
  ztp/source-crs/PtpOperatorConfigForEvent-SetSelector.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1567 ztp: use extra manifest copy when testing
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
Labels: approved, lgtm

#1554 ztp: Add ublx commands to example wpc config
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm

#1561 OCPBUGS-13634: ztp: remove accelerated container startup
  ztp/extra-manifests-builder/04-accelerated-container-startup/README.md
  ztp/extra-manifests-builder/04-accelerated-container-startup/accelerated-container-shutdown.service
  ztp/extra-manifests-builder/04-accelerated-container-startup/accelerated-container-startup.service
  ztp/extra-manifests-builder/04-accelerated-container-startup/accelerated-container-startup.sh
  ztp/extra-manifests-builder/04-accelerated-container-startup/build.sh
  ztp/extra-manifests-builder/04-accelerated-container-startup/test.sh
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/siteconfig-generator-kustomize-plugin/README.md
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-master.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-worker.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1565 ztp: Include SR-IOV-related kernel command-line arguments on day-0
  ztp/extra-manifests-builder/07-sriov-related-kernel-args/build.sh
  ztp/source-crs/extra-manifest/07-sriov-related-kernel-args-master.yaml
  ztp/source-crs/extra-manifest/07-sriov-related-kernel-args-worker.yaml
Labels: approved, lgtm

#1568 CNF-8851: ztp: Create warning for deprecated field: extraManifestPath
  ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml
Labels: approved, lgtm, jira/valid-reference

#1569 ztp: CNF-9146: Directly enable pins for WPC
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-reference

#1578 OCPBUGS-16649: Accelerated startup cleanup
  ztp/extra-manifests-builder/04-accelerated-container-startup/accelerated-container-startup.sh
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-master.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-worker.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1571 OCPBUGS-16362: ztp: cherry-pick reference config changes to 4.12
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-boundary.yaml
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-grandmaster.yaml
  feature-configs/5g-ref-nw/profile-base/du-general/ptp/ptpconfig-slave.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-boundary.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-grandmaster.yaml
  feature-configs/cn-ran-overlays/ran-profile/cluster-config/du-common/ptp/ptpconfig-slave.yaml
  ztp/policygenerator/testData/TestPtpConfig/sourcePolicies/TestPtpConfig.yaml
  ztp/source-crs/PtpConfigBoundary.yaml
  ztp/source-crs/PtpConfigMaster.yaml
  ztp/source-crs/PtpConfigSlave.yaml
  ztp/source-crs/PtpConfigSlaveCvl.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1557 SRIOV ExcludeTopology tests
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
  cnf-tests/testsuites/pkg/performanceprofile/performanceprofile.go
  cnf-tests/testsuites/pkg/pods/pods.go
Labels: approved, lgtm

#1574 [release-4.13] Bug OCPBUGS-16627: ztp: Use HTTP as default transport for cloud events
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/source-crs/HardwareEvent.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1580 [release-4.12] Bug OCPBUGS-16782: ztp: Use HTTP as default transport for cloud events
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/source-crs/HardwareEvent.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
