Repository openshift-kni/cnf-features-deploy, pull requests merged in 2024-04, with the labels that each got.

#1845 ztp: Add IPSec N-S configuration
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/source-crs/optional-extra-manifest/ipsec/README.md
  ztp/source-crs/optional-extra-manifest/ipsec/build.sh
  ztp/source-crs/optional-extra-manifest/ipsec/enable-ipsec.yaml
  ztp/source-crs/optional-extra-manifest/ipsec/ipsec-endpoint-config.yml
Labels: approved, lgtm, ok-to-test

#1864 OCPBUGS-31496: ztp: start chrony after network online
  ztp/extra-manifests-builder/99-sync-time-once/build.sh
  ztp/source-crs/extra-manifest/99-sync-time-once-master.yaml
  ztp/source-crs/extra-manifest/99-sync-time-once-worker.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1862 Retry BeforeAll when initial setup fails
  cnf-tests/testsuites/pkg/execute/ginkgo.go
Labels: approved, lgtm

#1852 ztp: OCPBUGS-31325: Backport fix to disable rcu_expedited after node recovers from reboot
  ztp/extra-manifests-builder/04-accelerated-container-startup/README.md
  ztp/extra-manifests-builder/04-accelerated-container-startup/accelerated-container-startup.sh
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-master.yaml
  ztp/source-crs/extra-manifest/04-accelerated-container-startup-worker.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1817 ztp: Downgrade MCO to an ignition version v3.2.0
  go.mod
  go.sum
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/types.go
  vendor/github.com/openshift/machine-config-operator/pkg/controller/common/constants.go
  vendor/github.com/openshift/machine-config-operator/pkg/controller/common/helpers.go
  vendor/github.com/openshift/machine-config-operator/pkg/controller/common/layered_node_state.go
  vendor/github.com/openshift/machine-config-operator/pkg/controller/common/layered_pool_state.go
  vendor/k8s.io/apiserver/pkg/features/OWNERS
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/credentialprovider/OWNERS
  vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/doc.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/keyring.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/plugins.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/provider.go
  vendor/k8s.io/kubernetes/pkg/features/OWNERS
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/siteConfigHelper_test.go
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/01-predefined-mc-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/01-predefined-mc-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/image-registry-partition-mc.yaml.tmpl
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/workload/03-workload-partitioning.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutputWithZap.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigV2TestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/01-container-mount-ns-and-kubelet-conf-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/01-container-mount-ns-and-kubelet-conf-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/04-accelerated-container-startup-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/04-accelerated-container-startup-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/06-kdump-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/06-kdump-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/disk-encryption.yaml.tmpl
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/image-registry-partition-mc.yaml.tmpl
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/workload/03-workload-partitioning.yaml
Labels: approved, lgtm

#1870 ztp: CNF-10965: Remove cgroups v1 enablement
  ztp/source-crs/extra-manifest/enable-cgroups-v1.yaml
Labels: approved, lgtm, jira/valid-reference

#1867 ztp: CNF-9536: Update reference SiteConfig to use rootDeviceHints wit…
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
  ztp/ran-crd/site-config-cr-ex.yaml
  ztp/ran-crd/site-config-crd.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-expansion.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-sno-du.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-standard-du.yaml
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/siteConfig_test.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigV2TestOutput.yaml
Labels: approved, lgtm, jira/valid-reference

#1863 ztp: CNF-9975: Update readmes
  ztp/gitops-subscriptions/argocd/DiskPartitionContainers.md
  ztp/gitops-subscriptions/argocd/ImageRegistry.md
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/SNOExpansion.md
  ztp/gitops-subscriptions/argocd/Upgrade.md
  ztp/gitops-subscriptions/argocd/deployment/openshift-gitops-operator.yaml
Labels: approved, lgtm, jira/valid-reference

#1853 ztp: ptp add ptpconfig for High Availability
  ztp/source-crs/PtpConfigForHA.yaml
Labels: approved, lgtm

#1869 ztp: CNF-11960: remove kernel timer migration
  ztp/source-crs/TunedPerformancePatch.yaml
Labels: approved, lgtm, jira/valid-reference

#1873 ztp: add disableDrain true in ztp
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/source-crs/SriovOperatorConfigForSNO.yaml
Labels: approved, lgtm

#1878 [release-4.14] CNF-12187: Support node deletion using ZTP
  ztp/gitops-subscriptions/argocd/WorkerNodeDeletion.md
  ztp/ran-crd/site-config-crd.yaml
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
Labels: approved, lgtm, jira/valid-reference

#1882 ztp: OCPBUGS-32039: Siteconfig blocks MNO cluster deployment for more or less than 3 master nodes
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfig_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1883 OCPBUGS-32771: ztp: update the default PlatformBackupRestore CR
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/README.md
  ztp/source-crs/ibu/PlatformBackupRestore.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1786 [release-4.14] tools: Add HTML converting to code and make true by default
  Makefile
  cnf-tests/testsuites/pkg/j2html/j2html.go
  hack/common.sh
  hack/run-functests.sh
Labels: approved, lgtm

#1812 cnf-tests: Deprecate k8s.io/utils pointer function
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/vrf/vrf.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/pods/pods.go
Labels: approved, lgtm, ok-to-test

#1880 ztp: cnf-7840: Allow ClusterImageSet to be synced
  ztp/gitops-subscriptions/argocd/deployment/app-project.yaml
Labels: approved, lgtm, jira/valid-reference

#1888 ztp: Add IBU platform OADP backup and restore CRs for LVMS
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/README.md
  ztp/source-crs/ibu/PlatformBackupRestoreLvms.yaml
Labels: approved, lgtm, ok-to-test

#1872 cnf-tests: Delete macvlan nad to retry allowlist test
  cnf-tests/testsuites/e2esuite/security/tuning.go
Labels: approved, lgtm
