Repository openshift-kni/cnf-features-deploy, pull requests merged in 2024-10, with the labels that each got.

#2052 OCPBUGS-39149: ztp: empty file in sitegen kustomize plugin
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/testUserExtraManifest/00-emptymanifest.yaml
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2058 ztp: update ptpEventConfig.apiVersion
  ztp/kube-compare-reference/optional/ptp-config/PtpOperatorConfigForEvent.yaml
  ztp/source-crs/PtpOperatorConfigForEvent-SetSelector.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm

#2055 ztp: Added compare script to compare rendered CRs with source-crs
  ztp/kube-compare-reference/Makefile
  ztp/kube-compare-reference/compare.sh
  ztp/kube-compare-reference/default_value.yaml
Labels: approved, lgtm, ok-to-test

#2062 CNF-14780: fix ptp templates
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-standard-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
Labels: approved, lgtm, jira/valid-reference

#2053 OCPBUGS-42750: Support upgrade from Cluster Logging 5.x to 6.0
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/README.md
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-clo5-cleanup.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/kustomization.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-clo5-cleanup-policy.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogForwarder.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogServiceAccount.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogServiceAccountAuditBinding.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogServiceAccountInfrastructureBinding.yaml
  ztp/source-crs/ClusterLogForwarder.yaml
  ztp/source-crs/ClusterLogServiceAccount.yaml
  ztp/source-crs/ClusterLogServiceAccountAuditBinding.yaml
  ztp/source-crs/ClusterLogServiceAccountInfrastructureBinding.yaml
  ztp/source-crs/ClusterLogging5Cleanup.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2065 CNF-14818: reference sync
  ztp/kube-compare-reference/.gitignore
  ztp/kube-compare-reference/compare.sh
  ztp/kube-compare-reference/optional/console-disable/ConsoleOperatorDisable.yaml
  ztp/kube-compare-reference/optional/image-registry/ImageRegistryConfig.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageClass.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageLV.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageNS.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageOperGroup.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageSubscription.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHA.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpOperatorConfig.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpOperatorConfigForEvent.yaml
  ztp/kube-compare-reference/optional/sriov-fec-operator/AcceleratorsNS.yaml
  ztp/kube-compare-reference/optional/sriov-fec-operator/AcceleratorsOperGroup.yaml
  ztp/kube-compare-reference/optional/sriov-fec-operator/AcceleratorsSubscription.yaml
  ztp/kube-compare-reference/optional/sriov-fec-operator/SriovFecClusterConfig.yaml
  ztp/kube-compare-reference/optional/storage/StorageLV.yaml
  ztp/kube-compare-reference/optional/storage/StorageLVMCluster.yaml
  ztp/kube-compare-reference/optional/storage/StorageLVMSubscription.yaml
  ztp/kube-compare-reference/optional/storage/StorageLVMSubscriptionNS.yaml
  ztp/kube-compare-reference/optional/storage/StorageLVMSubscriptionOperGroup.yaml
  ztp/kube-compare-reference/optional/storage/StoragePV.yaml
  ztp/kube-compare-reference/optional/storage/StoragePVC.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogForwarder.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogNS.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogOperGroup.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogServiceAccount.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogServiceAccountAuditBinding.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogServiceAccountInfrastructureBinding.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogSubscription.yaml
  ztp/kube-compare-reference/required/cluster-tuning/DisableOLMPprof.yaml
  ztp/kube-compare-reference/required/cluster-tuning/disabling-network-diagnostics/DisableSnoNetworkDiag.yaml
  ztp/kube-compare-reference/required/cluster-tuning/monitoring-configuration/ReduceMonitoringFootprint.yaml
  ztp/kube-compare-reference/required/cluster-tuning/operator-hub/DefaultCatsrc.yaml
  ztp/kube-compare-reference/required/cluster-tuning/operator-hub/DisconnectedICSP.yaml
  ztp/kube-compare-reference/required/cluster-tuning/operator-hub/OperatorHub.yaml
  ztp/kube-compare-reference/required/lca/LcaSubscription.yaml
  ztp/kube-compare-reference/required/lca/LcaSubscriptionNS.yaml
  ztp/kube-compare-reference/required/lca/LcaSubscriptionOperGroup.yaml
  ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml
  ztp/kube-compare-reference/required/node-tuning-operator/TunedPerformancePatch.yaml
  ztp/kube-compare-reference/required/ptp-operator/PtpSubscription.yaml
  ztp/kube-compare-reference/required/ptp-operator/PtpSubscriptionNS.yaml
  ztp/kube-compare-reference/required/ptp-operator/PtpSubscriptionOperGroup.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovNetwork.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovNetworkNodePolicy.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfig.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfigForSNO.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovSubscription.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovSubscriptionNS.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovSubscriptionOperGroup.yaml
Labels: approved, lgtm, jira/valid-reference

#2057 ztp: CNF-14762: add vrb2 and update refs
  ztp/source-crs/SriovFecClusterConfig.yaml
  ztp/source-crs/SriovVrbClusterConfig.yaml
Labels: approved, lgtm, jira/valid-reference

#2066 CNF-14818: sync quotes, comments, and whitespace between references and source-crs
  ztp/kube-compare-reference/Makefile
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/optional/image-registry/ImageRegistryConfig.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageLV.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpOperatorConfigForEvent.yaml
  ztp/kube-compare-reference/optional/sriov-fec-operator/AcceleratorsOperGroup.yaml
  ztp/kube-compare-reference/optional/sriov-fec-operator/AcceleratorsSubscription.yaml
  ztp/kube-compare-reference/optional/sriov-fec-operator/SriovFecClusterConfig.yaml
  ztp/kube-compare-reference/optional/storage/StorageLVMCluster.yaml
  ztp/kube-compare-reference/optional/storage/StorageLVMSubscriptionNS.yaml
  ztp/kube-compare-reference/optional/storage/StoragePV.yaml
  ztp/kube-compare-reference/optional/storage/StoragePVC.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogForwarder.yaml
  ztp/kube-compare-reference/required/cluster-tuning/operator-hub/DisconnectedICSP.yaml
  ztp/kube-compare-reference/required/node-tuning-operator/TunedPerformancePatch.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovNetwork.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfigForSNO.yaml
  ztp/source-crs/AcceleratorsOperGroup.yaml
  ztp/source-crs/AcceleratorsSubscription.yaml
  ztp/source-crs/ClusterLogForwarder.yaml
  ztp/source-crs/ClusterLogNS.yaml
  ztp/source-crs/ClusterLogOperGroup.yaml
  ztp/source-crs/DisconnectedICSP.yaml
  ztp/source-crs/ImageRegistryConfig.yaml
  ztp/source-crs/OperatorHub.yaml
  ztp/source-crs/PerformanceProfile.yaml
  ztp/source-crs/PtpConfigBoundary.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigForHA.yaml
  ztp/source-crs/PtpConfigForHAForEvent.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigMaster.yaml
  ztp/source-crs/PtpConfigMasterForEvent.yaml
  ztp/source-crs/PtpConfigSlave.yaml
  ztp/source-crs/PtpConfigSlaveCvl.yaml
  ztp/source-crs/PtpConfigSlaveForEvent.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
  ztp/source-crs/PtpSubscription.yaml
  ztp/source-crs/PtpSubscriptionNS.yaml
  ztp/source-crs/SriovFecClusterConfig.yaml
  ztp/source-crs/SriovNetwork.yaml
  ztp/source-crs/SriovNetworkNodePolicy.yaml
  ztp/source-crs/SriovOperatorConfig.yaml
  ztp/source-crs/SriovOperatorConfigForSNO.yaml
  ztp/source-crs/StorageLV.yaml
  ztp/source-crs/StorageLVMCluster.yaml
  ztp/source-crs/StoragePVC.yaml
  ztp/source-crs/TunedPerformancePatch.yaml
Labels: approved, lgtm, jira/valid-reference, ztp/reference

#2059 Build-in the RAN reference to the ZTP container
  ztp/resource-generator/Containerfile
Labels: approved, lgtm

#2068 CNF-14817: Cleanup PTP reference files
  ztp/kube-compare-reference/compare_ignore
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveCvl.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-reference, ztp/reference

#2072 CNF-14990: Fix gimme golang install for go > 1.20
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, jira/valid-reference

#2075 infra: Fix gimme version (again...)
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#2076 OCPBUGS-43574: ztp: Fix kube compare unordered list
  ztp/kube-compare-reference/unordered_list.tmpl
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2070 CNF-14823: Enforce reference and source-crs synchronization via CI
  ztp/kube-compare-reference/Makefile
  ztp/kube-compare-reference/README.md
  ztp/kube-compare-reference/compare.sh
Labels: approved, lgtm, jira/valid-reference, ztp/reference

#2071 [release-4.16] OCPBUGS-42441 ztp: add ptpEventConfig.apiVersion in PtpOperatorConfig
  ztp/source-crs/PtpOperatorConfigForEvent-SetSelector.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm

#2078 CNF-15050: ztp: Remove ztp-deploy-wave number from validator source crs for ACM PGs
  ztp/source-crs/validatorCRs/informDuValidatorMaster.yaml
  ztp/source-crs/validatorCRs/informDuValidatorWorker.yaml
Labels: approved, lgtm, jira/valid-reference

#1990 CNF-13652: Test integration of SRIOV and NMState operators
  Makefile
  cnf-tests/testsuites/e2esuite/knmstate/knmstate_sriov.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/pkg/client/clients.go
  feature-configs/ci/knmstate/kustomization.yaml
  feature-configs/ci/knmstate/operator_subscription.yaml
  feature-configs/deploy/knmstate/kustomization.yaml
  feature-configs/deploy/knmstate/operator_namespace.yaml
  feature-configs/deploy/knmstate/operator_operatorgroup.yaml
  feature-configs/deploy/knmstate/operator_subscription.yaml
  go.mod
  go.sum
  hack/setup-build-index-image.sh
  vendor/github.com/nmstate/kubernetes-nmstate/api/LICENSE
  vendor/github.com/nmstate/kubernetes-nmstate/api/names/names.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/condition_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkconfigurationenactment_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkstate_util.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/state_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/zz_generated.deepcopy.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/groupversion_info.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nmstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/zz_generated.deepcopy.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/groupversion_info.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/nmstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/nodenetworkconfigurationenactment_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/nodenetworkstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#2077 ztp: CNF-14991: Fix instability in policy-generator-plugin usage
  ztp/tools/pgt2acmpg/.gitignore
  ztp/tools/pgt2acmpg/scripts/build-acmpg-plugin.sh
Labels: approved, lgtm, jira/valid-reference

#2087 CNF-13527: Enforce cluster version for this reference to be 4.18
  ztp/kube-compare-reference/ClusterVersionOperator.yaml
  ztp/kube-compare-reference/compare_ignore
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/version_match.tmpl
Labels: approved, lgtm, jira/valid-reference, ztp/reference

#2089 CNF-15048: Enforce cluster version for this reference to be 4.17
  ztp/kube-compare-reference/ClusterVersionOperator.yaml
  ztp/kube-compare-reference/compare_ignore
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/version_match.tmpl
Labels: approved, lgtm, jira/valid-reference, ztp/reference

#2090 CNF-15048: Enforce cluster version for this reference to be 4.16
  ztp/kube-compare-reference/ClusterVersionOperator.yaml
  ztp/kube-compare-reference/compare_ignore
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/version_match.tmpl
Labels: approved, lgtm, jira/valid-reference, ztp/reference

#2073 infra: CNF-14990: Replace abandoned gimme tool & Provide alignment for golang version
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
  vendor/github.com/lack/mcmaker/Makefile
  vendor/github.com/lack/mcmaker/pkg/mcmaker.go
  vendor/modules.txt
  ztp/tools/pgt2acmpg/go.mod
Labels: approved, lgtm, jira/valid-reference

#2085 [release-4.16] Backport CNF-14991: Fix instability in policy-generator-plugin usage
  ztp/tools/pgt2acmpg/.gitignore
  ztp/tools/pgt2acmpg/scripts/build-acmpg-plugin.sh
Labels: approved, lgtm, jira/valid-reference

#2084 [release-4.17] Backport CNF-14991: Fix instability in policy-generator-plugin usage
  ztp/tools/pgt2acmpg/.gitignore
  ztp/tools/pgt2acmpg/scripts/build-acmpg-plugin.sh
Labels: approved, lgtm, jira/valid-reference

#2096 CNF-14178: ztp: reference: Use binary realease of helm-convert instead of go install [release-4.16]
  ztp/kube-compare-reference/Makefile
Labels: approved, lgtm, jira/valid-reference, ztp/reference

#2095 CNF-15048: ztp: reference: Use binary release of helm-convert instead of go install [release-4.17]
  ztp/kube-compare-reference/Makefile
Labels: approved, lgtm, jira/valid-reference, ztp/reference

#2091 [release-4.17] infra: CNF-14990: Replace abandoned gimme tool & Provide alignment for golang version
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
  vendor/github.com/lack/mcmaker/Makefile
  vendor/github.com/lack/mcmaker/pkg/mcmaker.go
  vendor/modules.txt
  ztp/resource-generator/Containerfile
  ztp/tools/pgt2acmpg/go.mod
Labels: approved, lgtm, jira/valid-reference

#2092 ztp: CNF-14990: Fix golang ocp builder image in resource generator
  go.mod
  ztp/resource-generator/Containerfile
Labels: approved, lgtm, jira/valid-reference

#2094 CNF-15059: ztp: reference: Use binary realease of helm-convert instead of go install [master]
  ztp/kube-compare-reference/Makefile
Labels: approved, lgtm, jira/valid-reference, ztp/reference
