Repository openshift-kni/cnf-features-deploy, pull requests merged in 2024-02, with the labels that each got.

#1703 [release-4.14] ztp: OCPBUGS-23298: fix chrony contention
  ztp/extra-manifests-builder/99-sync-time-once/build.sh
  ztp/source-crs/extra-manifest/99-sync-time-once-master.yaml
  ztp/source-crs/extra-manifest/99-sync-time-once-worker.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1814 ztp: Bump ignition testdata version from `3.2.0` to `3.4.0`
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/siteConfigHelper_test.go
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/01-predefined-mc-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/01-predefined-mc-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/image-registry-partition-mc.yaml.tmpl
  ztp/siteconfig-generator/siteConfig/testdata/extra-manifest/workload/03-workload-partitioning.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigV2TestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/01-container-mount-ns-and-kubelet-conf-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/01-container-mount-ns-and-kubelet-conf-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/04-accelerated-container-startup-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/04-accelerated-container-startup-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/06-kdump-master.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/06-kdump-worker.yaml
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/disk-encryption.yaml.tmpl
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/image-registry-partition-mc.yaml.tmpl
  ztp/siteconfig-generator/siteConfig/testdata/source-cr-extra-manifest-copy/workload/03-workload-partitioning.yaml
Labels: approved, lgtm

#1751 ztp: Disable sriov operator injector and webhook pods
  ztp/source-crs/SriovOperatorConfig-SetSelector.yaml
  ztp/source-crs/SriovOperatorConfig.yaml
Labels: approved, lgtm

#1820 ztp: Relocate the IBU source-cr
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/example-oadp-policy.yaml
  ztp/source-crs/ImageBasedUpgrade.yaml
  ztp/source-crs/ibu/ImageBasedUpgrade.yaml
  ztp/source-crs/ibu/ImageBasedUpgradeStatus.yaml
Labels: approved, lgtm

#1818 ztp: OCPBUGS-25820: Include SiteConfig error in SiteConfig Content
  ztp/siteconfig-generator/main.go
  ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1659 ztp: CNF-9748: Add ZAP labelling
  ztp/siteconfig-generator/siteConfig/clusterCRsV2.go
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutputWithZap.yaml
Labels: approved, lgtm, jira/valid-reference

#1777 cnf-tests: Deprecate ioutil
  cnf-tests/mirror/mirror.go
  cnf-tests/pod-utils/pkg/node/node.go
  cnf-tests/pod-utils/stresser/main.go
  cnf-tests/testsuites/e2esuite/sctp/sctp.go
  ztp/policygenerator/testSource/TestAssertions.go
  ztp/policygenerator/testSource/TestGetters.go
  ztp/policygenerator/testSource/TestHelpers.go
  ztp/siteconfig-generator/siteConfig/filesHandler.go
  ztp/tools/policy-object-template-diff/main.go
Labels: approved, lgtm, ok-to-test

#1829 cnf-tests: Print podman logs before the check
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1813 cnf-tests: Import consistency
  cnf-tests/testsuites/e2esuite/sctp/sctp.go
  cnf-tests/testsuites/e2esuite/vrf/vrf.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
Labels: approved, lgtm, ok-to-test

#1831 Cherry pick ibu content
  ztp/gitops-subscriptions/argocd/example/README.md
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/README.md
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/example-oadp-policy.yaml
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/kustomization.yaml
  ztp/source-crs/ibu/ImageBasedUpgrade.yaml
  ztp/source-crs/ibu/ImageBasedUpgradeStatus.yaml
  ztp/source-crs/ibu/PlatformBackupRestore.yaml
Labels: approved, lgtm

#1811 OCPBUGS-25794: cnf-tests: sriov-network-operator bump 4.14
  go.mod
  go.sum
  vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/test/util/cluster/cluster.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1837 infra: always skip frr-k8s tests
  hack/run-functests.sh
Labels: approved, lgtm
