Repository openshift-kni/cnf-features-deploy, pull requests merged in 2024-03, with the labels that each got.

#1839 ztp: OCPBUGS-27893: OperatorHub.yaml is missing from the ztp source-crs
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-mno-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/kustomization.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-mno-ranGen.yaml
  ztp/source-crs/OperatorHub.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1836 ztp: OCPBUGS-25259: remove workaround for ice module in kdump
  ztp/extra-manifests-builder/05-kdump-config/build.sh
  ztp/extra-manifests-builder/05-kdump-config/kdump-remove-ice-module.sh
  ztp/extra-manifests-builder/05-kdump-config/test.sh
  ztp/source-crs/extra-manifest/05-kdump-config-master.yaml
  ztp/source-crs/extra-manifest/05-kdump-config-worker.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1838 infra: Create `SriovOperatorConfig` while deploying
  feature-configs/deploy/sriov/04-sriov-operator-config.yaml
  feature-configs/deploy/sriov/kustomization.yaml
Labels: approved, lgtm

#1674 ZTP: Add tpm disk encryption with PCRs and solution for upgrade
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/README.md
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/build.sh
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/disablePcrOnRebootOrShutdown.sh
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/efibootmgr-output.txt
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/hwupgrade-detection-methods/file.sh
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/hwupgrade-detection-methods/fwup.sh
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/hwupgrade-detection-methods/ostree.sh
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/hwupgrade-detection-methods/talm.sh
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/luks-helpers.sh
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/pcr-disable-shutdown.service
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/pcr-rebind-boot.service
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/rebindDiskOnBoot.sh
  ztp/extra-manifests-builder/01-disk-encryption-pcr-rebind/test.sh
  ztp/ran-crd/site-config-crd.yaml
  ztp/siteconfig-generator-kustomize-plugin/kustomization.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site-diskencryption-nbde.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site-diskencryption-none.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site-diskencryption-tpm2.yaml
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/source-crs/extra-manifest/01-disk-encryption-pcr-rebind-master.yaml
  ztp/source-crs/extra-manifest/01-disk-encryption-pcr-rebind-worker.yaml
  ztp/source-crs/extra-manifest/disk-encryption.yaml.tmpl
Labels: approved, lgtm, ok-to-test

#1824 [release-4.14] ztp: OCPBUGS-30886: Include SiteConfig error in SiteConfig Content
  ztp/siteconfig-generator/main.go
  ztp/siteconfig-generator/siteConfig/siteConfigHelper.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1854 OCPBUGS-29706: PtpConfigSlave.yaml and PtpConfigSlaveCvl.yaml are identical
  ztp/source-crs/PtpConfigSlaveCvl.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
