Repository openshift-kni/cnf-features-deploy, pull requests merged in 2024-01, with the labels that each got.

#1739 telco: Add bondcni to testing
  .githooks/components.sh
  Makefile
Labels: approved, lgtm

#1736 cnf-tests: Update OCP version to 4.16
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  cnf-tests/mirror/images.json
  cnf-tests/testsuites/pkg/images/images.go
  feature-configs/deploy/s2i/build-config.yaml
  hack/common.sh
  ztp/resource-generator/Containerfile
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
Labels: approved, lgtm

#1742 infra: Reduce wget verbosity to unhide tests logs in Prow
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1728 ztp: OCPBUGS-24657: fix manifest for vector
  ztp/source-crs/ClusterLogging.yaml
Labels: approved, lgtm, ok-to-test, jira/valid-bug, jira/valid-reference

#1755 cnf-tests: revert test image to rhel8
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
Labels: approved, lgtm

#1707 Add .snyk file for static code analysis
  .snyk
Labels: approved, lgtm

#1722 OCPBUGS-24435: Fix for `VRF integration Integration: SRIOV, IPAM: static, Interfaces: 1, Scheme: 2 Pods 2 VRFs OCP Primary network overlap`
  cnf-tests/testsuites/e2esuite/vrf/vrf.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1727 CNF-9624: Add IBU CR to ztp/source-crs
  ztp/source-crs/ImageBasedUpgrade.yaml
Labels: approved, lgtm, jira/valid-reference

#1763 ztp: OCPBUGS-26540: Enable cgroups v1 during installation
  ztp/source-crs/extra-manifest/enable-cgroups-v1.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1769 ocpbugs-26931: Fix wrong cast
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
Labels: approved, lgtm, jira/valid-reference

#1772 ztp: revert base image to RHEL8
  ztp/resource-generator/Containerfile
Labels: approved, lgtm

#1729 owners: Add Sabbir Hasan to review and approval list for ZTP and RAN
  OWNERS_ALIASES
Labels: approved, lgtm

#1750 infra: Parse results to HTML
  Makefile
  cnf-tests/testsuites/pkg/j2html/j2html.go
  hack/common.sh
  hack/run-functests.sh
Labels: approved, lgtm

#1774 cnf-tests: Pass command line arguments to latency-e2e.test
  cnf-tests/entrypoint/test-run.sh
Labels: approved, lgtm, ok-to-test

#1773 OCPBUGS-27031: Don't skip a NMStateConfig over-ride
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/nmstateconfig.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1787 ztp: [4.15] pin policygenerator version to v1.12.4
  ztp/gitops-subscriptions/Makefile
Labels: approved, lgtm

#1782 OCPBUGS-27158: Pass command line arguments to latency-e2e.test
  cnf-tests/entrypoint/test-run.sh
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1797 [release-4.15] ztp: update SMA cable delay on PtpConfigDualCardGmWpc
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
Labels: approved, lgtm

#1795 ztp: update SMA cable delay on PtpConfigDualCardGmWpc
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
Labels: approved, lgtm

#1780 cnf-tests: Fixes snyk file content
  .snyk
Labels: approved, lgtm, ok-to-test

#1776 cnf-tests: `sriov/numa` clean configuration
  cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
Labels: approved, lgtm

#1799 ztp: pin policygenerator version to v1.12.4
  ztp/gitops-subscriptions/Makefile
Labels: approved, lgtm

#1803 Separate ZTP and CNF-Tests CI Jobs
  Makefile
Labels: approved, lgtm

#1792 ztp: CNF-10923: disk partitioning for `/var/lib/containers`
  ztp/gitops-subscriptions/argocd/DiskPartiitionContainers.md
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
Labels: approved, lgtm, jira/valid-reference

#1783 ztp: CNF-9622: Create IBU platform OADP backup and restore CRs
  ztp/gitops-subscriptions/argocd/example/README.md
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/README.md
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/example-oadp-policy.yaml
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/kustomization.yaml
  ztp/source-crs/ibu/PlatformBackupRestore.yaml
Labels: approved, lgtm, jira/valid-reference

#1766 cnf-tests: Fix fec secure boot test case
  cnf-tests/testsuites/e2esuite/fec/fec.go
Labels: approved, lgtm, ok-to-test
