Repository openshift-kni/cnf-features-deploy, pull requests merged in 2024-07, with the labels that each got.

#1957 [release-4.15] OCPBUGS-36503: Add documentation to explain how to select the multicluster-operators-subscription image
  ztp/gitops-subscriptions/argocd/README.md
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1959 infra: Create a special hypershift-ci feature config
  feature-configs/hypershift-ci/metallb/kustomization.yaml
  feature-configs/hypershift-ci/metallb/operator_subscription.yaml
  feature-configs/hypershift-ci/multinetworkpolicy/kustomization.yaml
  feature-configs/hypershift-ci/ptp/kustomization.yaml
  feature-configs/hypershift-ci/ptp/subscription.yaml
  feature-configs/hypershift-ci/s2i/kustomization.yaml
  feature-configs/hypershift-ci/s2i/post_deploy.sh
  feature-configs/hypershift-ci/sriov/kustomization.yaml
  feature-configs/hypershift-ci/sriov/sriov-subscription.yaml
  hack/common.sh
  hack/setup-test-cluster.sh
Labels: approved, lgtm

#1963 infra: Fix subscription of SRIOV for Hypershift CI
  feature-configs/hypershift-ci/sriov/sriov-subscription.yaml
Labels: approved, lgtm

#1961 OCPBUGS-36695: remove space from ptp4lopts for PTP HA
  ztp/source-crs/PtpConfigForHAForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1967 cnf-tests: use sriov config daemon for exec instead of mco
  cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
  cnf-tests/testsuites/pkg/nodes/nodes.go
  cnf-tests/testsuites/pkg/utils/consts.go
Labels: approved, lgtm

#1973 OCPBUGS-37118: ztp: fix NAV-TIMELS reporting period
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1940 ztp: DU profile RDS rules to work with kube-compare
  ztp/kube-compare-reference/README.md
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageClass.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageLV.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageNS.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageOperGroup.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageSubscription.yaml
  ztp/kube-compare-reference/optional/ptp-fast-event-notifications/PtpOperatorConfigForEvent.yaml
  ztp/kube-compare-reference/optional/sriov-fec-operator/AcceleratorsNS.yaml
  ztp/kube-compare-reference/optional/sriov-fec-operator/AcceleratorsOperGroup.yaml
  ztp/kube-compare-reference/optional/sriov-fec-operator/AcceleratorsSubscription.yaml
  ztp/kube-compare-reference/optional/sriov-fec-operator/SriovFecClusterConfig.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogNS.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogOperGroup.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogSubscription.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogging.yaml
  ztp/kube-compare-reference/required/cluster-tuning/disabling-network-diagnostics/DisableSnoNetworkDiag.yaml
  ztp/kube-compare-reference/required/cluster-tuning/monitoring-configuration/ReduceMonitoringFootprint.yaml
  ztp/kube-compare-reference/required/cluster-tuning/operator-hub/DefaultCatsrc.yaml
  ztp/kube-compare-reference/required/cluster-tuning/operator-hub/DisconnectedICSP.yaml
  ztp/kube-compare-reference/required/cluster-tuning/operator-hub/OperatorHub.yaml
  ztp/kube-compare-reference/required/machine-config/crun/enable-crun-master.yaml
  ztp/kube-compare-reference/required/machine-config/crun/enable-crun-worker.yaml
  ztp/kube-compare-reference/required/machine-config/disable-crio-wipe/99-crio-disable-wipe-master.yaml
  ztp/kube-compare-reference/required/machine-config/disable-crio-wipe/99-crio-disable-wipe-worker.yaml
  ztp/kube-compare-reference/required/machine-config/kubelet-configuration-and-container-mount-hiding/01-container-mount-ns-and-kubelet-conf-master.yaml
  ztp/kube-compare-reference/required/machine-config/kubelet-configuration-and-container-mount-hiding/01-container-mount-ns-and-kubelet-conf-worker.yaml
  ztp/kube-compare-reference/required/machine-config/one-shot-time-sync/99-sync-time-once-master.yaml
  ztp/kube-compare-reference/required/machine-config/one-shot-time-sync/99-sync-time-once-worker.yaml
  ztp/kube-compare-reference/required/machine-config/sctp/03-sctp-machine-config-master.yaml
  ztp/kube-compare-reference/required/machine-config/sctp/03-sctp-machine-config-worker.yaml
  ztp/kube-compare-reference/required/machine-config/set-rcu-normal/08-set-rcu-normal-master.yaml
  ztp/kube-compare-reference/required/machine-config/set-rcu-normal/08-set-rcu-normal-worker.yaml
  ztp/kube-compare-reference/required/machine-config/sriov-related-kernel-arguments/07-sriov-related-kernel-args-master.yaml
  ztp/kube-compare-reference/required/machine-config/sriov-related-kernel-arguments/07-sriov-related-kernel-args-worker.yaml
  ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml
  ztp/kube-compare-reference/required/node-tuning-operator/TunedPerformancePatch.yaml
  ztp/kube-compare-reference/required/ptp-operator/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/required/ptp-operator/PtpConfigGmWpc.yaml
  ztp/kube-compare-reference/required/ptp-operator/PtpSubscription.yaml
  ztp/kube-compare-reference/required/ptp-operator/PtpSubscriptionNS.yaml
  ztp/kube-compare-reference/required/ptp-operator/PtpSubscriptionOperGroup.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovNetwork.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovNetworkNodePolicy.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfig.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovSubscription.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovSubscriptionNS.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovSubscriptionOperGroup.yaml
  ztp/kube-compare-reference/validate_node_selector.tmpl
Labels: approved, lgtm

#1979 ztp: Fix diffs between ref and source-crs
  ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml
  ztp/kube-compare-reference/required/ptp-operator/PtpConfigGmWpc.yaml
Labels: approved, lgtm

#1978 Update OADP subscription to channel 1.4
  ztp/source-crs/OadpSubscription.yaml
Labels: approved, lgtm
