Repository openshift-kni/cnf-features-deploy, pull requests merged in 2024-11, with the labels that each got.

#2104 [release-4.15] ztp: remove unsupported KlusterletAddonConfig clusterLabels and update managecluster CR to include cloud and vendor label
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/deployment/allow-acm-managedcluster-control.json
  ztp/gitops-subscriptions/argocd/deployment/clusters-app.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/KlusterletAddonConfigOverride.yaml
  ztp/siteconfig-generator/siteConfig/clusterCRsV1.go
  ztp/siteconfig-generator/siteConfig/clusterCRsV2.go
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingArgocdAnnotation.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadata.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadataAnnotations.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-NotTemplated.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigV2TestOutput.yaml
Labels: approved, lgtm

#2105 [release-4.14] ztp: remove unsupported KlusterletAddonConfig clusterLabels and update managecluster CR to include cloud and vendor label
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/deployment/allow-acm-managedcluster-control.json
  ztp/gitops-subscriptions/argocd/deployment/clusters-app.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/KlusterletAddonConfigOverride.yaml
  ztp/siteconfig-generator/siteConfig/clusterCRs.go
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingArgocdAnnotation.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadata.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadataAnnotations.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-NotTemplated.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Labels: approved, lgtm

#2107 ztp: fix lint policies-app.yaml
  ztp/gitops-subscriptions/argocd/deployment/policies-app.yaml
Labels: approved, lgtm

#2098 infra: Add tests results to the main job page
  hack/run-functests.sh
Labels: approved, lgtm

#2110 cnf-tests: increase `WaitForAllMCPStable` timeout
  cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go
Labels: approved, lgtm

#2114 cnf-tests: Reduce size of cnf-tests image
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
Labels: approved, lgtm

#2108 CNF-13528: ztp: reference: Use capturegroupInlineDiff for PTPConfig
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigBoundary.yaml
  ztp/source-crs/PtpConfigBoundaryForEvent.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-reference, ztp/reference

#2102 ztp: reference: remove duplicated records
  ztp/kube-compare-reference/metadata.yaml
Labels: approved, lgtm, ok-to-test

#2103 ztp: reference: delete duplicated records
  ztp/kube-compare-reference/metadata.yaml
Labels: approved, lgtm, ok-to-test

#2120 cnf-tests: delete NADs between tuning tests
  cnf-tests/testsuites/e2esuite/security/tuning.go
Labels: approved, lgtm

#2115 CNF-15605: ztp: reference: Use capturegroupInlineDiff for PTPConfig [4.17]
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigBoundary.yaml
  ztp/source-crs/PtpConfigBoundaryForEvent.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-reference

#2118 CNF-15792: ztp: reference: Use capturegroupInlineDiff for PTPConfig [4.14]
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigBoundary.yaml
  ztp/source-crs/PtpConfigBoundaryForEvent.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-reference

#2117 CNF-15791: ztp: reference: Use capturegroupInlineDiff for PTPConfig [4.15]
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigBoundary.yaml
  ztp/source-crs/PtpConfigBoundaryForEvent.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-reference

#2119 CNF-15582: ztp: reference: Add description text to metadata.yaml
  ztp/kube-compare-reference/metadata.yaml
Labels: approved, lgtm, jira/valid-reference, ztp/reference
