Repository openshift-kni/cnf-features-deploy, pull requests merged in 2024-05, with the labels that each got.

#1890 OCPBUGS-32756: Add documentation to explain how to select the multicluster-operators-subscription image
  ztp/gitops-subscriptions/argocd/README.md
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1897 ztp: Fix fips=true tag in siteconfig-generator test code
  ztp/siteconfig-generator/siteConfig/siteConfigHelper_test.go
Labels: approved, lgtm

#1896 OCPBUGS-33364: ztp: Add IBU examples
  ztp/Makefile
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/README.md
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/acm-ibu-upgrade-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/example-oadp-policy.yaml
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/ibu-upgrade-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/kustomization.yaml
  ztp/source-crs/ConfigMapGeneric.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1899 OCPBUGS-33527: ztp: Update ice-dplls tuning to SCHED_FIFO 10
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/site-du-sno-ranGen.yaml
  ztp/source-crs/TunedPerformancePatch.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1892 OCPBUGS-33004: ztp: move IPsec directory to argocd/example
  ztp/gitops-subscriptions/argocd/example/optional-extra-manifest/ipsec/README.md
  ztp/gitops-subscriptions/argocd/example/optional-extra-manifest/ipsec/build.sh
  ztp/gitops-subscriptions/argocd/example/optional-extra-manifest/ipsec/enable-ipsec.yaml
  ztp/gitops-subscriptions/argocd/example/optional-extra-manifest/ipsec/ipsec-endpoint-config.yml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1903 ztp: CNF-12580: Remove LVMO operator
  ztp/source-crs/StorageLVMOSubscription.yaml
  ztp/source-crs/StorageLVMOSubscriptionNS.yaml
  ztp/source-crs/StorageLVMOSubscriptionOperGroup.yaml
  ztp/source-crs/StorageLVMSubscription.yaml
  ztp/tools/pgt2acmpg/README.md
Labels: approved, lgtm, jira/valid-reference

#1905 ztp: CNF-12718: improve json data readability in Siteconfig
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/acm-ibu-upgrade-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/ibu-upgrade-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site-diskencryption-nbde.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site-diskencryption-none.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site-diskencryption-tpm2.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-err.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-du.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site1-sno-expansion.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-sno-du.yaml
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/site2-standard-du.yaml
Labels: approved, lgtm, jira/valid-reference

#1898 OCPBUGS-33349: ztp: Add one-shot time sync on boot
  ztp/extra-manifests-builder/99-sync-time-once/build.sh
  ztp/source-crs/extra-manifest/99-sync-time-once-master.yaml
  ztp/source-crs/extra-manifest/99-sync-time-once-worker.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1908 ztp: CNF-11904: Update kustomize and SiteConfig versions
  ztp/gitops-subscriptions/Makefile
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
  ztp/policygenerator-kustomize-plugin/Makefile
  ztp/siteconfig-generator-kustomize-plugin/Makefile
Labels: approved, lgtm, jira/valid-reference

#1912 ztp: change IBU source cr to v1
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/README.md
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/acm-ibu-upgrade-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/image-based-upgrades/ibu-upgrade-ranGen.yaml
  ztp/source-crs/ibu/ImageBasedUpgrade.yaml
  ztp/source-crs/ibu/ImageBasedUpgradeStatus.yaml
Labels: approved, lgtm

#1913 infra: fix build index image for ocp version 4.16
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1891 CNF-12277: chore: move LVMS to mgmt cores
  ztp/source-crs/StorageLVMSubscriptionNS.yaml
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#1914 OCPBUGS-33597: Add TIMELS indication on T-GMs
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1917 OCPBUGS-34064: ZTP tuned patch typo: s/ice-dppls/ice-dplls/
  ztp/source-crs/TunedPerformancePatch.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
