Repository openshift-kni/cnf-features-deploy, pull requests merged in 2024-06, with the labels that each got.

#1916 OCPBUGS-34603: Add a new set of PTP configurations for events in source CRs with additional PTP options
  ztp/source-crs/PtpConfigBoundaryForEvent.yaml
  ztp/source-crs/PtpConfigForHAForEvent.yaml
  ztp/source-crs/PtpConfigMasterForEvent.yaml
  ztp/source-crs/PtpConfigSlaveForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1918 OCPBUGS-33524: change ptp4lOpts from empty spaced string to null
  ztp/source-crs/PtpConfigForHA.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1927 ztp: OCPBUGS-35225 - update ZTP Example with Ingress Capability
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
Labels: approved, lgtm

#1926 OCPBUGS-35105: Update ptpconfig to configure NAV-TIMELS to be periodically sent via the UBX-CFG-MSG message
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1901 OCPBUGS-33573: ztp: IPsec: configure local gateway mode
  ztp/gitops-subscriptions/argocd/example/optional-extra-manifest/ipsec/enable-ipsec.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1934 Add ClusterImageSet CR in the whitelist of policies-app-project
  ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
Labels: approved, lgtm, needs-ok-to-test

#1936 Revert "Add ClusterImageSet CR in the whitelist of policies-app-project" to fix commit message
  ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
Labels: approved, lgtm, needs-ok-to-test

#1937 Add ClusterImageSet CR in the whitelist of policies-app-project
  ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
Labels: approved, lgtm, needs-ok-to-test

#1938 infra: Support ARM64 platform in jobs
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#1848 cnf-tests: Update README.md
  README.md
  cnf-tests/README.md
Labels: approved, lgtm

#1945 ztp: add install and config CRs for LCA and OADP operators
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-sno-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml
  ztp/source-crs/LcaOperatorStatus.yaml
  ztp/source-crs/LcaSubscription.yaml
  ztp/source-crs/LcaSubscriptionNS.yaml
  ztp/source-crs/LcaSubscriptionOperGroup.yaml
  ztp/source-crs/OadpBackupStorageLocationStatus.yaml
  ztp/source-crs/OadpDataProtectionApplication.yaml
  ztp/source-crs/OadpOperatorStatus.yaml
  ztp/source-crs/OadpSecret.yaml
  ztp/source-crs/OadpSubscription.yaml
  ztp/source-crs/OadpSubscriptionNS.yaml
  ztp/source-crs/OadpSubscriptionOperGroup.yaml
Labels: approved, lgtm

#1865 CNF-11528: ztp: Add accelerated ZTP doc
  ztp/gitops-subscriptions/argocd/AcceleratedZtp.md
Labels: approved, lgtm, jira/valid-reference

#1939 infra: fixes branch to build the list of commits
  hack/verify-commits.sh
Labels: approved, lgtm

#1935 infra: Bump go v1.22 in CI jobs
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#1930 cnf-tests: Read guaranteed CPU list for cgroupv2
  cnf-tests/testsuites/e2esuite/dpdk/dpdk.go
  cnf-tests/testsuites/e2esuite/s2i/s2i.go
  tools/s2i-dpdk/test/test-app/run.sh
Labels: approved, lgtm
