Repository openshift-kni/cnf-features-deploy, pull requests merged in 2024-08, with the labels that each got.

#1981 ztp: OCPBUGS-37572: Fix aZTP for SiteConfig v1
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1980 [release-4.16] infra: Updated submodules refs
  Makefile
Labels: approved, lgtm

#1983 ztp: Update ref config with additional expected variation
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/required/cluster-tuning/operator-hub/DefaultCatsrc.yaml
  ztp/kube-compare-reference/required/cluster-tuning/operator-hub/DisconnectedICSP.yaml
Labels: approved, lgtm

#1972 ztp: Extend IPsec optional feature to support SNO+1 and MNO
  ztp/gitops-subscriptions/argocd/example/optional-extra-manifest/ipsec/README.md
  ztp/gitops-subscriptions/argocd/example/optional-extra-manifest/ipsec/configure-ipsec.sh
  ztp/gitops-subscriptions/argocd/example/optional-extra-manifest/ipsec/import-certs.sh
  ztp/gitops-subscriptions/argocd/example/optional-extra-manifest/ipsec/ipsec-config-policy.yaml
  ztp/gitops-subscriptions/argocd/example/optional-extra-manifest/ipsec/ipsec-endpoint-config.yml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-3node-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-standard-ranGen.yaml
  ztp/source-crs/NMState.yaml
  ztp/source-crs/NMStateOperatorStatus.yaml
  ztp/source-crs/NMStateSubscription.yaml
  ztp/source-crs/NMStateSubscriptionNS.yaml
  ztp/source-crs/NMStateSubscriptionOperGroup.yaml
Labels: approved, lgtm

#1982 ztp: CNF-13810: add missing CR for kube-compare
  ztp/kube-compare-reference/README.md
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/console-disable/ConsoleOperatorDisable.yaml
  ztp/kube-compare-reference/optional/image-registry/ImageRegistryConfig.yaml
  ztp/kube-compare-reference/optional/image-registry/ImageRegistryPV.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHA.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveCvl.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpOperatorConfig.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpOperatorConfigForEvent.yaml
  ztp/kube-compare-reference/optional/storage/StorageLV.yaml
  ztp/kube-compare-reference/optional/storage/StorageLVMCluster.yaml
  ztp/kube-compare-reference/optional/storage/StorageLVMSubscription.yaml
  ztp/kube-compare-reference/optional/storage/StorageLVMSubscriptionNS.yaml
  ztp/kube-compare-reference/optional/storage/StorageLVMSubscriptionOperGroup.yaml
  ztp/kube-compare-reference/optional/storage/StoragePV.yaml
  ztp/kube-compare-reference/optional/storage/StoragePVC.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogForwarder.yaml
  ztp/kube-compare-reference/required/cluster-tuning/09-openshift-marketplace-ns.yaml
  ztp/kube-compare-reference/required/cluster-tuning/DisableOLMPprof.yaml
  ztp/kube-compare-reference/required/lca/LcaSubscription.yaml
  ztp/kube-compare-reference/required/lca/LcaSubscriptionNS.yaml
  ztp/kube-compare-reference/required/lca/LcaSubscriptionOperGroup.yaml
  ztp/kube-compare-reference/required/machine-config/kdump/06-kdump-master.yaml
  ztp/kube-compare-reference/required/machine-config/kdump/06-kdump-worker.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfigForSNO.yaml
Labels: approved, lgtm, jira/valid-reference

#1994 Minor cleanup of annotated reference config
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageLV.yaml
  ztp/kube-compare-reference/optional/local-storage-operator/StorageOperGroup.yaml
  ztp/kube-compare-reference/optional/sriov-fec-operator/AcceleratorsOperGroup.yaml
  ztp/kube-compare-reference/optional/storage/StorageLVMSubscriptionOperGroup.yaml
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogOperGroup.yaml
  ztp/kube-compare-reference/required/cluster-tuning/operator-hub/DisconnectedICSP.yaml
  ztp/kube-compare-reference/required/lca/LcaSubscriptionOperGroup.yaml
  ztp/kube-compare-reference/required/ptp-operator/PtpSubscriptionOperGroup.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovSubscriptionOperGroup.yaml
Labels: approved, lgtm

#2000 ztp: Add ClusterInstance to allowable CR types
  ztp/gitops-subscriptions/argocd/deployment/app-project.yaml
Labels: approved, lgtm

#2001 ztp: make UEFISecureBoot default in 4.17 example yamls
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-3node.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-sno.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/example-standard.yaml
Labels: approved, lgtm, ok-to-test

#1998 add disableDrain: true in SriovOperatorConfigForSNO.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfigForSNO.yaml
Labels: approved, lgtm, ok-to-test

#2003 CNF-14015: removed BMER references from ZTP source CRs and example du configs
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/acm-group-du-sno-ranGen-templated.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/hub-side-templating/configMaps/group-zones-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/common-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/group-du-sno-ranGen.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/configMaps/group-zones-configmap.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/hub-side-templating/group-du-sno-ranGen-templated.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/common-ranGen.yaml
  ztp/policygenerator-kustomize-plugin/testPolicyGenTemplate/group-du-sno-ranGen.yaml
  ztp/source-crs/BareMetalEventRelaySubscription.yaml
  ztp/source-crs/BareMetalEventRelaySubscriptionNS.yaml
  ztp/source-crs/BareMetalEventRelaySubscriptionOperGroup.yaml
  ztp/source-crs/HardwareEvent.yaml
Labels: approved, lgtm, jira/valid-reference

#1999 ignore more annotations
  ztp/kube-compare-reference/metadata.yaml
Labels: approved, lgtm, ok-to-test

#1986 ztp: Change ArgoCD apps default deletion behavior
  ztp/gitops-subscriptions/argocd/deployment/clusters-app.yaml
Labels: approved, lgtm, ok-to-test

#1991 infra: bump `OPERATOR_VERSION` to 4.17
  cnf-tests/hack/init-git-submodules.sh
  hack/common.sh
Labels: approved, lgtm

#2004 CNF-13996: ztp: add ptpEventConfig.apiVersion in PtpOperatorConfig
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm, jira/valid-reference

#1886 [release-4.15] ztp: OCPBUGS-32918: Siteconfig blocks MNO cluster deployment for more or less than 3 master nodes
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfig_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2005 OCPBUGS-38489: ztp: remove unsupported KlusterletAddonConfig clusterLabels and update managecluster CR to include cloud and vendor label
  ztp/gitops-subscriptions/argocd/README.md
  ztp/gitops-subscriptions/argocd/deployment/allow-acm-managedcluster-control.json
  ztp/gitops-subscriptions/argocd/deployment/clusters-app.yaml
  ztp/gitops-subscriptions/argocd/example/siteconfig/KlusterletAddonConfigOverride.yaml
  ztp/siteconfig-generator/siteConfig/clusterCRsV1.go
  ztp/siteconfig-generator/siteConfig/clusterCRsV2.go
  ztp/siteconfig-generator/siteConfig/siteConfig.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingArgocdAnnotation.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadata.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-MissingMetadataAnnotations.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride-NotTemplated.yaml
  ztp/siteconfig-generator/siteConfig/testdata/KlusterletAddonConfigOverride.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutputWithZap.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigV2TestOutput.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2011 OCPBUGS-39095: ztp: DU reference should mark LCA operator as optional
  ztp/kube-compare-reference/metadata.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2014 OCPBUGS-38945: ztp: Reference: Allow SriovNetworkNodePolicy to be fully customizable
  ztp/kube-compare-reference/required/sriov-operator/SriovNetworkNodePolicy.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
