Repository openshift-kni/cnf-features-deploy, pull requests merged in 2025-09, with the labels that each got.

#2929 tools: Fix namespace for pod to build index image
  hack/setup-build-index-image.sh
Labels: approved, do-not-merge/hold, lgtm

#2931 Revert "ztp: update policygenerator makefile"
  ztp/policygenerator-kustomize-plugin/Makefile
Labels: approved, lgtm

#2913 infra: OCPBUGS-59702: update golog to 1.2.4 [release-4.12]
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_linux.go
  vendor/github.com/golang/glog/glog_file_nonwindows.go
  vendor/github.com/golang/glog/glog_file_other.go
  vendor/github.com/golang/glog/glog_file_posix.go
  vendor/github.com/golang/glog/glog_file_windows.go
  vendor/github.com/golang/glog/glog_flags.go
  vendor/github.com/golang/glog/internal/logsink/logsink.go
  vendor/github.com/golang/glog/internal/logsink/logsink_fatal.go
  vendor/github.com/golang/glog/internal/stackdump/stackdump.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2957 ztp: CNF-19507: remove cachito directory
  ztp/resource-generator/tools/cachito/build_requirements.in
  ztp/resource-generator/tools/cachito/build_requirements.txt
  ztp/resource-generator/tools/cachito/requirements.in
  ztp/resource-generator/tools/cachito/requirements.txt
  ztp/resource-generator/tools/cachito/setup.cfg
Labels: approved, lgtm, jira/valid-reference

#2987 Fix rpm lockfile task & Re-run lockfile task
  cnf-tests/.konflux/lock-runtime/rpms.lock.yaml
  cnf-tests/Makefile
Labels: approved, lgtm

#3006 infra: Fix git submodule syncing
  Makefile
  cnf-tests/Makefile
  ztp/resource-generator/Makefile
Labels: approved, lgtm

#3014 [release-4.14] infra: Fix git submodule syncing
  Makefile
  cnf-tests/Makefile
  ztp/resource-generator/Makefile
Labels: approved, lgtm
