Repository openshift-kni/cnf-features-deploy, pull requests merged in 2025-06, with the labels that each got.

#2572 Upversion golang to 1.23 in release-4.19
  .gitmodules
  go.mod
  ztp/resource-generator/Containerfile
Labels: approved, lgtm, ok-to-test

#2425 OCPBUGS-55771: ran powersave reference 4.18
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml
  ztp/kube-compare-reference/required/node-tuning-operator/TunedPerformancePatch.yaml
  ztp/kube-compare-reference/unordered_list.tmpl
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2438 cnf-tests: konflux 4.18 onboarding
  .tekton/cnf-tests-4-18-pull-request.yaml
  .tekton/cnf-tests-4-18-push.yaml
  cnf-tests/.konflux/Dockerfile
  cnf-tests/.konflux/OWNERS
  cnf-tests/.konflux/README.md
  cnf-tests/.konflux/rpms.in.yaml
  cnf-tests/.konflux/rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#2435 [release-4.19] cnf-tests konflux backports
  .tekton/cnf-tests-4-19-pull-request.yaml
  .tekton/cnf-tests-4-19-push.yaml
  cnf-tests/.konflux/Dockerfile
  cnf-tests/.konflux/rpms.in.yaml
  cnf-tests/.konflux/rpms.lock.yaml
  cnf-tests/Dockerfile.openshift
Labels: approved, lgtm

#2502 cnf-tests: konflux 4.14 onboarding
  .tekton/cnf-tests-4-14-pull-request.yaml
  .tekton/cnf-tests-4-14-push.yaml
  cnf-tests/.konflux/Dockerfile
  cnf-tests/.konflux/OWNERS
  cnf-tests/.konflux/README.md
  cnf-tests/.konflux/rpms.in.yaml
  cnf-tests/.konflux/rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#2596 ztp: fix tekton target branch in 4.12
  .tekton/ztp-site-generate-4-12-pull-request.yaml
  .tekton/ztp-site-generate-4-12-push.yaml
Labels: approved, lgtm, ok-to-test

#2501 cnf-tests: konflux 4.15 onboarding
  .tekton/cnf-tests-4-15-pull-request.yaml
  .tekton/cnf-tests-4-15-push.yaml
  cnf-tests/.konflux/Dockerfile
  cnf-tests/.konflux/OWNERS
  cnf-tests/.konflux/README.md
  cnf-tests/.konflux/rpms.in.yaml
  cnf-tests/.konflux/rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#2446 cnf-tests: konflux 4.16 onboarding
  .tekton/cnf-tests-4-16-pull-request.yaml
  .tekton/cnf-tests-4-16-push.yaml
  cnf-tests/.konflux/Dockerfile
  cnf-tests/.konflux/OWNERS
  cnf-tests/.konflux/README.md
  cnf-tests/.konflux/rpms.in.yaml
  cnf-tests/.konflux/rpms.lock.yaml
Labels: approved, lgtm, ok-to-test

#2599 chore(deps): update tasks references
  .tekton/cnf-tests-4-19-pull-request.yaml
  .tekton/cnf-tests-4-19-push.yaml
  .tekton/ztp-site-generate-4-19-pull-request.yaml
  .tekton/ztp-site-generate-4-19-push.yaml
Labels: approved, lgtm

#2600 cnf-tests: tekton: misplaced additional_tags
  .tekton/cnf-tests-4-20-push.yaml
Labels: approved, lgtm

#2604 cnf-tests: tekton: misplaced additional_tags
  .tekton/cnf-tests-4-16-push.yaml
Labels: approved, lgtm

#2601 cnf-tests: tekton: misplaced additional_tags
  .tekton/cnf-tests-4-19-push.yaml
Labels: approved, lgtm

#2606 cnf-tests: tekton: misplaced additional_tags
  .tekton/cnf-tests-4-14-push.yaml
Labels: approved, lgtm

#2603 cnf-tests: tekton: misplaced additional_tags
  .tekton/cnf-tests-4-17-push.yaml
Labels: approved, lgtm

#2605 cnf-tests: tekton: misplaced additional_tags
  .tekton/cnf-tests-4-15-push.yaml
Labels: approved, lgtm

#2602 cnf-tests: tekton: misplaced additional_tags
  .tekton/cnf-tests-4-18-push.yaml
Labels: approved, lgtm

#2607 cnf-tests: tekton: misplaced additional_tags
  .tekton/cnf-tests-4-12-push.yaml
Labels: approved, lgtm

#2613 cnf-tests: k5x: bump rhel 9.4 -> 9.6
  cnf-tests/.konflux/Dockerfile
  cnf-tests/.konflux/rpms.in.yaml
  cnf-tests/.konflux/rpms.lock.yaml
Labels: approved, lgtm

#2688 [release-4.19] cnf-tests: k5x: update to latest RPMs (namely pam)
  cnf-tests/.konflux/rpms.in.yaml
  cnf-tests/.konflux/rpms.lock.yaml
Labels: approved, lgtm

#2696 [release-4.14] cnf-tests: k5x: add missing SUITE_PATH
  cnf-tests/.konflux/Dockerfile
Labels: approved, lgtm

#2695 [release-4.12] cnf-tests: k5x: add missing SUITE_PATH
  cnf-tests/.konflux/Dockerfile
Labels: approved, lgtm
