Repository openshift-kni/cnf-features-deploy, pull requests merged in 2025-01, with the labels that each got.

#2093 [release-4.16] infra: CNF-14990: Replace abandoned gimme tool & Provide alignment for golang version
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
  vendor/github.com/lack/mcmaker/Makefile
  vendor/github.com/lack/mcmaker/pkg/mcmaker.go
  vendor/modules.txt
  ztp/tools/pgt2acmpg/go.mod
Labels: approved, lgtm, jira/valid-reference

#2139 CNF-15235: cnf-tests: move to rhel 9
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  cnf-tests/mirror/images.json
  cnf-tests/pod-utils/hugepages-allocator/main.go
  cnf-tests/testsuites/pkg/images/images.go
  cnf-tests/testsuites/pkg/pods/pods.go
Labels: approved, lgtm, jira/valid-reference

#2152 infra: sriov git submodule should point to `main`
  Makefile
Labels: approved, lgtm

#2146 [release-4.15] OCPBUGS-47798: Ensure BMH deletion before InfrEnv and NS
  ztp/siteconfig-generator/siteConfig/clusterCRsV1.go
  ztp/siteconfig-generator/siteConfig/clusterCRsV2.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badName.yaml
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badNamespace.yaml
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigV2TestOutput.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2157 commit verify 4.14
  hack/verify-commits.sh
Labels: approved, lgtm

#2155 commit verify 4.15
  hack/verify-commits.sh
Labels: approved, lgtm

#2159 OCPBUGS-48343: Update WPC GM e180 pin example to be more user-friendly
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2158 [release-4.14] OCPBUGS-48339: Ensure BMH deletion before InfrEnv and NS
  ztp/siteconfig-generator/siteConfig/clusterCRs.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badName.yaml
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride-badNamespace.yaml
  ztp/siteconfig-generator/siteConfig/testdata/BareMetalHostOverride.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/mergeMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/SplitAndMergeMachineConfigExpected/splitMC.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/onlyUserCR.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/partialfilter.yaml
  ztp/siteconfig-generator/siteConfig/testdata/filteredoutput/removeAll.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningDeprecatedTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigCPUPartitioningNewTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigDualStackStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigStandardClusterTestOutput.yaml
  ztp/siteconfig-generator/siteConfig/testdata/siteConfigTestOutput.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2135 [release-4.14] bump NTO deps
  cnf-tests/TESTLIST.md
  cnf-tests/docgen/e2e.json
  go.mod
  go.sum
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/configs/99-netdev-physical-rps.rules
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/configs/ocp-tuned-one-shot.service
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/scripts/clear-irqbalance-banned-cpus.sh
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/scripts/set-rps-mask.sh
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/tuned/openshift-node-performance
  vendor/github.com/openshift/cluster-node-tuning-operator/assets/performanceprofile/tuned/openshift-node-performance-rt
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/performanceprofile/v2/performanceprofile_types.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/tuned_types.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/performanceprofile/controller/performanceprofile/components/consts.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/performanceprofile/controller/performanceprofile/components/profile/profile.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/performanceprofile/utils/schedstat/schedstat.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/util/kernel.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/util/leaderelection.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/util/manifest.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/util/objectinfo.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/util/os.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/util/provider_id.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/util/ptr_cmp.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/util/strings_map.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/util/strings_slice.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/netqueues.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/1_performance/performance.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/utils/consts.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/utils/infrastructure/vm.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/utils/mcps/mcps.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  vendor/github.com/openshift/cluster-node-tuning-operator/test/e2e/performanceprofile/functests/utils/pods/pods.go
  vendor/github.com/openshift/library-go/LICENSE
  vendor/github.com/openshift/library-go/pkg/config/clusterstatus/clusterstatus.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/modules.txt
Labels: approved, lgtm

#2150 cnf-tests: delete Dockerfile
  cnf-tests/Dockerfile
Labels: approved, lgtm

#2126 OCPBUGS-42068: ztp: emptyfile in siteconfig and sitegen kustomize plugin backport
  ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/testUserExtraManifest/00-emptymanifest.yaml
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder.go
  ztp/siteconfig-generator/siteConfig/siteConfigBuilder_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2165 cnf-tests: Bump `OPERATOR_VERSION` to 4.19
  cnf-tests/mirror/images.json
  cnf-tests/testsuites/pkg/images/images.go
  hack/common.sh
Labels: approved, lgtm

#2186 [release-4.18]: Align test images version 4.18
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  cnf-tests/mirror/images.json
  cnf-tests/testsuites/pkg/images/images.go
  hack/run-functests.sh
Labels: approved, lgtm

#2192 fix dockerfile input
  .tekton/cnf-features-deploy-4-19-pull-request.yaml
Labels: approved, lgtm

#2188 ztp: modify ztp Containerfile for Konflux migration...
  ztp/resource-generator/Containerfile
Labels: approved, lgtm

#2193 ztp: OCPBUGS-48088: Add monitoring label for openshift-logging ns
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogNS.yaml
  ztp/source-crs/ClusterLogNS.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2194 OCPBUGS-47784: ztp: reference: Enable user customization of PTP priority1, priority2, and domainNumber fields
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
