Repository openshift-kni/cnf-features-deploy, pull requests merged in 2025-03, with the labels that each got.

#1712 cnf-tests: omit LatencyTestRun env variable
  cnf-tests/entrypoint/test-run.sh
  hack/run-functests.sh
Labels: approved, lgtm

#2177 OCPBUGS-49372: [4.17] ztp: remove phc2sys -w option
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2281 ztp: make ztp a hermetic build
  .tekton/ztp-site-generate-4-19-pull-request.yaml
  .tekton/ztp-site-generate-4-19-push.yaml
  ztp/resource-generator/.konflux/README.md
  ztp/resource-generator/.konflux/rpms.in.yaml
  ztp/resource-generator/.konflux/rpms.lock.yaml
  ztp/resource-generator/.konflux/ubi.repo
Labels: approved, lgtm

#2289 infra: add `chore(deps)` to the list of components
  .githooks/components.sh
Labels: approved, lgtm

#1947 ztp: Add ClusterImageSet CR in the whitelist of policies-app-project
  ztp/gitops-subscriptions/argocd/deployment/policies-app-project.yaml
Labels: approved, lgtm, ok-to-test

#2291 OCPBUGS-52492: ztp: Set up ptpClockThreshold in source-crs and reference templates
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
  ztp/source-crs/PtpConfigBoundaryForEvent.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigForHAForEvent.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigMasterForEvent.yaml
  ztp/source-crs/PtpConfigSlaveForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2300 OCPBUGS-52877: ztp: reference: Make SriovOperatorConfig optional fields truly optional
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfig.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#2231 [release-4.16] CNF-15765: CI fixes
  cnf-tests/Dockerfile.openshift
  cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
  cnf-tests/testsuites/e2esuite/security/tuning.go
  cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go
  cnf-tests/testsuites/pkg/nodes/nodes.go
  cnf-tests/testsuites/pkg/utils/consts.go
Labels: approved, lgtm, jira/valid-reference

#2314 CNF-16811: ztp: Add an example PtpConfig and reference template for the T-GM 3-card WPC
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigThreeCardGmWpc.yaml
  ztp/source-crs/PtpConfigThreeCardGmWpc.yaml
Labels: approved, lgtm, jira/valid-reference

#2319 ztp: Adjust 3-card PTP T-GM reference to not rely on fallback behavior
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigThreeCardGmWpc.yaml
Labels: approved, lgtm

#2315 ztp: Remove deprecated Event API version configuration
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpOperatorConfigForEvent.yaml
  ztp/source-crs/PtpOperatorConfigForEvent-SetSelector.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm, ok-to-test

#2309 ztp: reference: bump cluster-compare version check to 4.19
  ztp/kube-compare-reference/ClusterVersionOperator.yaml
Labels: approved, lgtm

#2320 OCPBUGS-53275: ztp: Add an example PtpConfig and reference template for the T-GM 3-card WPC
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigThreeCardGmWpc.yaml
  ztp/source-crs/PtpConfigThreeCardGmWpc.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2178 OCPBUGS-49373: [4.16] ztp: remove phc2sys -w option
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2305 ztp: CNF-15573: Add reboot manifests
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/README.md
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-multinode-reboot.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-sno-reboot.yaml
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/kustomization.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-multinode-reboot.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-reboot.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/kustomization.yaml
  ztp/kube-compare-reference/compare_ignore
  ztp/source-crs/RebootMachineConfig.yaml
  ztp/source-crs/validatorCRs/rebootMachineConfigPoolValidator.yaml
Labels: approved, lgtm, jira/valid-reference

#2266 [release-4.18] Revert CNF-13652: Test integration of SRIOV and NMState operators#1990
  Makefile
  cnf-tests/testsuites/e2esuite/knmstate/knmstate_sriov.go
  cnf-tests/testsuites/e2esuite/test_suite_test.go
  cnf-tests/testsuites/pkg/client/clients.go
  feature-configs/ci/knmstate/kustomization.yaml
  feature-configs/ci/knmstate/operator_subscription.yaml
  feature-configs/deploy/knmstate/kustomization.yaml
  feature-configs/deploy/knmstate/operator_namespace.yaml
  feature-configs/deploy/knmstate/operator_operatorgroup.yaml
  feature-configs/deploy/knmstate/operator_subscription.yaml
  go.mod
  go.sum
  hack/setup-build-index-image.sh
  vendor/github.com/nmstate/kubernetes-nmstate/api/LICENSE
  vendor/github.com/nmstate/kubernetes-nmstate/api/names/names.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/condition_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkconfigurationenactment_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkstate_util.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/state_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/zz_generated.deepcopy.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/groupversion_info.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nmstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/zz_generated.deepcopy.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/groupversion_info.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/nmstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/nodenetworkconfigurationenactment_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/nodenetworkstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#2234 cnf-tests: MultiNetworkPolicy `DiscoverSriov(...)` fix
  cnf-tests/testsuites/e2esuite/multinetworkpolicy/multinetworkpolicy_sriov.go
Labels: approved, lgtm

#2338 infra: Bump fedora to 41 in Dockerfile.tools
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#2333 ztp: add dual-follower ptpconfig example
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualFollower.yaml
  ztp/source-crs/PtpConfigDualFollower.yaml
Labels: approved, lgtm

#2327 ztp: Allow vfio kernel args to be optional
  ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml
  ztp/kube-compare-reference/unordered_list.tmpl
  ztp/source-crs/PerformanceProfile.yaml
Labels: approved, lgtm

#2332 infra: update `cluster-node-tuning` ref to `main`
  Makefile
  cnf-tests/README.md
Labels: approved, lgtm
