Repository openshift-kni/cnf-features-deploy, pull requests merged in 2025-05, with the labels that each got.

#2400 infra: CNF-16868: verify and restrict ztp commits
  .githooks/commit-msg
  hack/verify-commits.sh
Labels: approved, lgtm, jira/valid-reference

#2389 ztp: CNF-17690: update gitops-subscriptions, siteconfig and policygenerator binaries to use telco-reference submodule
  ztp/gitops-subscriptions/ACMPolicyGeneratorIntergration.md
  ztp/gitops-subscriptions/Makefile
  ztp/policygenerator-kustomize-plugin/Makefile
  ztp/policygenerator/README.md
  ztp/siteconfig-generator-kustomize-plugin/Makefile
  ztp/siteconfig-generator/README.md
Labels: approved, lgtm, jira/valid-reference

#2408 cnf-tests: tekton: tag konflux images as latest
  .tekton/cnf-tests-4-19-push.yaml
Labels: approved, lgtm

#2410 ztp: resource-generator konflux conforma
  .tekton/ztp-site-generate-4-19-pull-request.yaml
  .tekton/ztp-site-generate-4-19-push.yaml
  ztp/resource-generator/.konflux/rpms.lock.yaml
Labels: approved, lgtm

#2421 infra: use multi-arch fedora
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#2422 cnf-tests:k5x: adapt official conforma
  cnf-tests/.konflux/Dockerfile
Labels: approved, lgtm

#2428 cnf-tests: konflux dockerfile updates
  cnf-tests/.konflux/Dockerfile
Labels: approved, lgtm

#2430 ztp: update konflux lockfile
  .tekton/ztp-site-generate-4-19-pull-request.yaml
  .tekton/ztp-site-generate-4-19-push.yaml
  build-args-konflux.conf
  renovate.json
  ztp/.konflux/build-args-konflux.conf
  ztp/resource-generator/.konflux/OWNERS
  ztp/resource-generator/.konflux/redhat.repo
  ztp/resource-generator/.konflux/rpms.in.yaml
  ztp/resource-generator/.konflux/rpms.lock.yaml
  ztp/resource-generator/.konflux/ubi.repo
Labels: approved, lgtm, ok-to-test

#2434 fix ztp-site-generate push tekton file
  .tekton/ztp-site-generate-4-19-push.yaml
Labels: approved, lgtm

#2416 cnf-tests: add `findutils` binary
  cnf-tests/.konflux/Dockerfile
  cnf-tests/.konflux/rpms.in.yaml
  cnf-tests/.konflux/rpms.lock.yaml
  cnf-tests/Dockerfile.openshift
Labels: approved, lgtm, ok-to-test

#2436 tekton: up version ztp-site-generate tekton to 4.20
  .tekton/ztp-site-generate-4-20-pull-request.yaml
  .tekton/ztp-site-generate-4-20-push.yaml
Labels: approved, lgtm

#2387 OCPBUGS-55255: Align test images version 4.14
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  hack/run-functests.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2328 ztp: Support the patching of stringData in Secret source files
  ztp/policygenerator/policyGen/policyBuilder.go
  ztp/policygenerator/policyGen/policyBuilder_test.go
  ztp/policygenerator/policyGen/testData/GenericSourceFiles/GenericSecret.yaml
  ztp/policygenerator/utils/utils.go
Labels: approved, lgtm, ok-to-test

#2455 ztp: lock acmpg version for release-4.16
  ztp/tools/pgt2acmpg/scripts/build-acmpg-plugin.sh
Labels: approved, lgtm

#2469 tekton: backport konflux to release 4.19
  .tekton/ztp-site-generate-4-19-pull-request.yaml
  .tekton/ztp-site-generate-4-19-push.yaml
  build-args-konflux.conf
  ztp/.konflux/OWNERS
  ztp/.konflux/build-args-konflux.conf
  ztp/resource-generator/.konflux/OWNERS
  ztp/resource-generator/.konflux/redhat.repo
  ztp/resource-generator/.konflux/rpms.in.yaml
  ztp/resource-generator/.konflux/rpms.lock.yaml
Labels: approved, lgtm

#2470 tekton: add owners file in ztp konflux
  ztp/.konflux/OWNERS
Labels: approved, lgtm

#2508 cnf-tests: tekton: update on-cel-expression
  .tekton/cnf-tests-4-20-pull-request.yaml
  .tekton/cnf-tests-4-20-push.yaml
Labels: approved, lgtm

#2517 infra: lock gitmodule branches
  .gitmodules
Labels: approved, lgtm

#2512 ztp: backport ztp konflux to release-4.19
  .tekton/ztp-site-generate-4-19-pull-request.yaml
  .tekton/ztp-site-generate-4-19-push.yaml
  renovate.json
  ztp/.konflux/OWNERS
  ztp/.konflux/build-args-konflux.conf
  ztp/resource-generator/Containerfile
Labels: approved, lgtm

#2511 ztp: konflux updates in master
  .tekton/ztp-site-generate-4-20-pull-request.yaml
  .tekton/ztp-site-generate-4-20-push.yaml
  renovate.json
  ztp/.konflux/OWNERS
  ztp/.konflux/build-args-konflux.conf
  ztp/resource-generator/Containerfile
Labels: approved, lgtm

#2109 cnf-tests: Add debug information for flake tests
  cnf-tests/testsuites/e2esuite/dpdk/numa_node_sriov.go
  cnf-tests/testsuites/pkg/pods/pods.go
Labels: approved, lgtm

#2563 tekton: update service account in ztp 4.20
  .tekton/ztp-site-generate-4-20-pull-request.yaml
  .tekton/ztp-site-generate-4-20-push.yaml
Labels: approved, lgtm

#2567 cnf-tests: k5x: add OWNERS file
  cnf-tests/.konflux/OWNERS
Labels: approved, lgtm

#2513 ztp: backport ztp konflux to release-4.16
  .tekton/OWNERS
  .tekton/ztp-site-generate-4-16-pull-request.yaml
  .tekton/ztp-site-generate-4-16-push.yaml
  OWNERS_ALIASES
  ztp/resource-generator/.konflux/OWNERS
  ztp/resource-generator/.konflux/README.md
  ztp/resource-generator/.konflux/redhat.repo
  ztp/resource-generator/.konflux/rpms.in.yaml
  ztp/resource-generator/.konflux/rpms.lock.yaml
  ztp/resource-generator/Containerfile
Labels: approved, lgtm, ok-to-test

#2509 ztp: backport ztp konflux to release-4.17
  .tekton/OWNERS
  .tekton/ztp-site-generate-4-17-pull-request.yaml
  .tekton/ztp-site-generate-4-17-push.yaml
  OWNERS_ALIASES
  ztp/resource-generator/.konflux/OWNERS
  ztp/resource-generator/.konflux/README.md
  ztp/resource-generator/.konflux/redhat.repo
  ztp/resource-generator/.konflux/rpms.in.yaml
  ztp/resource-generator/.konflux/rpms.lock.yaml
  ztp/resource-generator/Containerfile
Labels: approved, lgtm, ok-to-test

#2565 ztp: backport ztp konflux to release-4.12
  .tekton/OWNERS
  .tekton/ztp-site-generate-4-12-pull-request.yaml
  .tekton/ztp-site-generate-4-12-push.yaml
  OWNERS_ALIASES
  ztp/resource-generator/.konflux/OWNERS
  ztp/resource-generator/.konflux/README.md
  ztp/resource-generator/.konflux/redhat.repo
  ztp/resource-generator/.konflux/rpms.in.yaml
  ztp/resource-generator/.konflux/rpms.lock.yaml
  ztp/resource-generator/Containerfile
Labels: approved, lgtm, ok-to-test
