Repository openshift-kni/cnf-features-deploy, pull requests merged in 2025-04, with the labels that each got.

#2335 OCPBUGS-54381: ztp: Allow watch for policy evaluation intervals in PGT
  ztp/policygenerator/policyGen/policyBuilder_test.go
  ztp/policygenerator/policyGen/policyHelper.go
  ztp/policygenerator/utils/utils.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2343 OCPBUGS-54312: ztp: reference: Enable users to set PerformanceProfile perPodPowerManagement
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2347 OCPBUGS-54459: Align test images version 4.15
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  hack/run-functests.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2344 OCPBUGS-54194: ztp: reference: Allow PerformanceProfile kernelPageSize to optionally be set
  ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2168 Elaborated instructions for branching
  README.md
Labels: approved, lgtm

#2179 OCPBUGS-49374: [4.15] ztp: remove phc2sys -w option
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2352 [release-4.18] ztp: Lock ACM PG version
  ztp/tools/pgt2acmpg/scripts/build-acmpg-plugin.sh
Labels: approved, lgtm

#2349 CNF-13139: ztp: Add hardwareTuning to PerformanceProfile
  ztp/kube-compare-reference/required/node-tuning-operator/PerformanceProfile.yaml
  ztp/source-crs/PerformanceProfile-SetSelector.yaml
  ztp/source-crs/PerformanceProfile.yaml
Labels: approved, lgtm, jira/valid-reference

#2180 OCPBUGS-44603: [4.14] ztp: remove phc2sys -w option
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2354 [release-4.17] ztp: Lock ACM PG version
  ztp/tools/pgt2acmpg/scripts/build-acmpg-plugin.sh
Labels: approved, lgtm

#2350 cnf-tests: syscall deprecated; use sys/unix pkg
  cnf-tests/pod-utils/cyclictest-runner/main.go
  cnf-tests/pod-utils/hugepages-allocator/main.go
  cnf-tests/pod-utils/hwlatdetect-runner/main.go
  cnf-tests/pod-utils/oslat-runner/main.go
Labels: approved, lgtm, ok-to-test

#2345 cnf-tests: pointer deprecation: use 'ptr' instead
  cnf-tests/testsuites/e2esuite/multinetworkpolicy/reachmatcher.go
  cnf-tests/testsuites/e2esuite/sctp/sctp.go
  cnf-tests/testsuites/pkg/pods/pods.go
Labels: approved, lgtm, ok-to-test

#2373 ztp: README updates and renovate bot config update
  renovate.json
  ztp/extra-manifests-builder/README.md
  ztp/gitops-subscriptions/README.md
  ztp/kube-compare-reference/README.md
  ztp/source-crs/README.md
Labels: approved, lgtm

#2353 OCPBUGS-54517: ztp: reference: Ensure PtpOperatorConfig apiVersion is a string, and transportHost is optional
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpOperatorConfigForEvent.yaml
  ztp/source-crs/PtpOperatorConfigForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#2382 infra: validated renovate config
  renovate.json
Labels: approved, lgtm

#2355 cnf-tests: k5x: build source image
  .tekton/cnf-tests-4-19-pull-request.yaml
  .tekton/cnf-tests-4-19-push.yaml
  cnf-tests/.konflux/Dockerfile
  cnf-tests/.konflux/rpms.in.yaml
Labels: approved, lgtm

#2390 ztp: Update resource-generator to Trusted Artifacts Pipeline
  .tekton/ztp-site-generate-4-19-pull-request.yaml
  .tekton/ztp-site-generate-4-19-push.yaml
Labels: approved, lgtm

#2403 cnf-tests: 4.20 pipelines configuration
  .tekton/cnf-tests-4-19-pull-request.yaml
  .tekton/cnf-tests-4-19-push.yaml
  .tekton/cnf-tests-4-20-pull-request.yaml
  .tekton/cnf-tests-4-20-push.yaml
Labels: approved, lgtm
