Repository openshift-kni/cnf-features-deploy, pull requests merged in 2025-02, with the labels that each got.

#2174 OCPBUGS-48803: [4.19] ztp: remove phc2sys -w option
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2201 tekton owners + misc infra
  .tekton/OWNERS
  .tekton/cnf-features-deploy-4-19-pull-request.yaml
  .tekton/cnf-features-deploy-4-19-push.yaml
  build-args-konflux.conf
Labels: do-not-merge/invalid-owners-file

#2198 OCPBUGS-47784: ztp: reference: Enable user customization of PTP priority1, priority2, and domainNumber fields
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHA.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2205 OCPBUGS-49793: ztp: reference: Enable user customization of PTP priority1, priority2, and domainNumber [4.18]
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHA.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2206 OCPBUGS-44271: ztp: reference: Make SriovOperatorConfig optional fields truly optional
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfig.yaml
  ztp/kube-compare-reference/required/sriov-operator/SriovOperatorConfigForSNO.yaml
  ztp/source-crs/SriovOperatorConfigForSNO.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#2187 Dynamically select test image versions
  cnf-tests/Dockerfile.openshift
  hack/run-functests.sh
Labels: approved, lgtm

#2134 infra: Build images for `knmstate`
  cnf-tests/testsuites/e2esuite/knmstate/knmstate_sriov.go
  cnf-tests/testsuites/pkg/namespaces/namespaces.go
  cnf-tests/testsuites/pkg/utils/consts.go
  cnf-tests/testsuites/validationsuite/cluster/validation.go
  feature-configs/ci/knmstate/operator_subscription.yaml
  hack/setup-build-index-image.sh
Labels: approved, lgtm

#2217 fix ownership (needs lowercase references)
  .tekton/OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#2214 OCPBUGS-49786: ztp: Set up ptpClockThreshold in source-crs and reference templates
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHA.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
  ztp/source-crs/PtpConfigBoundaryForEvent.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigForHAForEvent.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigMasterForEvent.yaml
  ztp/source-crs/PtpConfigSlaveForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2215 OCPBUGS-49785: ztp: Default WPC-GM MaxInSpecOffset to 1500 and allow user configuration of all settings values
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2224 OCPBUGS-47784: ztp: Enforce PTP priority1 field must be 128 for telco ABMCA
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2225 OCPBUGS-49793: ztp: Enforce PTP priority1 field must be 128 for telco ABMCA
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2229 cnf-tests: Dump `openshift-multus` namespace on failure
  cnf-tests/testsuites/pkg/utils/reporter.go
  hack/run-functests.sh
Labels: approved, lgtm

#2230 [release-4.17] CNF-15765: CI fixes
  cnf-tests/Dockerfile.openshift
  cnf-tests/testsuites/e2esuite/security/tuning.go
  cnf-tests/testsuites/pkg/machineconfigpool/machineconfigpool.go
Labels: approved, lgtm, jira/valid-reference

#2239 OCPBUGS-48184: ztp: reference: Allow topolvm.io or kubernetes.io/no-provisioner for StorageClass provisioner
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/must_match_one_of.tmpl
  ztp/kube-compare-reference/optional/local-storage-operator/StorageClass.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2238 infra: skip Tekton checks (.tekton dir)
  .githooks/commit-msg
  .githooks/skipped-files.sh
Labels: approved, lgtm

#2242 ztp: update OadpBackupStorageLocationStatus source cr with metadata name
  ztp/gitops-subscriptions/argocd/example/acmpolicygenerator/acm-example-sno-site.yaml
  ztp/gitops-subscriptions/argocd/example/policygentemplates/example-sno-site.yaml
  ztp/source-crs/OadpBackupStorageLocationStatus.yaml
Labels: approved, lgtm

#2254 fix ztp build parameterization
  .tekton/ztp-site-generate-4-19-pull-request.yaml
  .tekton/ztp-site-generate-4-19-push.yaml
Labels: approved, lgtm

#2226 OCPBUGS-49815: ztp: reference: Enable user customization of PTP priority2 and domainNumber fields
  ztp/kube-compare-reference/default_value.yaml
  ztp/kube-compare-reference/metadata.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundary.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigBoundaryForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHA.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigForHAForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMaster.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigMasterForEvent.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlave.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigSlaveForEvent.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2255 owners: expand konflux reviewers and approvers (.tekton dir)
  OWNERS_ALIASES
Labels: approved, lgtm

#2256 infra: introduce reviewers for Konflux (.tekton dir)
  .tekton/OWNERS
Labels: approved, lgtm

#2191 OCPBUGS-50611: [release-4.16]: Align test images version 4.16
  cnf-tests/Dockerfile
  cnf-tests/Dockerfile.openshift
  hack/run-functests.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2199 Add script to check outdated image references
  Makefile
  hack/verify-images-updated.sh
Labels: approved, lgtm

#2176 OCPBUGS-49371: [4.18] ztp: remove phc2sys -w option
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigDualCardGmWpc.yaml
  ztp/kube-compare-reference/optional/ptp-config/PtpConfigGmWpc.yaml
  ztp/source-crs/PtpConfigDualCardGmWpc.yaml
  ztp/source-crs/PtpConfigGmWpc.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2273 infra: skip .tekton checks for staging files and upstream commits
  .githooks/check-skipped-files.sh
  .githooks/commit-msg
  hack/verify-commits.sh
Labels: approved, lgtm

#2277 rebase master changes
  .githooks/check-skipped-files.sh
  .githooks/commit-msg
  .tekton/OWNERS
  .tekton/cnf-features-deploy-4-19-pull-request.yaml
  .tekton/cnf-features-deploy-4-19-push.yaml
  Makefile
  OWNERS_ALIASES
  go.mod
  go.sum
  hack/verify-commits.sh
  hack/verify-images-updated.sh
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/NOTICE
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1beta1/types.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1beta2/types.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1beta2/zz_generated.deepcopy.go
  vendor/github.com/k8snetworkplumbingwg/multi-networkpolicy/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/openshift-kni/k8sreporter/client.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
  ztp/kube-compare-reference/required/cluster-logging/ClusterLogSubscription.yaml
  ztp/source-crs/ClusterLogSubscription.yaml
Labels: approved, lgtm

#2279 introduce ztp .tekton config
  .tekton/ztp-site-generate-4-19-pull-request.yaml
  .tekton/ztp-site-generate-4-19-push.yaml
Labels: approved, lgtm
